/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/amd/v1"
	typedamdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/clientset/versioned/typed/amd/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeResourceTemplates implements ResourceTemplateInterface
type fakeResourceTemplates struct {
	*gentype.FakeClientWithListAndApply[*v1.ResourceTemplate, *v1.ResourceTemplateList, *amdv1.ResourceTemplateApplyConfiguration]
	Fake *FakeAmdV1
}

func newFakeResourceTemplates(fake *FakeAmdV1, namespace string) typedamdv1.ResourceTemplateInterface {
	return &fakeResourceTemplates{
		gentype.NewFakeClientWithListAndApply[*v1.ResourceTemplate, *v1.ResourceTemplateList, *amdv1.ResourceTemplateApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("resourcetemplates"),
			v1.SchemeGroupVersion.WithKind("ResourceTemplate"),
			func() *v1.ResourceTemplate { return &v1.ResourceTemplate{} },
			func() *v1.ResourceTemplateList { return &v1.ResourceTemplateList{} },
			func(dst, src *v1.ResourceTemplateList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ResourceTemplateList) []*v1.ResourceTemplate { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.ResourceTemplateList, items []*v1.ResourceTemplate) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
