{
 "title": "K8S Overview",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(kube_node_info, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(kube_node_info{cluster=~\"$cluster\"}, node)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"}, namespace)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Memory Ratio",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "Memory Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "Memory Limit Rate"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$node$\"}[2m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU Utilization Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU Limit Rate"
    }
   ]
  },
  {
   "title": "Pod density",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\",node=~\"$node\"})\n/\nsum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Cluster CPU Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})/ sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Node Memory Information",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$node$\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Node CPU Number of cores",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$node$\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Nodes with Pod",
   "type": "bargauge",
   "description": "Number of cluster nodes，Nodes POD Number of，NodesPODUpper Limit",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{origin_prometheus=~\"$origin_prometheus\"})",
     "legendFormat": "Number of nodes"
    },
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$node$\"})",
     "legendFormat": "Pod Number of nodes"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$node$\"})",
     "legendFormat": "Upper limit Pod"
    }
   ]
  },
  {
   "title": "Cluster Memory  Requested",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"}) / sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\",node=~\"$node\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_info{node=~\"$node\",cluster=~\"$cluster\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{node=~\"$node\",cluster=~\"$cluster\",resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "limited"
    }
   ]
  },
  {
   "title": "Node Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\",cluster=~\"$cluster\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    },
    {
     "expr": "kube_node_status_condition{condition=~\"PIDPressure\",node=~\"$node\",cluster=~\"$cluster\",status=\"true\"}==1",
     "legendFormat": "{{node}} {{condition}}"
    }
   ]
  },
  {
   "title": "Taints",
   "type": "stat",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by(key)(kube_node_spec_taint{key=~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "count by(key)(kube_node_spec_taint{key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "$node：Node Information Detail",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$node$\"}) by (node)",
     "legendFormat": "pod Number"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$node$\"}[2m])) by (node)"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$node$\"}) by (node) - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "Memory Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "CPU Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "CPU Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})by (node)",
     "legendFormat": "Disk Usage%"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$node$\"})by (node)",
     "legendFormat": "PodCaps"
    }
   ]
  },
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Number Of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes Unavailable",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Node NotReady",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_condition{cluster=~\"$cluster\",condition=\"Ready\",status=\"false\"}==1",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "node number",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_info{cluster=~\"$cluster\"})"
    }
   ]
  },
  { "title": "Deployments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Updated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Unavailable",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Statefuleset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Statefulset Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=~\"$cluster\"}",
       "legendFormat": "{{ statefulset}}"
      }
     ]
    },
    {
     "title": "Statefulset replicas",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_ready{namespace=~\"$namespace\",cluster=~\"$cluster\"}/kube_statefulset_status_replicas{namespace=~\"$namespace\",cluster=~\"$cluster\"}*100",
       "legendFormat": "{{statefulset}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods restart in 30m",
     "type": "table",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m])>1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Evicted",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_pod_status_reason{cluster=~\"$cluster\",namespace=~\"$namespace\", reason=\"Evicted\"}==1",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{cluster=~\"$cluster\",namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",cluster=~\"$cluster\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\" ,cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "HPA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "hpa",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "current_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_max_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "max_{{hpa}}"
      },
      {
       "expr": "kube_hpa_spec_min_replicas{cluster=~\"$cluster\",namespace=~\"$namespace\"}",
       "legendFormat": "min_{{hpa}}"
      }
     ]
    },
    {
     "title": "total-hpa-current",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(kube_hpa_status_current_replicas{hpa=~\".*\"})",
       "legendFormat": "kube_hpa_status_current_replicas"
      }
     ]
    },
    {
     "title": "current==max",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_max_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    },
    {
     "title": "current==min",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_hpa_status_current_replicas{hpa=~\".*\"} == kube_hpa_spec_min_replicas{hpa=~\".*\"}",
       "legendFormat": "{{hpa}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 92 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Job last success time from now",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 92 },
     "targets": [
      {
       "expr": "(time()-kube_job_status_completion_time{namespace=~\"$namespace\",cluster=~\"$cluster\"})/60/60/24>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Job failed",
     "type": "table",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 92 },
     "targets": [
      {
       "expr": "kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"}>1",
       "legendFormat": "{{job_name}}"
      }
     ]
    },
    {
     "title": "Jobs Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 105 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 127 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\",cluster=~\"$cluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "pvc is bound",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc is not bound",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{phase!=\"Bound\"}==1)",
       "legendFormat": "{{persistentvolumeclaim=}}"
      }
     ]
    },
    {
     "title": "pvc",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes/1024/1024/1024",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}