// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock_s3 is a generated GoMock package.
package mock_s3

import (
	context "context"
	reflect "reflect"

	s3 "github.com/AMD-AIG-AIMA/SAFE/common/pkg/s3"
	s30 "github.com/aws/aws-sdk-go-v2/service/s3"
	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// AbortMultiPartUpload mocks base method.
func (m *MockInterface) AbortMultiPartUpload(ctx context.Context, param *s3.MultiUploadParam, timeout int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMultiPartUpload", ctx, param, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMultiPartUpload indicates an expected call of AbortMultiPartUpload.
func (mr *MockInterfaceMockRecorder) AbortMultiPartUpload(ctx, param, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMultiPartUpload", reflect.TypeOf((*MockInterface)(nil).AbortMultiPartUpload), ctx, param, timeout)
}

// CompleteMultiPartUpload mocks base method.
func (m *MockInterface) CompleteMultiPartUpload(ctx context.Context, param *s3.MultiUploadParam, timeout int64) (*s30.CompleteMultipartUploadOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteMultiPartUpload", ctx, param, timeout)
	ret0, _ := ret[0].(*s30.CompleteMultipartUploadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteMultiPartUpload indicates an expected call of CompleteMultiPartUpload.
func (mr *MockInterfaceMockRecorder) CompleteMultiPartUpload(ctx, param, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteMultiPartUpload", reflect.TypeOf((*MockInterface)(nil).CompleteMultiPartUpload), ctx, param, timeout)
}

// CreateMultiPartUpload mocks base method.
func (m *MockInterface) CreateMultiPartUpload(ctx context.Context, key string, timeout int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiPartUpload", ctx, key, timeout)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMultiPartUpload indicates an expected call of CreateMultiPartUpload.
func (mr *MockInterfaceMockRecorder) CreateMultiPartUpload(ctx, key, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiPartUpload", reflect.TypeOf((*MockInterface)(nil).CreateMultiPartUpload), ctx, key, timeout)
}

// DeleteObject mocks base method.
func (m *MockInterface) DeleteObject(ctx context.Context, key string, timeout int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, key, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockInterfaceMockRecorder) DeleteObject(ctx, key, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockInterface)(nil).DeleteObject), ctx, key, timeout)
}

// GeneratePresignedURL mocks base method.
func (m *MockInterface) GeneratePresignedURL(ctx context.Context, key string, expireDay int32) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, key, expireDay)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockInterfaceMockRecorder) GeneratePresignedURL(ctx, key, expireDay interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockInterface)(nil).GeneratePresignedURL), ctx, key, expireDay)
}

// MultiPartUpload mocks base method.
func (m *MockInterface) MultiPartUpload(ctx context.Context, param *s3.MultiUploadParam, timeout int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MultiPartUpload", ctx, param, timeout)
	ret0, _ := ret[0].(error)
	return ret0
}

// MultiPartUpload indicates an expected call of MultiPartUpload.
func (mr *MockInterfaceMockRecorder) MultiPartUpload(ctx, param, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MultiPartUpload", reflect.TypeOf((*MockInterface)(nil).MultiPartUpload), ctx, param, timeout)
}

// PutObject mocks base method.
func (m *MockInterface) PutObject(ctx context.Context, key, value string, timeout int64) (*s30.PutObjectOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutObject", ctx, key, value, timeout)
	ret0, _ := ret[0].(*s30.PutObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObject indicates an expected call of PutObject.
func (mr *MockInterfaceMockRecorder) PutObject(ctx, key, value, timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockInterface)(nil).PutObject), ctx, key, value, timeout)
}
