{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "log-alert-evaluator.serviceAccountName" . }}
  labels:
    {{- include "log-alert-evaluator.labels" . | nindent 4 }}
{{- end }}
