/*
 * Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apisamdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	versioned "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/clientset/versioned"
	internalinterfaces "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/informers/externalversions/internalinterfaces"
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/listers/amd/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FaultInformer provides access to a shared informer and lister for
// Faults.
type FaultInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() amdv1.FaultLister
}

type faultInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFaultInformer constructs a new informer for Fault type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFaultInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFaultInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFaultInformer constructs a new informer for Fault type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFaultInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AmdV1().Faults(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AmdV1().Faults(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AmdV1().Faults(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AmdV1().Faults(namespace).Watch(ctx, options)
			},
		},
		&apisamdv1.Fault{},
		resyncPeriod,
		indexers,
	)
}

func (f *faultInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFaultInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *faultInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisamdv1.Fault{}, f.defaultInformer)
}

func (f *faultInformer) Lister() amdv1.FaultLister {
	return amdv1.NewFaultLister(f.Informer().GetIndexer())
}
