// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLensAuthProviders = "lens_auth_providers"

// LensAuthProviders mapped from table <lens_auth_providers>
type LensAuthProviders struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	Enabled     bool      `gorm:"column:enabled;not null;default:true" json:"enabled"`
	Priority    int32     `gorm:"column:priority;not null" json:"priority"`
	Config      ExtType   `gorm:"column:config;not null" json:"config"`
	Status      string    `gorm:"column:status;not null;default:active" json:"status"`
	LastCheckAt time.Time `gorm:"column:last_check_at" json:"last_check_at"`
	LastError   string    `gorm:"column:last_error" json:"last_error"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	CreatedBy   string    `gorm:"column:created_by" json:"created_by"`
}

// TableName LensAuthProviders's table name
func (*LensAuthProviders) TableName() string {
	return TableNameLensAuthProviders
}
