/*
Copyright The AMD Authors.

*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
)

// AddonTemplateSpecApplyConfiguration represents a declarative configuration of the AddonTemplateSpec type for use
// with apply.
type AddonTemplateSpecApplyConfiguration struct {
	Type                 *amdv1.AddonTemplateType `json:"type,omitempty"`
	Category             *string                  `json:"category,omitempty"`
	URL                  *string                  `json:"url,omitempty"`
	Version              *string                  `json:"version,omitempty"`
	Description          *string                  `json:"description,omitempty"`
	Extensions           map[string]string        `json:"extensions,omitempty"`
	Icon                 *string                  `json:"icon,omitempty"`
	GpuChip              *amdv1.GpuChipType       `json:"gpuChip,omitempty"`
	GpuProduct           *amdv1.GpuChipProduct    `json:"gpuProduct,omitempty"`
	IsOneShotService     *bool                    `json:"isOneShotService,omitempty"`
	HelmDefaultValues    *string                  `json:"helmDefaultValues,omitempty"`
	HelmDefaultNamespace *string                  `json:"helmDefaultNamespace,omitempty"`
}

// AddonTemplateSpecApplyConfiguration constructs a declarative configuration of the AddonTemplateSpec type for use with
// apply.
func AddonTemplateSpec() *AddonTemplateSpecApplyConfiguration {
	return &AddonTemplateSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithType(value amdv1.AddonTemplateType) *AddonTemplateSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithCategory sets the Category field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Category field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithCategory(value string) *AddonTemplateSpecApplyConfiguration {
	b.Category = &value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithURL(value string) *AddonTemplateSpecApplyConfiguration {
	b.URL = &value
	return b
}

// WithVersion sets the Version field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Version field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithVersion(value string) *AddonTemplateSpecApplyConfiguration {
	b.Version = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithDescription(value string) *AddonTemplateSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithExtensions puts the entries into the Extensions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Extensions field,
// overwriting an existing map entries in Extensions field with the same key.
func (b *AddonTemplateSpecApplyConfiguration) WithExtensions(entries map[string]string) *AddonTemplateSpecApplyConfiguration {
	if b.Extensions == nil && len(entries) > 0 {
		b.Extensions = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Extensions[k] = v
	}
	return b
}

// WithIcon sets the Icon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Icon field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithIcon(value string) *AddonTemplateSpecApplyConfiguration {
	b.Icon = &value
	return b
}

// WithGpuChip sets the GpuChip field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GpuChip field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithGpuChip(value amdv1.GpuChipType) *AddonTemplateSpecApplyConfiguration {
	b.GpuChip = &value
	return b
}

// WithGpuProduct sets the GpuProduct field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GpuProduct field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithGpuProduct(value amdv1.GpuChipProduct) *AddonTemplateSpecApplyConfiguration {
	b.GpuProduct = &value
	return b
}

// WithIsOneShotService sets the IsOneShotService field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsOneShotService field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithIsOneShotService(value bool) *AddonTemplateSpecApplyConfiguration {
	b.IsOneShotService = &value
	return b
}

// WithHelmDefaultValues sets the HelmDefaultValues field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HelmDefaultValues field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithHelmDefaultValues(value string) *AddonTemplateSpecApplyConfiguration {
	b.HelmDefaultValues = &value
	return b
}

// WithHelmDefaultNamespace sets the HelmDefaultNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HelmDefaultNamespace field is set to the value of the last call.
func (b *AddonTemplateSpecApplyConfiguration) WithHelmDefaultNamespace(value string) *AddonTemplateSpecApplyConfiguration {
	b.HelmDefaultNamespace = &value
	return b
}
