/*
 * Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// CapacityApplyConfiguration represents a declarative configuration of the Capacity type for use
// with apply.
type CapacityApplyConfiguration struct {
	TotalBytes     *uint64 `json:"bytesTotal,omitempty"`
	UsedBytes      *uint64 `json:"bytesUsed,omitempty"`
	AvailableBytes *uint64 `json:"bytesAvailable,omitempty"`
	LastUpdated    *string `json:"lastUpdated,omitempty"`
}

// CapacityApplyConfiguration constructs a declarative configuration of the Capacity type for use with
// apply.
func Capacity() *CapacityApplyConfiguration {
	return &CapacityApplyConfiguration{}
}

// WithTotalBytes sets the TotalBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalBytes field is set to the value of the last call.
func (b *CapacityApplyConfiguration) WithTotalBytes(value uint64) *CapacityApplyConfiguration {
	b.TotalBytes = &value
	return b
}

// WithUsedBytes sets the UsedBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsedBytes field is set to the value of the last call.
func (b *CapacityApplyConfiguration) WithUsedBytes(value uint64) *CapacityApplyConfiguration {
	b.UsedBytes = &value
	return b
}

// WithAvailableBytes sets the AvailableBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailableBytes field is set to the value of the last call.
func (b *CapacityApplyConfiguration) WithAvailableBytes(value uint64) *CapacityApplyConfiguration {
	b.AvailableBytes = &value
	return b
}

// WithLastUpdated sets the LastUpdated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdated field is set to the value of the last call.
func (b *CapacityApplyConfiguration) WithLastUpdated(value string) *CapacityApplyConfiguration {
	b.LastUpdated = &value
	return b
}
