/*
Copyright The AMD Authors.

*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ContainerFailedMessageApplyConfiguration represents a declarative configuration of the ContainerFailedMessage type for use
// with apply.
type ContainerFailedMessageApplyConfiguration struct {
	Name     *string `json:"name,omitempty"`
	Reason   *string `json:"reason,omitempty"`
	Message  *string `json:"message,omitempty"`
	ExitCode *int32  `json:"exitCode,omitempty"`
	Signal   *int32  `json:"signal,omitempty"`
	Analysis *string `json:"analysis,omitempty"`
}

// ContainerFailedMessageApplyConfiguration constructs a declarative configuration of the ContainerFailedMessage type for use with
// apply.
func ContainerFailedMessage() *ContainerFailedMessageApplyConfiguration {
	return &ContainerFailedMessageApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ContainerFailedMessageApplyConfiguration) WithName(value string) *ContainerFailedMessageApplyConfiguration {
	b.Name = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *ContainerFailedMessageApplyConfiguration) WithReason(value string) *ContainerFailedMessageApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ContainerFailedMessageApplyConfiguration) WithMessage(value string) *ContainerFailedMessageApplyConfiguration {
	b.Message = &value
	return b
}

// WithExitCode sets the ExitCode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExitCode field is set to the value of the last call.
func (b *ContainerFailedMessageApplyConfiguration) WithExitCode(value int32) *ContainerFailedMessageApplyConfiguration {
	b.ExitCode = &value
	return b
}

// WithSignal sets the Signal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Signal field is set to the value of the last call.
func (b *ContainerFailedMessageApplyConfiguration) WithSignal(value int32) *ContainerFailedMessageApplyConfiguration {
	b.Signal = &value
	return b
}

// WithAnalysis sets the Analysis field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Analysis field is set to the value of the last call.
func (b *ContainerFailedMessageApplyConfiguration) WithAnalysis(value string) *ContainerFailedMessageApplyConfiguration {
	b.Analysis = &value
	return b
}
