/*
Copyright The AMD Authors.

*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// TemplatePhaseApplyConfiguration represents a declarative configuration of the TemplatePhase type for use
// with apply.
type TemplatePhaseApplyConfiguration struct {
	MatchExpressions map[string]string `json:"matchExpressions,omitempty"`
	Phase            *string           `json:"phase,omitempty"`
}

// TemplatePhaseApplyConfiguration constructs a declarative configuration of the TemplatePhase type for use with
// apply.
func TemplatePhase() *TemplatePhaseApplyConfiguration {
	return &TemplatePhaseApplyConfiguration{}
}

// WithMatchExpressions puts the entries into the MatchExpressions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the MatchExpressions field,
// overwriting an existing map entries in MatchExpressions field with the same key.
func (b *TemplatePhaseApplyConfiguration) WithMatchExpressions(entries map[string]string) *TemplatePhaseApplyConfiguration {
	if b.MatchExpressions == nil && len(entries) > 0 {
		b.MatchExpressions = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.MatchExpressions[k] = v
	}
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *TemplatePhaseApplyConfiguration) WithPhase(value string) *TemplatePhaseApplyConfiguration {
	b.Phase = &value
	return b
}
