/*
Copyright The AMD Authors.

*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// WorkloadSpecApplyConfiguration represents a declarative configuration of the WorkloadSpec type for use
// with apply.
type WorkloadSpecApplyConfiguration struct {
	Resource                *WorkloadResourceApplyConfiguration `json:"resource,omitempty"`
	Workspace               *string                             `json:"workspace,omitempty"`
	Image                   *string                             `json:"image,omitempty"`
	EntryPoint              *string                             `json:"entryPoint,omitempty"`
	Env                     map[string]string                   `json:"env,omitempty"`
	IsSSHEnabled            *bool                               `json:"isSSHEnabled,omitempty"`
	IsSupervised            *bool                               `json:"isSupervised,omitempty"`
	GroupVersionKind        *schema.GroupVersionKind            `json:"gvk,omitempty"`
	MaxRetry                *int                                `json:"maxRetry,omitempty"`
	Priority                *int                                `json:"priority,omitempty"`
	TTLSecondsAfterFinished *int                                `json:"ttlSecondsAfterFinished,omitempty"`
	Timeout                 *int                                `json:"timeout,omitempty"`
	CustomerLabels          map[string]string                   `json:"customerLabels,omitempty"`
	Liveness                *HealthCheckApplyConfiguration      `json:"liveness,omitempty"`
	Readiness               *HealthCheckApplyConfiguration      `json:"readiness,omitempty"`
	Service                 *ServiceApplyConfiguration          `json:"service,omitempty"`
}

// WorkloadSpecApplyConfiguration constructs a declarative configuration of the WorkloadSpec type for use with
// apply.
func WorkloadSpec() *WorkloadSpecApplyConfiguration {
	return &WorkloadSpecApplyConfiguration{}
}

// WithResource sets the Resource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resource field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithResource(value *WorkloadResourceApplyConfiguration) *WorkloadSpecApplyConfiguration {
	b.Resource = value
	return b
}

// WithWorkspace sets the Workspace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workspace field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithWorkspace(value string) *WorkloadSpecApplyConfiguration {
	b.Workspace = &value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithImage(value string) *WorkloadSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithEntryPoint sets the EntryPoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EntryPoint field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithEntryPoint(value string) *WorkloadSpecApplyConfiguration {
	b.EntryPoint = &value
	return b
}

// WithEnv puts the entries into the Env field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Env field,
// overwriting an existing map entries in Env field with the same key.
func (b *WorkloadSpecApplyConfiguration) WithEnv(entries map[string]string) *WorkloadSpecApplyConfiguration {
	if b.Env == nil && len(entries) > 0 {
		b.Env = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Env[k] = v
	}
	return b
}

// WithIsSSHEnabled sets the IsSSHEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsSSHEnabled field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithIsSSHEnabled(value bool) *WorkloadSpecApplyConfiguration {
	b.IsSSHEnabled = &value
	return b
}

// WithIsSupervised sets the IsSupervised field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsSupervised field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithIsSupervised(value bool) *WorkloadSpecApplyConfiguration {
	b.IsSupervised = &value
	return b
}

// WithGroupVersionKind sets the GroupVersionKind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupVersionKind field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithGroupVersionKind(value schema.GroupVersionKind) *WorkloadSpecApplyConfiguration {
	b.GroupVersionKind = &value
	return b
}

// WithMaxRetry sets the MaxRetry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRetry field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithMaxRetry(value int) *WorkloadSpecApplyConfiguration {
	b.MaxRetry = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithPriority(value int) *WorkloadSpecApplyConfiguration {
	b.Priority = &value
	return b
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithTTLSecondsAfterFinished(value int) *WorkloadSpecApplyConfiguration {
	b.TTLSecondsAfterFinished = &value
	return b
}

// WithTimeout sets the Timeout field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timeout field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithTimeout(value int) *WorkloadSpecApplyConfiguration {
	b.Timeout = &value
	return b
}

// WithCustomerLabels puts the entries into the CustomerLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the CustomerLabels field,
// overwriting an existing map entries in CustomerLabels field with the same key.
func (b *WorkloadSpecApplyConfiguration) WithCustomerLabels(entries map[string]string) *WorkloadSpecApplyConfiguration {
	if b.CustomerLabels == nil && len(entries) > 0 {
		b.CustomerLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CustomerLabels[k] = v
	}
	return b
}

// WithLiveness sets the Liveness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Liveness field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithLiveness(value *HealthCheckApplyConfiguration) *WorkloadSpecApplyConfiguration {
	b.Liveness = value
	return b
}

// WithReadiness sets the Readiness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Readiness field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithReadiness(value *HealthCheckApplyConfiguration) *WorkloadSpecApplyConfiguration {
	b.Readiness = value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *WorkloadSpecApplyConfiguration) WithService(value *ServiceApplyConfiguration) *WorkloadSpecApplyConfiguration {
	b.Service = value
	return b
}
