apiVersion: v1
data:
  key: {{ .Values.crypto.key }} 
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  .dockerconfigjson: e30=
kind: Secret
metadata:
  name: {{ .Release.Name }}-image
  namespace: {{ .Release.Namespace }}