{
 "title": "NodeHistory",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "node", "query": { "query": "label_values(gpu_health,node)" } }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization{node=\"$node\"} ",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Vram Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (gpu_package_power{node=\"$node\"}/gpu_total_vram{node=\"$node\"} * 100)",
     "legendFormat": "GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Package Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_package_power{node=\"$node\"} ",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Vram Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "gpu_total_vram{node=\"$node\"} - gpu_free_vram{node=\"$node\"}",
     "legendFormat": "GPU{{gpu_id}}"
    },
    {
     "expr": "max(gpu_total_vram{node=\"$node\"} )",
     "legendFormat": "Vram Total"
    }
   ]
  },
  {
   "title": "GPU Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "gpu_ecc_correct_athub{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret ATHUB GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_bif{node=\"$node\"}> 0",
     "legendFormat": "ECC Corret BIF GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_df{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret DF GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_fuse{node=\"$node\"}> 0",
     "legendFormat": "ECC Corret FUSE GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_gfx{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret GFX GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_hdp{node=\"$node\"}> 0",
     "legendFormat": "ECC Corret HDP GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_ih{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret IH GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_jpeg{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret JPEG GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_mca{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret MCA GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_mmhub{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret MMHUB GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_mp0{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret MP0 GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_mp1{node=\"$node\"}> 0",
     "legendFormat": "ECC Corret MP1 GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_mpio{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret MPIO GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_sdma{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret SDMA GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_sem{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret SEM GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_smn{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret SMN GPU{{gpu_id}}"
    },
    {
     "expr": "sgpu_ecc_correct_total{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret Total GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_umc{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret UMC GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_vcn{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret VCN GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_correct_xgmi_wafl{node=\"$node\"} > 0",
     "legendFormat": "ECC Corret WAFL GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_athub{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret ATHUB GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_bif{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret BIF GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_df{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret DF GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_fuse{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret FUSE GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_gfx{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret GFX GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_hdp{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret HDP GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_ih{node=\"$node\"}> 0",
     "legendFormat": "ECC UnCorret IH GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_jpeg{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret JPEG GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_mca{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret MCA GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_mmhub{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret MMHUB GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_mp0{node=\"$node\"}> 0",
     "legendFormat": "ECC UnCorret MP0 GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_mp1{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret MP1 GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_mpio{node=\"$node\"}> 0",
     "legendFormat": "ECC UnCorret MPIO GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_sdma{node=\"$node\"}> 0",
     "legendFormat": "ECC UnCorret SDMA GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_sem{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret SEM GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_smn{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret SMN GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_total{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret Tota GPUl{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_umc{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret UMC GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_vcn{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret VCN GPU{{gpu_id}}"
    },
    {
     "expr": "gpu_ecc_uncorrect_xgmi_wafl{node=\"$node\"} > 0",
     "legendFormat": "ECC UnCorret WAFL GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "XGMI Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(gpu_xgmi_link_tx{node=\"$node\"}[1m])) by (gpu_id)",
     "legendFormat": "GPU {{gpu_id}} TX"
    },
    {
     "expr": "sum(rate(gpu_xgmi_link_rx{node=\"$node\"}[1m])) by (gpu_id)",
     "legendFormat": "GPU {{gpu_id}} RX"
    }
   ]
  },
  {
   "title": "PCIE Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(pcie_bandwidth{node=\"$node\"}[1m])) by (gpu_id)",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "RDMA Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rdma_stat_tx_roce_only_bytes{node=\"$node\"}[1m])",
     "legendFormat": "{{device}} Tx"
    },
    {
     "expr": "rate(rdma_stat_rx_roce_only_bytes{node=\"$node\"}[1m])",
     "legendFormat": "{{device}} Rx"
    }
   ]
  },
  {
   "title": "RDMA Packets/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(rdma_stat_tx_pkts{node=\"$node\"}[1m])",
     "legendFormat": "{{device}} Tx"
    },
    {
     "expr": "rate(rdma_stat_rx_pkts{node=\"$node\"}[1m])",
     "legendFormat": "{{device}} Rx"
    }
   ]
  },
  {
   "title": "RDMA Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "increase(rdma_stat_rx_roce_discards{node=\"$node\"}) > 0",
     "legendFormat": "RX Roce Discards:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_tx_roce_discards{node=\"$node\"}) > 0",
     "legendFormat": "TX Roce Discards:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_tx_roce_errors{node=\"$node\"}[1m]) > 0",
     "legendFormat": "TX Roce Errors:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_rx_roce_errors{node=\"$node\"}[1m]) > 0",
     "legendFormat": "RX Roce Errors:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_seq_err_naks_rcvd{node=\"$node\"}[1m]) > 0",
     "legendFormat": "NAK(Seq err):{{device}}"
    },
    {
     "expr": "increase(rdma_stat_rnr_naks_rcvd{node=\"$node\"}[1m]) > 0",
     "legendFormat": "NAK(RNR):{{device}}"
    },
    {
     "expr": "increase(rdma_stat_missing_resp{node=\"$node\"}[1m]) > 0",
     "legendFormat": "Missing Resp:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_to_retransmits{node=\"$node\"}[1m]) > 0",
     "legendFormat": "ReTransmit:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_max_retry_exceeded{node=\"$node\"}[1m]) > 0",
     "legendFormat": "MaxRetryExceeded:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_missing_resp{node=\"$node\"}[1m]) > 0",
     "legendFormat": "MissingResp:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_unrecoverable_err{node=\"$node\"}[1m]) > 0",
     "legendFormat": "UnrecoverableErr:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_local_qp_op_err{node=\"$node\"}[1m]) > 0",
     "legendFormat": "LocalQpOpErr:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_local_protection_err{node=\"$node\"}[1m]) > 0",
     "legendFormat": "LocalProtectionErr:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_remote_access_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "RemoteAccessErr:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_remote_invalid_req_err{node=\"$node\"}[1m]) > 0",
     "legendFormat": "RemoteInvalidReqErr:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_remote_op_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "RemoteOpErr:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_opcode_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Opcode Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_domain_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Rx Domain Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_no_perm{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Rx No Perm:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_range_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Rx Range Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_domain_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Tx Domain Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_no_perm{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Tx No Perm:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_range_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Tx Range Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rem_inv_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Rem Inv Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_mem_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Mem Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_srq_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Srq Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_cmp_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Cmp Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_wqe_format_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Wqe Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_cq_load_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Cq Load Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_srq_load_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Srq Load Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_pci_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Tx Pci Err:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_pci_err{node=\"$node\"}[1m]) > 0 ",
     "legendFormat": "Res Rx Pci Err:{{device}}"
    }
   ]
  },
  {
   "title": "RDMA Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "increase(rdma_stat_dup_req{node=\"$node\"}[1m]) > 0",
     "legendFormat": "DupReq:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_exceed_max{node=\"$node\"}[1m]) > 0",
     "legendFormat": "ResExceedMax:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_length_mismatch{node=\"$node\"}[1m]) > 0",
     "legendFormat": "ResLengthMismatch:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_exceeds_wqe{node=\"$node\"}[1m]) > 0",
     "legendFormat": "ResExceedsWqe:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_invalid_rkey{node=\"$node\"}[1m]) > 0",
     "legendFormat": "Res Rx Invalid Rkey:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_invalid_rkey{node=\"$node\"}[1m]) > 0",
     "legendFormat": "Res Tx Invalid Rkey:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_irrq_oflow{node=\"$node\"}[1m]) > 0",
     "legendFormat": "Res Irrq Oflow:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_unsup_opcode{node=\"$node\"}[1m]) > 0",
     "legendFormat": "Res Unsupported OpCode:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_unaligned_atomic{node=\"$node\"}[1m]) > 0",
     "legendFormat": "Res Unaligned Atomic:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_missing_resp{node=\"$node\"}[1m]) > 0",
     "legendFormat": "MissingResp:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_invalid_dup_rkey{node=\"$node\"}[1m]) > 0",
     "legendFormat": "Res Invalid Dup Rkey:{{device}}"
    }
   ]
  }
 ]
}