{
 "title": "Workload Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "workload_uid",
    "query": {
     "query": "label_values(workload_gpu_clock,workload_uid)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tflops/Iteration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].metric" },
      { "jsonPath": "$.[*].value", "language": "jsonpath", "name": "", "type": "number" },
      { "jsonPath": "$.[*].timestamp", "language": "jsonpath", "name": "", "type": "time" }
     ],
     "method": "GET",
     "params": [
      [
       "start",
       "${__from}"
      ],
      [
       "end",
       "${__to}"
      ]
     ],
     "urlPath": "/v1/workloads/${workload_uid}/trainingPerformance"
    }
   ]
  },
  {
   "title": "RDMA Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_discards{workload_uid=\"$workload_uid\"})) by (node)> 0",
     "legendFormat": "RX Roce Discards:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_discards{workload_uid=\"$workload_uid\"})) by (node)> 0",
     "legendFormat": "TX Roce Discards:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "TX Roce Errors:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "RX Roce Errors:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_seq_err_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "NAK(Seq err):{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rnr_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "NAK(RNR):{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "Missing Resp:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_to_retransmits{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "ReTransmit:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_max_retry_exceeded{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "MaxRetryExceeded:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "MissingResp:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_unrecoverable_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "UnrecoverableErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_qp_op_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "LocalQpOpErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_protection_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "LocalProtectionErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_access_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "RemoteAccessErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_invalid_req_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "RemoteInvalidReqErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_op_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "RemoteOpErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_opcode_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Opcode Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rx Domain Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rx No Perm:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rx Range Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Tx Domain Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Tx No Perm:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Tx Range Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rem_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rem Inv Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_mem_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Mem Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Srq Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cmp_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Cmp Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_wqe_format_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Wqe Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Cq Load Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Srq Load Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Tx Pci Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rx Pci Err:{{node}}"
    }
   ]
  },
  {
   "title": "Tokens Per GPU/Iteration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].metric" },
      { "jsonPath": "$.[*].value", "language": "jsonpath", "name": "", "type": "number" },
      { "jsonPath": "$.[*].timestamp", "language": "jsonpath", "name": "", "type": "time" }
     ],
     "method": "GET",
     "params": [
      [
       "start",
       "${__from}"
      ],
      [
       "end",
       "${__to}"
      ]
     ],
     "urlPath": "/v1/workloads/${workload_uid}/trainingPerformance"
    }
   ]
  },
  { "title": "Training Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Tflops/Iteration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].metric" },
      { "jsonPath": "$.[*].value", "language": "jsonpath", "name": "", "type": "number" },
      { "jsonPath": "$.[*].timestamp", "language": "jsonpath", "name": "", "type": "time" }
     ],
     "method": "GET",
     "params": [
      [
       "start",
       "${__from}"
      ],
      [
       "end",
       "${__to}"
      ]
     ],
     "urlPath": "/v1/workloads/${workload_uid}/trainingPerformance"
    }
   ]
  },
  {
   "title": "Tokens Per GPU/Iteration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.[*].metric" },
      { "jsonPath": "$.[*].value", "language": "jsonpath", "name": "", "type": "number" },
      { "jsonPath": "$.[*].timestamp", "language": "jsonpath", "name": "", "type": "time" }
     ],
     "method": "GET",
     "params": [
      [
       "start",
       "${__from}"
      ],
      [
       "end",
       "${__to}"
      ]
     ],
     "urlPath": "/v1/workloads/${workload_uid}/trainingPerformance"
    }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Pod Cpu Usage(cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workload_container_cpu_usage_seconds_total{workload_uid=\"$workload_uid\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum by (pod) (\n    workload_container_memory_working_set_bytes{container!=\"\",pod!=\"\",workload_uid = \"$workload_uid\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Utilzation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "(\n  sum by (pod) (\n    workload_container_memory_working_set_bytes{container!=\"\",pod!=\"\",workload_uid = \"$workload_uid\"}\n  )\n)\n/\n(\n  sum by (pod) (\n    workload_kube_pod_container_resource_requests{resource=\"memory\",workload_uid = \"$workload_uid\"}\n  )\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Ephemeral Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum by (pod) (\n    workload_pod_ephemeral_storage_usage_bytes{workload_uid = \"$workload_uid\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Write Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod,container) (\n  rate(workload_container_fs_writes_bytes_total{container!=\"\",pod!=\"\",workload_uid=\"$workload_uid\"}[5m])\n)",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "Pod Read Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod,container) (\n  rate(workload_container_fs_reads_bytes_total{container!=\"\",pod!=\"\",workload_uid=\"$workload_uid\"}[5m])\n)",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "avg(workload_gpu_utilization{workload_uid=\"$workload_uid\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "GPU Memory Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "100 - ((avg(workload_gpu_free_vram{workload_uid=\"$workload_uid\"}) by (node))/(avg(workload_gpu_total_vram{workload_uid=\"$workload_uid\"}) by (node)) * 100)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(workload_gpu_package_power{workload_uid=\"$workload_uid\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(avg(workload_gpu_total_vram{workload_uid=\"$workload_uid\"}) by (node)) - (avg(workload_gpu_free_vram{workload_uid=\"$workload_uid\"}) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "RDMA Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_rdma_stat_tx_bytes{workload_uid=\"$workload_uid\"}[1m])) by (node)",
     "legendFormat": "{{node}}  TX"
    },
    {
     "expr": "sum(rate(workload_rdma_stat_rx_bytes{workload_uid=\"$workload_uid\"}[1m])) by (node)",
     "legendFormat": "{{node}}  RX"
    }
   ]
  },
  {
   "title": "RDMA Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum(rate(workload_rdma_stat_tx_pkts{workload_uid=\"$workload_uid\"}[1m])) by (node)",
     "legendFormat": "{{node}}  TX"
    },
    {
     "expr": "sum(rate(workload_rdma_stat_rx_pkts{workload_uid=\"$workload_uid\"}[1m])) by (node)",
     "legendFormat": "{{node}}  RX"
    }
   ]
  },
  {
   "title": "RDMA Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_discards{workload_uid=\"$workload_uid\"})) by (node)> 0",
     "legendFormat": "RX Roce Discards:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_discards{workload_uid=\"$workload_uid\"})) by (node)> 0",
     "legendFormat": "TX Roce Discards:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "TX Roce Errors:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "RX Roce Errors:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_seq_err_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "NAK(Seq err):{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rnr_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "NAK(RNR):{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "Missing Resp:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_to_retransmits{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "ReTransmit:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_max_retry_exceeded{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "MaxRetryExceeded:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "MissingResp:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_unrecoverable_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "UnrecoverableErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_qp_op_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "LocalQpOpErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_protection_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "LocalProtectionErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_access_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "RemoteAccessErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_invalid_req_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0",
     "legendFormat": "RemoteInvalidReqErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_op_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "RemoteOpErr:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_opcode_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Opcode Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rx Domain Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rx No Perm:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rx Range Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Tx Domain Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Tx No Perm:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Tx Range Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rem_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rem Inv Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_mem_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Mem Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Srq Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cmp_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Cmp Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_wqe_format_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Wqe Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Cq Load Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Srq Load Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Tx Pci Err:{{node}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (node)> 0 ",
     "legendFormat": "Res Rx Pci Err:{{node}}"
    }
   ]
  },
  {
   "title": "RDMA Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "increase(workload_rdma_stat_dup_req{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "DupReq:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_exceed_max{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResExceedMax:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_length_mismatch{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResLengthMismatch:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_exceeds_wqe{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResExceedsWqe:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_rx_invalid_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Rx Invalid Rkey:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_tx_invalid_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Tx Invalid Rkey:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_irrq_oflow{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Irrq Oflow:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_unsup_opcode{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Unsupported OpCode:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_unaligned_atomic{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Unaligned Atomic:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "MissingResp:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_invalid_dup_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Invalid Dup Rkey:{{node}}:{{device}}"
    }
   ]
  },
  {
   "title": "XGMI Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_gpu_xgmi_link_tx{workload_uid=\"$workload_uid\"}[1m])) by (node)",
     "legendFormat": "{{node}}  TX"
    },
    {
     "expr": "sum(rate(gpu_xgmi_link_rx{workload_uid=\"$workload_uid\"}[1m])) by (node)",
     "legendFormat": "{{node}}  RX"
    }
   ]
  },
  {
   "title": "PCIE Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_pcie_bandwidth{workload_uid=\"$workload_uid\"}[1m])) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "workload_gpu_utilization{workload_uid=\"$workload_uid\"}",
     "legendFormat": "{{node}}-GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Memory Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "100 - (workload_gpu_free_vram{workload_uid=\"$workload_uid\"}/workload_gpu_total_vram{workload_uid=\"$workload_uid\"} * 100)",
     "legendFormat": "{{node}}-GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "workload_gpu_package_power{workload_uid=\"$workload_uid\"}",
     "legendFormat": "{{node}}-GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "workload_gpu_total_vram{workload_uid=\"$workload_uid\"} - workload_gpu_free_vram{workload_uid=\"$workload_uid\"}",
     "legendFormat": "{{node}}-GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "RDMA Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_rdma_stat_tx_bytes{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,node)",
     "legendFormat": "{{node}} GPU {{gpu_id}} TX"
    },
    {
     "expr": "sum(rate(workload_rdma_stat_rx_bytes{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,node)",
     "legendFormat": "{{node}} GPU {{gpu_id}} RX"
    }
   ]
  },
  {
   "title": "RDMA Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "sum(rate(workload_rdma_stat_tx_pkts{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,node)",
     "legendFormat": "{{node}} GPU {{gpu_id}} TX"
    },
    {
     "expr": "sum(rate(workload_rdma_stat_rx_pkts{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,node)",
     "legendFormat": "{{node}} GPU {{gpu_id}} RX"
    }
   ]
  },
  {
   "title": "RDMA Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_discards{workload_uid=\"$workload_uid\"})) by (node,device)> 0",
     "legendFormat": "RX Roce Discards:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_discards{workload_uid=\"$workload_uid\"})) by (node,device)> 0",
     "legendFormat": "TX Roce Discards:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "TX Roce Errors:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "RX Roce Errors:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_seq_err_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "NAK(Seq err):{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rnr_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "NAK(RNR):{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "Missing Resp:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_to_retransmits{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "ReTransmit:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_max_retry_exceeded{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "MaxRetryExceeded:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "MissingResp:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_unrecoverable_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "UnrecoverableErr:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_qp_op_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "LocalQpOpErr:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_protection_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "LocalProtectionErr:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_access_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "RemoteAccessErr:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_invalid_req_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0",
     "legendFormat": "RemoteInvalidReqErr:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_op_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "RemoteOpErr:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_opcode_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Opcode Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Rx Domain Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Rx No Perm:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Rx Range Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Tx Domain Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Tx No Perm:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Tx Range Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rem_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Rem Inv Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_mem_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Mem Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Srq Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cmp_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Cmp Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_wqe_format_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Wqe Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Cq Load Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Srq Load Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Tx Pci Err:{{node}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (node,device)> 0 ",
     "legendFormat": "Res Rx Pci Err:{{node}}-{{device}}"
    }
   ]
  },
  {
   "title": "XGMI Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_gpu_xgmi_link_tx{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,node)",
     "legendFormat": "{{node}} GPU {{gpu_id}} TX"
    },
    {
     "expr": "sum(rate(gpu_xgmi_link_rx{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,node)",
     "legendFormat": "{{node}} GPU {{gpu_id}} RX"
    }
   ]
  },
  {
   "title": "PCIE Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_pcie_bandwidth{workload_uid=\"$workload_uid\"}[1m])) by (node,gpu_id)",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 147 },
   "targets": [
    {
     "expr": "increase(workload_rdma_stat_dup_req{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "DupReq:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_exceed_max{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResExceedMax:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_length_mismatch{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResLengthMismatch:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_exceeds_wqe{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResExceedsWqe:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_rx_invalid_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Rx Invalid Rkey:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_tx_invalid_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Tx Invalid Rkey:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_irrq_oflow{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Irrq Oflow:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_unsup_opcode{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Unsupported OpCode:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_unaligned_atomic{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Unaligned Atomic:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "MissingResp:{{node}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_invalid_dup_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Invalid Dup Rkey:{{node}}:{{device}}"
    }
   ]
  }
 ]
}