/*
Copyright The AMD Authors.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/amd/v1"
	typedamdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/clientset/versioned/typed/amd/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeWorkloads implements WorkloadInterface
type fakeWorkloads struct {
	*gentype.FakeClientWithListAndApply[*v1.Workload, *v1.WorkloadList, *amdv1.WorkloadApplyConfiguration]
	Fake *FakeAmdV1
}

func newFakeWorkloads(fake *FakeAmdV1, namespace string) typedamdv1.WorkloadInterface {
	return &fakeWorkloads{
		gentype.NewFakeClientWithListAndApply[*v1.Workload, *v1.WorkloadList, *amdv1.WorkloadApplyConfiguration](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("workloads"),
			v1.SchemeGroupVersion.WithKind("Workload"),
			func() *v1.Workload { return &v1.Workload{} },
			func() *v1.WorkloadList { return &v1.WorkloadList{} },
			func(dst, src *v1.WorkloadList) { dst.ListMeta = src.ListMeta },
			func(list *v1.WorkloadList) []*v1.Workload { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.WorkloadList, items []*v1.Workload) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
