/*
Copyright The AMD Authors.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/clientset/versioned/typed/amd/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAmdV1 struct {
	*testing.Fake
}

func (c *FakeAmdV1) AddonTemplates(namespace string) v1.AddonTemplateInterface {
	return newFakeAddonTemplates(c, namespace)
}

func (c *FakeAmdV1) Clusters(namespace string) v1.ClusterInterface {
	return newFakeClusters(c, namespace)
}

func (c *FakeAmdV1) Faults(namespace string) v1.FaultInterface {
	return newFakeFaults(c, namespace)
}

func (c *FakeAmdV1) Jobs(namespace string) v1.JobInterface {
	return newFakeJobs(c, namespace)
}

func (c *FakeAmdV1) Nodes(namespace string) v1.NodeInterface {
	return newFakeNodes(c, namespace)
}

func (c *FakeAmdV1) NodeFlavors(namespace string) v1.NodeFlavorInterface {
	return newFakeNodeFlavors(c, namespace)
}

func (c *FakeAmdV1) NodeTemplates(namespace string) v1.NodeTemplateInterface {
	return newFakeNodeTemplates(c, namespace)
}

func (c *FakeAmdV1) ResourceTemplates(namespace string) v1.ResourceTemplateInterface {
	return newFakeResourceTemplates(c, namespace)
}

func (c *FakeAmdV1) StorageClusters(namespace string) v1.StorageClusterInterface {
	return newFakeStorageClusters(c, namespace)
}

func (c *FakeAmdV1) Workloads(namespace string) v1.WorkloadInterface {
	return newFakeWorkloads(c, namespace)
}

func (c *FakeAmdV1) Workspaces(namespace string) v1.WorkspaceInterface {
	return newFakeWorkspaces(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAmdV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
