/*
Copyright The AMD Authors.

*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/amd/v1"
	typedamdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/clientset/versioned/typed/amd/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeWorkspaces implements WorkspaceInterface
type fakeWorkspaces struct {
	*gentype.FakeClientWithListAndApply[*v1.Workspace, *v1.WorkspaceList, *amdv1.WorkspaceApplyConfiguration]
	Fake *FakeAmdV1
}

func newFakeWorkspaces(fake *FakeAmdV1) typedamdv1.WorkspaceInterface {
	return &fakeWorkspaces{
		gentype.NewFakeClientWithListAndApply[*v1.Workspace, *v1.WorkspaceList, *amdv1.WorkspaceApplyConfiguration](
			fake.Fake,
			"",
			v1.SchemeGroupVersion.WithResource("workspaces"),
			v1.SchemeGroupVersion.WithKind("Workspace"),
			func() *v1.Workspace { return &v1.Workspace{} },
			func() *v1.WorkspaceList { return &v1.WorkspaceList{} },
			func(dst, src *v1.WorkspaceList) { dst.ListMeta = src.ListMeta },
			func(list *v1.WorkspaceList) []*v1.Workspace { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.WorkspaceList, items []*v1.Workspace) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
