// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newAlertStatistics(db *gorm.DB, opts ...gen.DOOption) alertStatistics {
	_alertStatistics := alertStatistics{}

	_alertStatistics.alertStatisticsDo.UseDB(db, opts...)
	_alertStatistics.alertStatisticsDo.UseModel(&model.AlertStatistics{})

	tableName := _alertStatistics.alertStatisticsDo.TableName()
	_alertStatistics.ALL = field.NewAsterisk(tableName)
	_alertStatistics.ID = field.NewInt64(tableName, "id")
	_alertStatistics.Date = field.NewTime(tableName, "date")
	_alertStatistics.Hour = field.NewInt32(tableName, "hour")
	_alertStatistics.AlertName = field.NewString(tableName, "alert_name")
	_alertStatistics.Source = field.NewString(tableName, "source")
	_alertStatistics.Severity = field.NewString(tableName, "severity")
	_alertStatistics.WorkloadID = field.NewString(tableName, "workload_id")
	_alertStatistics.ClusterName = field.NewString(tableName, "cluster_name")
	_alertStatistics.FiringCount = field.NewInt32(tableName, "firing_count")
	_alertStatistics.ResolvedCount = field.NewInt32(tableName, "resolved_count")
	_alertStatistics.TotalDurationSeconds = field.NewInt64(tableName, "total_duration_seconds")
	_alertStatistics.AvgDurationSeconds = field.NewFloat64(tableName, "avg_duration_seconds")
	_alertStatistics.CreatedAt = field.NewTime(tableName, "created_at")

	_alertStatistics.fillFieldMap()

	return _alertStatistics
}

type alertStatistics struct {
	alertStatisticsDo alertStatisticsDo

	ALL                  field.Asterisk
	ID                   field.Int64
	Date                 field.Time
	Hour                 field.Int32 // Hour of day (0-23), NULL for daily aggregates
	AlertName            field.String
	Source               field.String
	Severity             field.String
	WorkloadID           field.String
	ClusterName          field.String
	FiringCount          field.Int32
	ResolvedCount        field.Int32
	TotalDurationSeconds field.Int64
	AvgDurationSeconds   field.Float64
	CreatedAt            field.Time

	fieldMap map[string]field.Expr
}

func (a alertStatistics) Table(newTableName string) *alertStatistics {
	a.alertStatisticsDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a alertStatistics) As(alias string) *alertStatistics {
	a.alertStatisticsDo.DO = *(a.alertStatisticsDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *alertStatistics) updateTableName(table string) *alertStatistics {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Date = field.NewTime(table, "date")
	a.Hour = field.NewInt32(table, "hour")
	a.AlertName = field.NewString(table, "alert_name")
	a.Source = field.NewString(table, "source")
	a.Severity = field.NewString(table, "severity")
	a.WorkloadID = field.NewString(table, "workload_id")
	a.ClusterName = field.NewString(table, "cluster_name")
	a.FiringCount = field.NewInt32(table, "firing_count")
	a.ResolvedCount = field.NewInt32(table, "resolved_count")
	a.TotalDurationSeconds = field.NewInt64(table, "total_duration_seconds")
	a.AvgDurationSeconds = field.NewFloat64(table, "avg_duration_seconds")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *alertStatistics) WithContext(ctx context.Context) *alertStatisticsDo {
	return a.alertStatisticsDo.WithContext(ctx)
}

func (a alertStatistics) TableName() string { return a.alertStatisticsDo.TableName() }

func (a alertStatistics) Alias() string { return a.alertStatisticsDo.Alias() }

func (a alertStatistics) Columns(cols ...field.Expr) gen.Columns {
	return a.alertStatisticsDo.Columns(cols...)
}

func (a *alertStatistics) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *alertStatistics) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 13)
	a.fieldMap["id"] = a.ID
	a.fieldMap["date"] = a.Date
	a.fieldMap["hour"] = a.Hour
	a.fieldMap["alert_name"] = a.AlertName
	a.fieldMap["source"] = a.Source
	a.fieldMap["severity"] = a.Severity
	a.fieldMap["workload_id"] = a.WorkloadID
	a.fieldMap["cluster_name"] = a.ClusterName
	a.fieldMap["firing_count"] = a.FiringCount
	a.fieldMap["resolved_count"] = a.ResolvedCount
	a.fieldMap["total_duration_seconds"] = a.TotalDurationSeconds
	a.fieldMap["avg_duration_seconds"] = a.AvgDurationSeconds
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a alertStatistics) clone(db *gorm.DB) alertStatistics {
	a.alertStatisticsDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a alertStatistics) replaceDB(db *gorm.DB) alertStatistics {
	a.alertStatisticsDo.ReplaceDB(db)
	return a
}

type alertStatisticsDo struct{ gen.DO }

func (a alertStatisticsDo) Debug() *alertStatisticsDo {
	return a.withDO(a.DO.Debug())
}

func (a alertStatisticsDo) WithContext(ctx context.Context) *alertStatisticsDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a alertStatisticsDo) ReadDB() *alertStatisticsDo {
	return a.Clauses(dbresolver.Read)
}

func (a alertStatisticsDo) WriteDB() *alertStatisticsDo {
	return a.Clauses(dbresolver.Write)
}

func (a alertStatisticsDo) Session(config *gorm.Session) *alertStatisticsDo {
	return a.withDO(a.DO.Session(config))
}

func (a alertStatisticsDo) Clauses(conds ...clause.Expression) *alertStatisticsDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a alertStatisticsDo) Returning(value interface{}, columns ...string) *alertStatisticsDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a alertStatisticsDo) Not(conds ...gen.Condition) *alertStatisticsDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a alertStatisticsDo) Or(conds ...gen.Condition) *alertStatisticsDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a alertStatisticsDo) Select(conds ...field.Expr) *alertStatisticsDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a alertStatisticsDo) Where(conds ...gen.Condition) *alertStatisticsDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a alertStatisticsDo) Order(conds ...field.Expr) *alertStatisticsDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a alertStatisticsDo) Distinct(cols ...field.Expr) *alertStatisticsDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a alertStatisticsDo) Omit(cols ...field.Expr) *alertStatisticsDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a alertStatisticsDo) Join(table schema.Tabler, on ...field.Expr) *alertStatisticsDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a alertStatisticsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *alertStatisticsDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a alertStatisticsDo) RightJoin(table schema.Tabler, on ...field.Expr) *alertStatisticsDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a alertStatisticsDo) Group(cols ...field.Expr) *alertStatisticsDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a alertStatisticsDo) Having(conds ...gen.Condition) *alertStatisticsDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a alertStatisticsDo) Limit(limit int) *alertStatisticsDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a alertStatisticsDo) Offset(offset int) *alertStatisticsDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a alertStatisticsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *alertStatisticsDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a alertStatisticsDo) Unscoped() *alertStatisticsDo {
	return a.withDO(a.DO.Unscoped())
}

func (a alertStatisticsDo) Create(values ...*model.AlertStatistics) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a alertStatisticsDo) CreateInBatches(values []*model.AlertStatistics, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a alertStatisticsDo) Save(values ...*model.AlertStatistics) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a alertStatisticsDo) First() (*model.AlertStatistics, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertStatistics), nil
	}
}

func (a alertStatisticsDo) Take() (*model.AlertStatistics, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertStatistics), nil
	}
}

func (a alertStatisticsDo) Last() (*model.AlertStatistics, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertStatistics), nil
	}
}

func (a alertStatisticsDo) Find() ([]*model.AlertStatistics, error) {
	result, err := a.DO.Find()
	return result.([]*model.AlertStatistics), err
}

func (a alertStatisticsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AlertStatistics, err error) {
	buf := make([]*model.AlertStatistics, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a alertStatisticsDo) FindInBatches(result *[]*model.AlertStatistics, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a alertStatisticsDo) Attrs(attrs ...field.AssignExpr) *alertStatisticsDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a alertStatisticsDo) Assign(attrs ...field.AssignExpr) *alertStatisticsDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a alertStatisticsDo) Joins(fields ...field.RelationField) *alertStatisticsDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a alertStatisticsDo) Preload(fields ...field.RelationField) *alertStatisticsDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a alertStatisticsDo) FirstOrInit() (*model.AlertStatistics, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertStatistics), nil
	}
}

func (a alertStatisticsDo) FirstOrCreate() (*model.AlertStatistics, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AlertStatistics), nil
	}
}

func (a alertStatisticsDo) FindByPage(offset int, limit int) (result []*model.AlertStatistics, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a alertStatisticsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a alertStatisticsDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a alertStatisticsDo) Delete(models ...*model.AlertStatistics) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *alertStatisticsDo) withDO(do gen.Dao) *alertStatisticsDo {
	a.DO = *do.(*gen.DO)
	return a
}
