// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newCommitImpactAnalysis(db *gorm.DB, opts ...gen.DOOption) commitImpactAnalysis {
	_commitImpactAnalysis := commitImpactAnalysis{}

	_commitImpactAnalysis.commitImpactAnalysisDo.UseDB(db, opts...)
	_commitImpactAnalysis.commitImpactAnalysisDo.UseModel(&model.CommitImpactAnalysis{})

	tableName := _commitImpactAnalysis.commitImpactAnalysisDo.TableName()
	_commitImpactAnalysis.ALL = field.NewAsterisk(tableName)
	_commitImpactAnalysis.ID = field.NewInt64(tableName, "id")
	_commitImpactAnalysis.ConfigID = field.NewInt64(tableName, "config_id")
	_commitImpactAnalysis.RunID = field.NewInt64(tableName, "run_id")
	_commitImpactAnalysis.CommitSha = field.NewString(tableName, "commit_sha")
	_commitImpactAnalysis.ImpactScore = field.NewFloat64(tableName, "impact_score")
	_commitImpactAnalysis.RiskLevel = field.NewString(tableName, "risk_level")
	_commitImpactAnalysis.ImpactCategories = field.NewField(tableName, "impact_categories")
	_commitImpactAnalysis.AffectedMetrics = field.NewField(tableName, "affected_metrics")
	_commitImpactAnalysis.Explanation = field.NewString(tableName, "explanation")
	_commitImpactAnalysis.Recommendations = field.NewField(tableName, "recommendations")
	_commitImpactAnalysis.IsAiGenerated = field.NewBool(tableName, "is_ai_generated")
	_commitImpactAnalysis.Confidence = field.NewFloat64(tableName, "confidence")
	_commitImpactAnalysis.AnalyzedAt = field.NewTime(tableName, "analyzed_at")
	_commitImpactAnalysis.CreatedAt = field.NewTime(tableName, "created_at")

	_commitImpactAnalysis.fillFieldMap()

	return _commitImpactAnalysis
}

type commitImpactAnalysis struct {
	commitImpactAnalysisDo commitImpactAnalysisDo

	ALL              field.Asterisk
	ID               field.Int64
	ConfigID         field.Int64
	RunID            field.Int64
	CommitSha        field.String
	ImpactScore      field.Float64
	RiskLevel        field.String
	ImpactCategories field.Field
	AffectedMetrics  field.Field
	Explanation      field.String
	Recommendations  field.Field
	IsAiGenerated    field.Bool
	Confidence       field.Float64
	AnalyzedAt       field.Time
	CreatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (c commitImpactAnalysis) Table(newTableName string) *commitImpactAnalysis {
	c.commitImpactAnalysisDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c commitImpactAnalysis) As(alias string) *commitImpactAnalysis {
	c.commitImpactAnalysisDo.DO = *(c.commitImpactAnalysisDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *commitImpactAnalysis) updateTableName(table string) *commitImpactAnalysis {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewInt64(table, "id")
	c.ConfigID = field.NewInt64(table, "config_id")
	c.RunID = field.NewInt64(table, "run_id")
	c.CommitSha = field.NewString(table, "commit_sha")
	c.ImpactScore = field.NewFloat64(table, "impact_score")
	c.RiskLevel = field.NewString(table, "risk_level")
	c.ImpactCategories = field.NewField(table, "impact_categories")
	c.AffectedMetrics = field.NewField(table, "affected_metrics")
	c.Explanation = field.NewString(table, "explanation")
	c.Recommendations = field.NewField(table, "recommendations")
	c.IsAiGenerated = field.NewBool(table, "is_ai_generated")
	c.Confidence = field.NewFloat64(table, "confidence")
	c.AnalyzedAt = field.NewTime(table, "analyzed_at")
	c.CreatedAt = field.NewTime(table, "created_at")

	c.fillFieldMap()

	return c
}

func (c *commitImpactAnalysis) WithContext(ctx context.Context) *commitImpactAnalysisDo {
	return c.commitImpactAnalysisDo.WithContext(ctx)
}

func (c commitImpactAnalysis) TableName() string { return c.commitImpactAnalysisDo.TableName() }

func (c commitImpactAnalysis) Alias() string { return c.commitImpactAnalysisDo.Alias() }

func (c commitImpactAnalysis) Columns(cols ...field.Expr) gen.Columns {
	return c.commitImpactAnalysisDo.Columns(cols...)
}

func (c *commitImpactAnalysis) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *commitImpactAnalysis) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 14)
	c.fieldMap["id"] = c.ID
	c.fieldMap["config_id"] = c.ConfigID
	c.fieldMap["run_id"] = c.RunID
	c.fieldMap["commit_sha"] = c.CommitSha
	c.fieldMap["impact_score"] = c.ImpactScore
	c.fieldMap["risk_level"] = c.RiskLevel
	c.fieldMap["impact_categories"] = c.ImpactCategories
	c.fieldMap["affected_metrics"] = c.AffectedMetrics
	c.fieldMap["explanation"] = c.Explanation
	c.fieldMap["recommendations"] = c.Recommendations
	c.fieldMap["is_ai_generated"] = c.IsAiGenerated
	c.fieldMap["confidence"] = c.Confidence
	c.fieldMap["analyzed_at"] = c.AnalyzedAt
	c.fieldMap["created_at"] = c.CreatedAt
}

func (c commitImpactAnalysis) clone(db *gorm.DB) commitImpactAnalysis {
	c.commitImpactAnalysisDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c commitImpactAnalysis) replaceDB(db *gorm.DB) commitImpactAnalysis {
	c.commitImpactAnalysisDo.ReplaceDB(db)
	return c
}

type commitImpactAnalysisDo struct{ gen.DO }

func (c commitImpactAnalysisDo) Debug() *commitImpactAnalysisDo {
	return c.withDO(c.DO.Debug())
}

func (c commitImpactAnalysisDo) WithContext(ctx context.Context) *commitImpactAnalysisDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c commitImpactAnalysisDo) ReadDB() *commitImpactAnalysisDo {
	return c.Clauses(dbresolver.Read)
}

func (c commitImpactAnalysisDo) WriteDB() *commitImpactAnalysisDo {
	return c.Clauses(dbresolver.Write)
}

func (c commitImpactAnalysisDo) Session(config *gorm.Session) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Session(config))
}

func (c commitImpactAnalysisDo) Clauses(conds ...clause.Expression) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c commitImpactAnalysisDo) Returning(value interface{}, columns ...string) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c commitImpactAnalysisDo) Not(conds ...gen.Condition) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c commitImpactAnalysisDo) Or(conds ...gen.Condition) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c commitImpactAnalysisDo) Select(conds ...field.Expr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c commitImpactAnalysisDo) Where(conds ...gen.Condition) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c commitImpactAnalysisDo) Order(conds ...field.Expr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c commitImpactAnalysisDo) Distinct(cols ...field.Expr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c commitImpactAnalysisDo) Omit(cols ...field.Expr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c commitImpactAnalysisDo) Join(table schema.Tabler, on ...field.Expr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c commitImpactAnalysisDo) LeftJoin(table schema.Tabler, on ...field.Expr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c commitImpactAnalysisDo) RightJoin(table schema.Tabler, on ...field.Expr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c commitImpactAnalysisDo) Group(cols ...field.Expr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c commitImpactAnalysisDo) Having(conds ...gen.Condition) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c commitImpactAnalysisDo) Limit(limit int) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c commitImpactAnalysisDo) Offset(offset int) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c commitImpactAnalysisDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c commitImpactAnalysisDo) Unscoped() *commitImpactAnalysisDo {
	return c.withDO(c.DO.Unscoped())
}

func (c commitImpactAnalysisDo) Create(values ...*model.CommitImpactAnalysis) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c commitImpactAnalysisDo) CreateInBatches(values []*model.CommitImpactAnalysis, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c commitImpactAnalysisDo) Save(values ...*model.CommitImpactAnalysis) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c commitImpactAnalysisDo) First() (*model.CommitImpactAnalysis, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitImpactAnalysis), nil
	}
}

func (c commitImpactAnalysisDo) Take() (*model.CommitImpactAnalysis, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitImpactAnalysis), nil
	}
}

func (c commitImpactAnalysisDo) Last() (*model.CommitImpactAnalysis, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitImpactAnalysis), nil
	}
}

func (c commitImpactAnalysisDo) Find() ([]*model.CommitImpactAnalysis, error) {
	result, err := c.DO.Find()
	return result.([]*model.CommitImpactAnalysis), err
}

func (c commitImpactAnalysisDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CommitImpactAnalysis, err error) {
	buf := make([]*model.CommitImpactAnalysis, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c commitImpactAnalysisDo) FindInBatches(result *[]*model.CommitImpactAnalysis, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c commitImpactAnalysisDo) Attrs(attrs ...field.AssignExpr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c commitImpactAnalysisDo) Assign(attrs ...field.AssignExpr) *commitImpactAnalysisDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c commitImpactAnalysisDo) Joins(fields ...field.RelationField) *commitImpactAnalysisDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c commitImpactAnalysisDo) Preload(fields ...field.RelationField) *commitImpactAnalysisDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c commitImpactAnalysisDo) FirstOrInit() (*model.CommitImpactAnalysis, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitImpactAnalysis), nil
	}
}

func (c commitImpactAnalysisDo) FirstOrCreate() (*model.CommitImpactAnalysis, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CommitImpactAnalysis), nil
	}
}

func (c commitImpactAnalysisDo) FindByPage(offset int, limit int) (result []*model.CommitImpactAnalysis, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c commitImpactAnalysisDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c commitImpactAnalysisDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c commitImpactAnalysisDo) Delete(models ...*model.CommitImpactAnalysis) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *commitImpactAnalysisDo) withDO(do gen.Dao) *commitImpactAnalysisDo {
	c.DO = *do.(*gen.DO)
	return c
}
