// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newComponentGroups(db *gorm.DB, opts ...gen.DOOption) componentGroups {
	_componentGroups := componentGroups{}

	_componentGroups.componentGroupsDo.UseDB(db, opts...)
	_componentGroups.componentGroupsDo.UseModel(&model.ComponentGroups{})

	tableName := _componentGroups.componentGroupsDo.TableName()
	_componentGroups.ALL = field.NewAsterisk(tableName)
	_componentGroups.ID = field.NewString(tableName, "id")
	_componentGroups.ClusterName = field.NewString(tableName, "cluster_name")
	_componentGroups.Namespace = field.NewString(tableName, "namespace")
	_componentGroups.GroupName = field.NewString(tableName, "group_name")
	_componentGroups.GroupDisplayName = field.NewString(tableName, "group_display_name")
	_componentGroups.AggregationMethod = field.NewString(tableName, "aggregation_method")
	_componentGroups.AggregationRule = field.NewString(tableName, "aggregation_rule")
	_componentGroups.AggregationKey = field.NewString(tableName, "aggregation_key")
	_componentGroups.AggregationConfidence = field.NewFloat64(tableName, "aggregation_confidence")
	_componentGroups.AiReasoning = field.NewString(tableName, "ai_reasoning")
	_componentGroups.MemberCount = field.NewInt32(tableName, "member_count")
	_componentGroups.PrimaryComponentID = field.NewString(tableName, "primary_component_id")
	_componentGroups.ComponentCategory = field.NewString(tableName, "component_category")
	_componentGroups.ComponentType = field.NewString(tableName, "component_type")
	_componentGroups.UserOverride = field.NewBool(tableName, "user_override")
	_componentGroups.UserOverrideAt = field.NewTime(tableName, "user_override_at")
	_componentGroups.UserOverrideBy = field.NewString(tableName, "user_override_by")
	_componentGroups.Status = field.NewString(tableName, "status")
	_componentGroups.CreatedAt = field.NewTime(tableName, "created_at")
	_componentGroups.UpdatedAt = field.NewTime(tableName, "updated_at")
	_componentGroups.CreatedByScan = field.NewString(tableName, "created_by_scan")
	_componentGroups.LastUpdatedByScan = field.NewString(tableName, "last_updated_by_scan")

	_componentGroups.fillFieldMap()

	return _componentGroups
}

type componentGroups struct {
	componentGroupsDo componentGroupsDo

	ALL                   field.Asterisk
	ID                    field.String
	ClusterName           field.String
	Namespace             field.String
	GroupName             field.String
	GroupDisplayName      field.String
	AggregationMethod     field.String
	AggregationRule       field.String
	AggregationKey        field.String
	AggregationConfidence field.Float64
	AiReasoning           field.String
	MemberCount           field.Int32
	PrimaryComponentID    field.String
	ComponentCategory     field.String
	ComponentType         field.String
	UserOverride          field.Bool
	UserOverrideAt        field.Time
	UserOverrideBy        field.String
	Status                field.String
	CreatedAt             field.Time
	UpdatedAt             field.Time
	CreatedByScan         field.String
	LastUpdatedByScan     field.String

	fieldMap map[string]field.Expr
}

func (c componentGroups) Table(newTableName string) *componentGroups {
	c.componentGroupsDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c componentGroups) As(alias string) *componentGroups {
	c.componentGroupsDo.DO = *(c.componentGroupsDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *componentGroups) updateTableName(table string) *componentGroups {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.ClusterName = field.NewString(table, "cluster_name")
	c.Namespace = field.NewString(table, "namespace")
	c.GroupName = field.NewString(table, "group_name")
	c.GroupDisplayName = field.NewString(table, "group_display_name")
	c.AggregationMethod = field.NewString(table, "aggregation_method")
	c.AggregationRule = field.NewString(table, "aggregation_rule")
	c.AggregationKey = field.NewString(table, "aggregation_key")
	c.AggregationConfidence = field.NewFloat64(table, "aggregation_confidence")
	c.AiReasoning = field.NewString(table, "ai_reasoning")
	c.MemberCount = field.NewInt32(table, "member_count")
	c.PrimaryComponentID = field.NewString(table, "primary_component_id")
	c.ComponentCategory = field.NewString(table, "component_category")
	c.ComponentType = field.NewString(table, "component_type")
	c.UserOverride = field.NewBool(table, "user_override")
	c.UserOverrideAt = field.NewTime(table, "user_override_at")
	c.UserOverrideBy = field.NewString(table, "user_override_by")
	c.Status = field.NewString(table, "status")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")
	c.CreatedByScan = field.NewString(table, "created_by_scan")
	c.LastUpdatedByScan = field.NewString(table, "last_updated_by_scan")

	c.fillFieldMap()

	return c
}

func (c *componentGroups) WithContext(ctx context.Context) *componentGroupsDo {
	return c.componentGroupsDo.WithContext(ctx)
}

func (c componentGroups) TableName() string { return c.componentGroupsDo.TableName() }

func (c componentGroups) Alias() string { return c.componentGroupsDo.Alias() }

func (c componentGroups) Columns(cols ...field.Expr) gen.Columns {
	return c.componentGroupsDo.Columns(cols...)
}

func (c *componentGroups) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *componentGroups) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 22)
	c.fieldMap["id"] = c.ID
	c.fieldMap["cluster_name"] = c.ClusterName
	c.fieldMap["namespace"] = c.Namespace
	c.fieldMap["group_name"] = c.GroupName
	c.fieldMap["group_display_name"] = c.GroupDisplayName
	c.fieldMap["aggregation_method"] = c.AggregationMethod
	c.fieldMap["aggregation_rule"] = c.AggregationRule
	c.fieldMap["aggregation_key"] = c.AggregationKey
	c.fieldMap["aggregation_confidence"] = c.AggregationConfidence
	c.fieldMap["ai_reasoning"] = c.AiReasoning
	c.fieldMap["member_count"] = c.MemberCount
	c.fieldMap["primary_component_id"] = c.PrimaryComponentID
	c.fieldMap["component_category"] = c.ComponentCategory
	c.fieldMap["component_type"] = c.ComponentType
	c.fieldMap["user_override"] = c.UserOverride
	c.fieldMap["user_override_at"] = c.UserOverrideAt
	c.fieldMap["user_override_by"] = c.UserOverrideBy
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
	c.fieldMap["created_by_scan"] = c.CreatedByScan
	c.fieldMap["last_updated_by_scan"] = c.LastUpdatedByScan
}

func (c componentGroups) clone(db *gorm.DB) componentGroups {
	c.componentGroupsDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c componentGroups) replaceDB(db *gorm.DB) componentGroups {
	c.componentGroupsDo.ReplaceDB(db)
	return c
}

type componentGroupsDo struct{ gen.DO }

func (c componentGroupsDo) Debug() *componentGroupsDo {
	return c.withDO(c.DO.Debug())
}

func (c componentGroupsDo) WithContext(ctx context.Context) *componentGroupsDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c componentGroupsDo) ReadDB() *componentGroupsDo {
	return c.Clauses(dbresolver.Read)
}

func (c componentGroupsDo) WriteDB() *componentGroupsDo {
	return c.Clauses(dbresolver.Write)
}

func (c componentGroupsDo) Session(config *gorm.Session) *componentGroupsDo {
	return c.withDO(c.DO.Session(config))
}

func (c componentGroupsDo) Clauses(conds ...clause.Expression) *componentGroupsDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c componentGroupsDo) Returning(value interface{}, columns ...string) *componentGroupsDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c componentGroupsDo) Not(conds ...gen.Condition) *componentGroupsDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c componentGroupsDo) Or(conds ...gen.Condition) *componentGroupsDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c componentGroupsDo) Select(conds ...field.Expr) *componentGroupsDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c componentGroupsDo) Where(conds ...gen.Condition) *componentGroupsDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c componentGroupsDo) Order(conds ...field.Expr) *componentGroupsDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c componentGroupsDo) Distinct(cols ...field.Expr) *componentGroupsDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c componentGroupsDo) Omit(cols ...field.Expr) *componentGroupsDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c componentGroupsDo) Join(table schema.Tabler, on ...field.Expr) *componentGroupsDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c componentGroupsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *componentGroupsDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c componentGroupsDo) RightJoin(table schema.Tabler, on ...field.Expr) *componentGroupsDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c componentGroupsDo) Group(cols ...field.Expr) *componentGroupsDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c componentGroupsDo) Having(conds ...gen.Condition) *componentGroupsDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c componentGroupsDo) Limit(limit int) *componentGroupsDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c componentGroupsDo) Offset(offset int) *componentGroupsDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c componentGroupsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *componentGroupsDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c componentGroupsDo) Unscoped() *componentGroupsDo {
	return c.withDO(c.DO.Unscoped())
}

func (c componentGroupsDo) Create(values ...*model.ComponentGroups) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c componentGroupsDo) CreateInBatches(values []*model.ComponentGroups, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c componentGroupsDo) Save(values ...*model.ComponentGroups) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c componentGroupsDo) First() (*model.ComponentGroups, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentGroups), nil
	}
}

func (c componentGroupsDo) Take() (*model.ComponentGroups, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentGroups), nil
	}
}

func (c componentGroupsDo) Last() (*model.ComponentGroups, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentGroups), nil
	}
}

func (c componentGroupsDo) Find() ([]*model.ComponentGroups, error) {
	result, err := c.DO.Find()
	return result.([]*model.ComponentGroups), err
}

func (c componentGroupsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ComponentGroups, err error) {
	buf := make([]*model.ComponentGroups, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c componentGroupsDo) FindInBatches(result *[]*model.ComponentGroups, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c componentGroupsDo) Attrs(attrs ...field.AssignExpr) *componentGroupsDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c componentGroupsDo) Assign(attrs ...field.AssignExpr) *componentGroupsDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c componentGroupsDo) Joins(fields ...field.RelationField) *componentGroupsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c componentGroupsDo) Preload(fields ...field.RelationField) *componentGroupsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c componentGroupsDo) FirstOrInit() (*model.ComponentGroups, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentGroups), nil
	}
}

func (c componentGroupsDo) FirstOrCreate() (*model.ComponentGroups, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentGroups), nil
	}
}

func (c componentGroupsDo) FindByPage(offset int, limit int) (result []*model.ComponentGroups, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c componentGroupsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c componentGroupsDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c componentGroupsDo) Delete(models ...*model.ComponentGroups) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *componentGroupsDo) withDO(do gen.Dao) *componentGroupsDo {
	c.DO = *do.(*gen.DO)
	return c
}
