// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newComponentRegistry(db *gorm.DB, opts ...gen.DOOption) componentRegistry {
	_componentRegistry := componentRegistry{}

	_componentRegistry.componentRegistryDo.UseDB(db, opts...)
	_componentRegistry.componentRegistryDo.UseModel(&model.ComponentRegistry{})

	tableName := _componentRegistry.componentRegistryDo.TableName()
	_componentRegistry.ALL = field.NewAsterisk(tableName)
	_componentRegistry.ID = field.NewString(tableName, "id")
	_componentRegistry.ClusterName = field.NewString(tableName, "cluster_name")
	_componentRegistry.Namespace = field.NewString(tableName, "namespace")
	_componentRegistry.ComponentName = field.NewString(tableName, "component_name")
	_componentRegistry.ComponentCategory = field.NewString(tableName, "component_category")
	_componentRegistry.ComponentType = field.NewString(tableName, "component_type")
	_componentRegistry.ComponentTypeDisplay = field.NewString(tableName, "component_type_display")
	_componentRegistry.IdentifiedBy = field.NewString(tableName, "identified_by")
	_componentRegistry.IdentificationConfidence = field.NewFloat64(tableName, "identification_confidence")
	_componentRegistry.IdentificationEvidence = field.NewField(tableName, "identification_evidence")
	_componentRegistry.AggregationMethod = field.NewString(tableName, "aggregation_method")
	_componentRegistry.AggregationKey = field.NewString(tableName, "aggregation_key")
	_componentRegistry.GroupID = field.NewString(tableName, "group_id")
	_componentRegistry.IsPrimary = field.NewBool(tableName, "is_primary")
	_componentRegistry.MemberCount = field.NewInt32(tableName, "member_count")
	_componentRegistry.Metadata = field.NewField(tableName, "metadata")
	_componentRegistry.AlertCoverageScore = field.NewFloat64(tableName, "alert_coverage_score")
	_componentRegistry.ExistingRuleCount = field.NewInt32(tableName, "existing_rule_count")
	_componentRegistry.ExpectedCategories = field.NewString(tableName, "expected_categories")
	_componentRegistry.MissingCategories = field.NewString(tableName, "missing_categories")
	_componentRegistry.UserOverride = field.NewBool(tableName, "user_override")
	_componentRegistry.UserOverrideAt = field.NewTime(tableName, "user_override_at")
	_componentRegistry.UserOverrideBy = field.NewString(tableName, "user_override_by")
	_componentRegistry.LastSeenAt = field.NewTime(tableName, "last_seen_at")
	_componentRegistry.ScanID = field.NewString(tableName, "scan_id")
	_componentRegistry.Status = field.NewString(tableName, "status")
	_componentRegistry.CreatedAt = field.NewTime(tableName, "created_at")
	_componentRegistry.UpdatedAt = field.NewTime(tableName, "updated_at")

	_componentRegistry.fillFieldMap()

	return _componentRegistry
}

type componentRegistry struct {
	componentRegistryDo componentRegistryDo

	ALL                      field.Asterisk
	ID                       field.String
	ClusterName              field.String
	Namespace                field.String
	ComponentName            field.String
	ComponentCategory        field.String
	ComponentType            field.String
	ComponentTypeDisplay     field.String
	IdentifiedBy             field.String
	IdentificationConfidence field.Float64
	IdentificationEvidence   field.Field
	AggregationMethod        field.String
	AggregationKey           field.String
	GroupID                  field.String
	IsPrimary                field.Bool
	MemberCount              field.Int32
	Metadata                 field.Field
	AlertCoverageScore       field.Float64
	ExistingRuleCount        field.Int32
	ExpectedCategories       field.String
	MissingCategories        field.String
	UserOverride             field.Bool
	UserOverrideAt           field.Time
	UserOverrideBy           field.String
	LastSeenAt               field.Time
	ScanID                   field.String
	Status                   field.String
	CreatedAt                field.Time
	UpdatedAt                field.Time

	fieldMap map[string]field.Expr
}

func (c componentRegistry) Table(newTableName string) *componentRegistry {
	c.componentRegistryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c componentRegistry) As(alias string) *componentRegistry {
	c.componentRegistryDo.DO = *(c.componentRegistryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *componentRegistry) updateTableName(table string) *componentRegistry {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewString(table, "id")
	c.ClusterName = field.NewString(table, "cluster_name")
	c.Namespace = field.NewString(table, "namespace")
	c.ComponentName = field.NewString(table, "component_name")
	c.ComponentCategory = field.NewString(table, "component_category")
	c.ComponentType = field.NewString(table, "component_type")
	c.ComponentTypeDisplay = field.NewString(table, "component_type_display")
	c.IdentifiedBy = field.NewString(table, "identified_by")
	c.IdentificationConfidence = field.NewFloat64(table, "identification_confidence")
	c.IdentificationEvidence = field.NewField(table, "identification_evidence")
	c.AggregationMethod = field.NewString(table, "aggregation_method")
	c.AggregationKey = field.NewString(table, "aggregation_key")
	c.GroupID = field.NewString(table, "group_id")
	c.IsPrimary = field.NewBool(table, "is_primary")
	c.MemberCount = field.NewInt32(table, "member_count")
	c.Metadata = field.NewField(table, "metadata")
	c.AlertCoverageScore = field.NewFloat64(table, "alert_coverage_score")
	c.ExistingRuleCount = field.NewInt32(table, "existing_rule_count")
	c.ExpectedCategories = field.NewString(table, "expected_categories")
	c.MissingCategories = field.NewString(table, "missing_categories")
	c.UserOverride = field.NewBool(table, "user_override")
	c.UserOverrideAt = field.NewTime(table, "user_override_at")
	c.UserOverrideBy = field.NewString(table, "user_override_by")
	c.LastSeenAt = field.NewTime(table, "last_seen_at")
	c.ScanID = field.NewString(table, "scan_id")
	c.Status = field.NewString(table, "status")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *componentRegistry) WithContext(ctx context.Context) *componentRegistryDo {
	return c.componentRegistryDo.WithContext(ctx)
}

func (c componentRegistry) TableName() string { return c.componentRegistryDo.TableName() }

func (c componentRegistry) Alias() string { return c.componentRegistryDo.Alias() }

func (c componentRegistry) Columns(cols ...field.Expr) gen.Columns {
	return c.componentRegistryDo.Columns(cols...)
}

func (c *componentRegistry) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *componentRegistry) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 28)
	c.fieldMap["id"] = c.ID
	c.fieldMap["cluster_name"] = c.ClusterName
	c.fieldMap["namespace"] = c.Namespace
	c.fieldMap["component_name"] = c.ComponentName
	c.fieldMap["component_category"] = c.ComponentCategory
	c.fieldMap["component_type"] = c.ComponentType
	c.fieldMap["component_type_display"] = c.ComponentTypeDisplay
	c.fieldMap["identified_by"] = c.IdentifiedBy
	c.fieldMap["identification_confidence"] = c.IdentificationConfidence
	c.fieldMap["identification_evidence"] = c.IdentificationEvidence
	c.fieldMap["aggregation_method"] = c.AggregationMethod
	c.fieldMap["aggregation_key"] = c.AggregationKey
	c.fieldMap["group_id"] = c.GroupID
	c.fieldMap["is_primary"] = c.IsPrimary
	c.fieldMap["member_count"] = c.MemberCount
	c.fieldMap["metadata"] = c.Metadata
	c.fieldMap["alert_coverage_score"] = c.AlertCoverageScore
	c.fieldMap["existing_rule_count"] = c.ExistingRuleCount
	c.fieldMap["expected_categories"] = c.ExpectedCategories
	c.fieldMap["missing_categories"] = c.MissingCategories
	c.fieldMap["user_override"] = c.UserOverride
	c.fieldMap["user_override_at"] = c.UserOverrideAt
	c.fieldMap["user_override_by"] = c.UserOverrideBy
	c.fieldMap["last_seen_at"] = c.LastSeenAt
	c.fieldMap["scan_id"] = c.ScanID
	c.fieldMap["status"] = c.Status
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c componentRegistry) clone(db *gorm.DB) componentRegistry {
	c.componentRegistryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c componentRegistry) replaceDB(db *gorm.DB) componentRegistry {
	c.componentRegistryDo.ReplaceDB(db)
	return c
}

type componentRegistryDo struct{ gen.DO }

func (c componentRegistryDo) Debug() *componentRegistryDo {
	return c.withDO(c.DO.Debug())
}

func (c componentRegistryDo) WithContext(ctx context.Context) *componentRegistryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c componentRegistryDo) ReadDB() *componentRegistryDo {
	return c.Clauses(dbresolver.Read)
}

func (c componentRegistryDo) WriteDB() *componentRegistryDo {
	return c.Clauses(dbresolver.Write)
}

func (c componentRegistryDo) Session(config *gorm.Session) *componentRegistryDo {
	return c.withDO(c.DO.Session(config))
}

func (c componentRegistryDo) Clauses(conds ...clause.Expression) *componentRegistryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c componentRegistryDo) Returning(value interface{}, columns ...string) *componentRegistryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c componentRegistryDo) Not(conds ...gen.Condition) *componentRegistryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c componentRegistryDo) Or(conds ...gen.Condition) *componentRegistryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c componentRegistryDo) Select(conds ...field.Expr) *componentRegistryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c componentRegistryDo) Where(conds ...gen.Condition) *componentRegistryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c componentRegistryDo) Order(conds ...field.Expr) *componentRegistryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c componentRegistryDo) Distinct(cols ...field.Expr) *componentRegistryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c componentRegistryDo) Omit(cols ...field.Expr) *componentRegistryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c componentRegistryDo) Join(table schema.Tabler, on ...field.Expr) *componentRegistryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c componentRegistryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *componentRegistryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c componentRegistryDo) RightJoin(table schema.Tabler, on ...field.Expr) *componentRegistryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c componentRegistryDo) Group(cols ...field.Expr) *componentRegistryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c componentRegistryDo) Having(conds ...gen.Condition) *componentRegistryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c componentRegistryDo) Limit(limit int) *componentRegistryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c componentRegistryDo) Offset(offset int) *componentRegistryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c componentRegistryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *componentRegistryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c componentRegistryDo) Unscoped() *componentRegistryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c componentRegistryDo) Create(values ...*model.ComponentRegistry) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c componentRegistryDo) CreateInBatches(values []*model.ComponentRegistry, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c componentRegistryDo) Save(values ...*model.ComponentRegistry) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c componentRegistryDo) First() (*model.ComponentRegistry, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentRegistry), nil
	}
}

func (c componentRegistryDo) Take() (*model.ComponentRegistry, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentRegistry), nil
	}
}

func (c componentRegistryDo) Last() (*model.ComponentRegistry, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentRegistry), nil
	}
}

func (c componentRegistryDo) Find() ([]*model.ComponentRegistry, error) {
	result, err := c.DO.Find()
	return result.([]*model.ComponentRegistry), err
}

func (c componentRegistryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ComponentRegistry, err error) {
	buf := make([]*model.ComponentRegistry, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c componentRegistryDo) FindInBatches(result *[]*model.ComponentRegistry, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c componentRegistryDo) Attrs(attrs ...field.AssignExpr) *componentRegistryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c componentRegistryDo) Assign(attrs ...field.AssignExpr) *componentRegistryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c componentRegistryDo) Joins(fields ...field.RelationField) *componentRegistryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c componentRegistryDo) Preload(fields ...field.RelationField) *componentRegistryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c componentRegistryDo) FirstOrInit() (*model.ComponentRegistry, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentRegistry), nil
	}
}

func (c componentRegistryDo) FirstOrCreate() (*model.ComponentRegistry, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ComponentRegistry), nil
	}
}

func (c componentRegistryDo) FindByPage(offset int, limit int) (result []*model.ComponentRegistry, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c componentRegistryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c componentRegistryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c componentRegistryDo) Delete(models ...*model.ComponentRegistry) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *componentRegistryDo) withDO(do gen.Dao) *componentRegistryDo {
	c.DO = *do.(*gen.DO)
	return c
}
