// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newDashboardSummaries(db *gorm.DB, opts ...gen.DOOption) dashboardSummaries {
	_dashboardSummaries := dashboardSummaries{}

	_dashboardSummaries.dashboardSummariesDo.UseDB(db, opts...)
	_dashboardSummaries.dashboardSummariesDo.UseModel(&model.DashboardSummaries{})

	tableName := _dashboardSummaries.dashboardSummariesDo.TableName()
	_dashboardSummaries.ALL = field.NewAsterisk(tableName)
	_dashboardSummaries.ID = field.NewInt64(tableName, "id")
	_dashboardSummaries.ConfigID = field.NewInt64(tableName, "config_id")
	_dashboardSummaries.Date = field.NewTime(tableName, "date")
	_dashboardSummaries.BuildStatus = field.NewString(tableName, "build_status")
	_dashboardSummaries.PerfChange = field.NewFloat64(tableName, "perf_change")
	_dashboardSummaries.CommitCount = field.NewInt32(tableName, "commit_count")
	_dashboardSummaries.ContributorCount = field.NewInt32(tableName, "contributor_count")
	_dashboardSummaries.AlertInfo = field.NewField(tableName, "alert_info")
	_dashboardSummaries.TopImprovements = field.NewField(tableName, "top_improvements")
	_dashboardSummaries.TopRegressions = field.NewField(tableName, "top_regressions")
	_dashboardSummaries.AiInsights = field.NewString(tableName, "ai_insights")
	_dashboardSummaries.CreatedAt = field.NewTime(tableName, "created_at")
	_dashboardSummaries.UpdatedAt = field.NewTime(tableName, "updated_at")

	_dashboardSummaries.fillFieldMap()

	return _dashboardSummaries
}

type dashboardSummaries struct {
	dashboardSummariesDo dashboardSummariesDo

	ALL              field.Asterisk
	ID               field.Int64
	ConfigID         field.Int64
	Date             field.Time
	BuildStatus      field.String
	PerfChange       field.Float64
	CommitCount      field.Int32
	ContributorCount field.Int32
	AlertInfo        field.Field
	TopImprovements  field.Field
	TopRegressions   field.Field
	AiInsights       field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (d dashboardSummaries) Table(newTableName string) *dashboardSummaries {
	d.dashboardSummariesDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dashboardSummaries) As(alias string) *dashboardSummaries {
	d.dashboardSummariesDo.DO = *(d.dashboardSummariesDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dashboardSummaries) updateTableName(table string) *dashboardSummaries {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.ConfigID = field.NewInt64(table, "config_id")
	d.Date = field.NewTime(table, "date")
	d.BuildStatus = field.NewString(table, "build_status")
	d.PerfChange = field.NewFloat64(table, "perf_change")
	d.CommitCount = field.NewInt32(table, "commit_count")
	d.ContributorCount = field.NewInt32(table, "contributor_count")
	d.AlertInfo = field.NewField(table, "alert_info")
	d.TopImprovements = field.NewField(table, "top_improvements")
	d.TopRegressions = field.NewField(table, "top_regressions")
	d.AiInsights = field.NewString(table, "ai_insights")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *dashboardSummaries) WithContext(ctx context.Context) *dashboardSummariesDo {
	return d.dashboardSummariesDo.WithContext(ctx)
}

func (d dashboardSummaries) TableName() string { return d.dashboardSummariesDo.TableName() }

func (d dashboardSummaries) Alias() string { return d.dashboardSummariesDo.Alias() }

func (d dashboardSummaries) Columns(cols ...field.Expr) gen.Columns {
	return d.dashboardSummariesDo.Columns(cols...)
}

func (d *dashboardSummaries) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dashboardSummaries) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 13)
	d.fieldMap["id"] = d.ID
	d.fieldMap["config_id"] = d.ConfigID
	d.fieldMap["date"] = d.Date
	d.fieldMap["build_status"] = d.BuildStatus
	d.fieldMap["perf_change"] = d.PerfChange
	d.fieldMap["commit_count"] = d.CommitCount
	d.fieldMap["contributor_count"] = d.ContributorCount
	d.fieldMap["alert_info"] = d.AlertInfo
	d.fieldMap["top_improvements"] = d.TopImprovements
	d.fieldMap["top_regressions"] = d.TopRegressions
	d.fieldMap["ai_insights"] = d.AiInsights
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d dashboardSummaries) clone(db *gorm.DB) dashboardSummaries {
	d.dashboardSummariesDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dashboardSummaries) replaceDB(db *gorm.DB) dashboardSummaries {
	d.dashboardSummariesDo.ReplaceDB(db)
	return d
}

type dashboardSummariesDo struct{ gen.DO }

func (d dashboardSummariesDo) Debug() *dashboardSummariesDo {
	return d.withDO(d.DO.Debug())
}

func (d dashboardSummariesDo) WithContext(ctx context.Context) *dashboardSummariesDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dashboardSummariesDo) ReadDB() *dashboardSummariesDo {
	return d.Clauses(dbresolver.Read)
}

func (d dashboardSummariesDo) WriteDB() *dashboardSummariesDo {
	return d.Clauses(dbresolver.Write)
}

func (d dashboardSummariesDo) Session(config *gorm.Session) *dashboardSummariesDo {
	return d.withDO(d.DO.Session(config))
}

func (d dashboardSummariesDo) Clauses(conds ...clause.Expression) *dashboardSummariesDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dashboardSummariesDo) Returning(value interface{}, columns ...string) *dashboardSummariesDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dashboardSummariesDo) Not(conds ...gen.Condition) *dashboardSummariesDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dashboardSummariesDo) Or(conds ...gen.Condition) *dashboardSummariesDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dashboardSummariesDo) Select(conds ...field.Expr) *dashboardSummariesDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dashboardSummariesDo) Where(conds ...gen.Condition) *dashboardSummariesDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dashboardSummariesDo) Order(conds ...field.Expr) *dashboardSummariesDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dashboardSummariesDo) Distinct(cols ...field.Expr) *dashboardSummariesDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dashboardSummariesDo) Omit(cols ...field.Expr) *dashboardSummariesDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dashboardSummariesDo) Join(table schema.Tabler, on ...field.Expr) *dashboardSummariesDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dashboardSummariesDo) LeftJoin(table schema.Tabler, on ...field.Expr) *dashboardSummariesDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dashboardSummariesDo) RightJoin(table schema.Tabler, on ...field.Expr) *dashboardSummariesDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dashboardSummariesDo) Group(cols ...field.Expr) *dashboardSummariesDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dashboardSummariesDo) Having(conds ...gen.Condition) *dashboardSummariesDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dashboardSummariesDo) Limit(limit int) *dashboardSummariesDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dashboardSummariesDo) Offset(offset int) *dashboardSummariesDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dashboardSummariesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *dashboardSummariesDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dashboardSummariesDo) Unscoped() *dashboardSummariesDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dashboardSummariesDo) Create(values ...*model.DashboardSummaries) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dashboardSummariesDo) CreateInBatches(values []*model.DashboardSummaries, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dashboardSummariesDo) Save(values ...*model.DashboardSummaries) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dashboardSummariesDo) First() (*model.DashboardSummaries, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardSummaries), nil
	}
}

func (d dashboardSummariesDo) Take() (*model.DashboardSummaries, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardSummaries), nil
	}
}

func (d dashboardSummariesDo) Last() (*model.DashboardSummaries, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardSummaries), nil
	}
}

func (d dashboardSummariesDo) Find() ([]*model.DashboardSummaries, error) {
	result, err := d.DO.Find()
	return result.([]*model.DashboardSummaries), err
}

func (d dashboardSummariesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DashboardSummaries, err error) {
	buf := make([]*model.DashboardSummaries, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dashboardSummariesDo) FindInBatches(result *[]*model.DashboardSummaries, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dashboardSummariesDo) Attrs(attrs ...field.AssignExpr) *dashboardSummariesDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dashboardSummariesDo) Assign(attrs ...field.AssignExpr) *dashboardSummariesDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dashboardSummariesDo) Joins(fields ...field.RelationField) *dashboardSummariesDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dashboardSummariesDo) Preload(fields ...field.RelationField) *dashboardSummariesDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dashboardSummariesDo) FirstOrInit() (*model.DashboardSummaries, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardSummaries), nil
	}
}

func (d dashboardSummariesDo) FirstOrCreate() (*model.DashboardSummaries, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DashboardSummaries), nil
	}
}

func (d dashboardSummariesDo) FindByPage(offset int, limit int) (result []*model.DashboardSummaries, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dashboardSummariesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dashboardSummariesDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dashboardSummariesDo) Delete(models ...*model.DashboardSummaries) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dashboardSummariesDo) withDO(do gen.Dao) *dashboardSummariesDo {
	d.DO = *do.(*gen.DO)
	return d
}
