// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newGpuDevice(db *gorm.DB, opts ...gen.DOOption) gpuDevice {
	_gpuDevice := gpuDevice{}

	_gpuDevice.gpuDeviceDo.UseDB(db, opts...)
	_gpuDevice.gpuDeviceDo.UseModel(&model.GpuDevice{})

	tableName := _gpuDevice.gpuDeviceDo.TableName()
	_gpuDevice.ALL = field.NewAsterisk(tableName)
	_gpuDevice.ID = field.NewInt32(tableName, "id")
	_gpuDevice.NodeID = field.NewInt32(tableName, "node_id")
	_gpuDevice.GpuID = field.NewInt32(tableName, "gpu_id")
	_gpuDevice.GpuModel = field.NewString(tableName, "gpu_model")
	_gpuDevice.Memory = field.NewInt32(tableName, "memory")
	_gpuDevice.Utilization = field.NewFloat64(tableName, "utilization")
	_gpuDevice.Temperature = field.NewFloat64(tableName, "temperature")
	_gpuDevice.Power = field.NewFloat64(tableName, "power")
	_gpuDevice.Serial = field.NewString(tableName, "serial")
	_gpuDevice.RdmaDeviceName = field.NewString(tableName, "rdma_device_name")
	_gpuDevice.RdmaGUID = field.NewString(tableName, "rdma_guid")
	_gpuDevice.RdmaLid = field.NewString(tableName, "rdma_lid")
	_gpuDevice.CreatedAt = field.NewTime(tableName, "created_at")
	_gpuDevice.UpdatedAt = field.NewTime(tableName, "updated_at")
	_gpuDevice.NumaNode = field.NewInt32(tableName, "numa_node")
	_gpuDevice.NumaAffinity = field.NewInt32(tableName, "numa_affinity")

	_gpuDevice.fillFieldMap()

	return _gpuDevice
}

type gpuDevice struct {
	gpuDeviceDo

	ALL            field.Asterisk
	ID             field.Int32
	NodeID         field.Int32
	GpuID          field.Int32
	GpuModel       field.String
	Memory         field.Int32
	Utilization    field.Float64
	Temperature    field.Float64
	Power          field.Float64
	Serial         field.String
	RdmaDeviceName field.String
	RdmaGUID       field.String
	RdmaLid        field.String
	CreatedAt      field.Time
	UpdatedAt      field.Time
	NumaNode       field.Int32
	NumaAffinity   field.Int32

	fieldMap map[string]field.Expr
}

func (g gpuDevice) Table(newTableName string) *gpuDevice {
	g.gpuDeviceDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g gpuDevice) As(alias string) *gpuDevice {
	g.gpuDeviceDo.DO = *(g.gpuDeviceDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *gpuDevice) updateTableName(table string) *gpuDevice {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewInt32(table, "id")
	g.NodeID = field.NewInt32(table, "node_id")
	g.GpuID = field.NewInt32(table, "gpu_id")
	g.GpuModel = field.NewString(table, "gpu_model")
	g.Memory = field.NewInt32(table, "memory")
	g.Utilization = field.NewFloat64(table, "utilization")
	g.Temperature = field.NewFloat64(table, "temperature")
	g.Power = field.NewFloat64(table, "power")
	g.Serial = field.NewString(table, "serial")
	g.RdmaDeviceName = field.NewString(table, "rdma_device_name")
	g.RdmaGUID = field.NewString(table, "rdma_guid")
	g.RdmaLid = field.NewString(table, "rdma_lid")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.NumaNode = field.NewInt32(table, "numa_node")
	g.NumaAffinity = field.NewInt32(table, "numa_affinity")

	g.fillFieldMap()

	return g
}

func (g *gpuDevice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *gpuDevice) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 16)
	g.fieldMap["id"] = g.ID
	g.fieldMap["node_id"] = g.NodeID
	g.fieldMap["gpu_id"] = g.GpuID
	g.fieldMap["gpu_model"] = g.GpuModel
	g.fieldMap["memory"] = g.Memory
	g.fieldMap["utilization"] = g.Utilization
	g.fieldMap["temperature"] = g.Temperature
	g.fieldMap["power"] = g.Power
	g.fieldMap["serial"] = g.Serial
	g.fieldMap["rdma_device_name"] = g.RdmaDeviceName
	g.fieldMap["rdma_guid"] = g.RdmaGUID
	g.fieldMap["rdma_lid"] = g.RdmaLid
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["numa_node"] = g.NumaNode
	g.fieldMap["numa_affinity"] = g.NumaAffinity
}

func (g gpuDevice) clone(db *gorm.DB) gpuDevice {
	g.gpuDeviceDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g gpuDevice) replaceDB(db *gorm.DB) gpuDevice {
	g.gpuDeviceDo.ReplaceDB(db)
	return g
}

type gpuDeviceDo struct{ gen.DO }

type IGpuDeviceDo interface {
	gen.SubQuery
	Debug() IGpuDeviceDo
	WithContext(ctx context.Context) IGpuDeviceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGpuDeviceDo
	WriteDB() IGpuDeviceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGpuDeviceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGpuDeviceDo
	Not(conds ...gen.Condition) IGpuDeviceDo
	Or(conds ...gen.Condition) IGpuDeviceDo
	Select(conds ...field.Expr) IGpuDeviceDo
	Where(conds ...gen.Condition) IGpuDeviceDo
	Order(conds ...field.Expr) IGpuDeviceDo
	Distinct(cols ...field.Expr) IGpuDeviceDo
	Omit(cols ...field.Expr) IGpuDeviceDo
	Join(table schema.Tabler, on ...field.Expr) IGpuDeviceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGpuDeviceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGpuDeviceDo
	Group(cols ...field.Expr) IGpuDeviceDo
	Having(conds ...gen.Condition) IGpuDeviceDo
	Limit(limit int) IGpuDeviceDo
	Offset(offset int) IGpuDeviceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGpuDeviceDo
	Unscoped() IGpuDeviceDo
	Create(values ...*model.GpuDevice) error
	CreateInBatches(values []*model.GpuDevice, batchSize int) error
	Save(values ...*model.GpuDevice) error
	First() (*model.GpuDevice, error)
	Take() (*model.GpuDevice, error)
	Last() (*model.GpuDevice, error)
	Find() ([]*model.GpuDevice, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GpuDevice, err error)
	FindInBatches(result *[]*model.GpuDevice, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GpuDevice) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGpuDeviceDo
	Assign(attrs ...field.AssignExpr) IGpuDeviceDo
	Joins(fields ...field.RelationField) IGpuDeviceDo
	Preload(fields ...field.RelationField) IGpuDeviceDo
	FirstOrInit() (*model.GpuDevice, error)
	FirstOrCreate() (*model.GpuDevice, error)
	FindByPage(offset int, limit int) (result []*model.GpuDevice, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGpuDeviceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g gpuDeviceDo) Debug() IGpuDeviceDo {
	return g.withDO(g.DO.Debug())
}

func (g gpuDeviceDo) WithContext(ctx context.Context) IGpuDeviceDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g gpuDeviceDo) ReadDB() IGpuDeviceDo {
	return g.Clauses(dbresolver.Read)
}

func (g gpuDeviceDo) WriteDB() IGpuDeviceDo {
	return g.Clauses(dbresolver.Write)
}

func (g gpuDeviceDo) Session(config *gorm.Session) IGpuDeviceDo {
	return g.withDO(g.DO.Session(config))
}

func (g gpuDeviceDo) Clauses(conds ...clause.Expression) IGpuDeviceDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g gpuDeviceDo) Returning(value interface{}, columns ...string) IGpuDeviceDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g gpuDeviceDo) Not(conds ...gen.Condition) IGpuDeviceDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g gpuDeviceDo) Or(conds ...gen.Condition) IGpuDeviceDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g gpuDeviceDo) Select(conds ...field.Expr) IGpuDeviceDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g gpuDeviceDo) Where(conds ...gen.Condition) IGpuDeviceDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g gpuDeviceDo) Order(conds ...field.Expr) IGpuDeviceDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g gpuDeviceDo) Distinct(cols ...field.Expr) IGpuDeviceDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g gpuDeviceDo) Omit(cols ...field.Expr) IGpuDeviceDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g gpuDeviceDo) Join(table schema.Tabler, on ...field.Expr) IGpuDeviceDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g gpuDeviceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGpuDeviceDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g gpuDeviceDo) RightJoin(table schema.Tabler, on ...field.Expr) IGpuDeviceDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g gpuDeviceDo) Group(cols ...field.Expr) IGpuDeviceDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g gpuDeviceDo) Having(conds ...gen.Condition) IGpuDeviceDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g gpuDeviceDo) Limit(limit int) IGpuDeviceDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g gpuDeviceDo) Offset(offset int) IGpuDeviceDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g gpuDeviceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGpuDeviceDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g gpuDeviceDo) Unscoped() IGpuDeviceDo {
	return g.withDO(g.DO.Unscoped())
}

func (g gpuDeviceDo) Create(values ...*model.GpuDevice) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g gpuDeviceDo) CreateInBatches(values []*model.GpuDevice, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g gpuDeviceDo) Save(values ...*model.GpuDevice) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g gpuDeviceDo) First() (*model.GpuDevice, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GpuDevice), nil
	}
}

func (g gpuDeviceDo) Take() (*model.GpuDevice, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GpuDevice), nil
	}
}

func (g gpuDeviceDo) Last() (*model.GpuDevice, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GpuDevice), nil
	}
}

func (g gpuDeviceDo) Find() ([]*model.GpuDevice, error) {
	result, err := g.DO.Find()
	return result.([]*model.GpuDevice), err
}

func (g gpuDeviceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GpuDevice, err error) {
	buf := make([]*model.GpuDevice, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g gpuDeviceDo) FindInBatches(result *[]*model.GpuDevice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g gpuDeviceDo) Attrs(attrs ...field.AssignExpr) IGpuDeviceDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g gpuDeviceDo) Assign(attrs ...field.AssignExpr) IGpuDeviceDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g gpuDeviceDo) Joins(fields ...field.RelationField) IGpuDeviceDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g gpuDeviceDo) Preload(fields ...field.RelationField) IGpuDeviceDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g gpuDeviceDo) FirstOrInit() (*model.GpuDevice, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GpuDevice), nil
	}
}

func (g gpuDeviceDo) FirstOrCreate() (*model.GpuDevice, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GpuDevice), nil
	}
}

func (g gpuDeviceDo) FindByPage(offset int, limit int) (result []*model.GpuDevice, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g gpuDeviceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g gpuDeviceDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g gpuDeviceDo) Delete(models ...*model.GpuDevice) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *gpuDeviceDo) withDO(do gen.Dao) *gpuDeviceDo {
	g.DO = *do.(*gen.DO)
	return g
}
