// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newLensSystemConfigs(db *gorm.DB, opts ...gen.DOOption) lensSystemConfigs {
	_lensSystemConfigs := lensSystemConfigs{}

	_lensSystemConfigs.lensSystemConfigsDo.UseDB(db, opts...)
	_lensSystemConfigs.lensSystemConfigsDo.UseModel(&model.LensSystemConfigs{})

	tableName := _lensSystemConfigs.lensSystemConfigsDo.TableName()
	_lensSystemConfigs.ALL = field.NewAsterisk(tableName)
	_lensSystemConfigs.Key = field.NewString(tableName, "key")
	_lensSystemConfigs.Value = field.NewField(tableName, "value")
	_lensSystemConfigs.Category = field.NewString(tableName, "category")
	_lensSystemConfigs.Description = field.NewString(tableName, "description")
	_lensSystemConfigs.IsSecret = field.NewBool(tableName, "is_secret")
	_lensSystemConfigs.CreatedAt = field.NewTime(tableName, "created_at")
	_lensSystemConfigs.UpdatedAt = field.NewTime(tableName, "updated_at")

	_lensSystemConfigs.fillFieldMap()

	return _lensSystemConfigs
}

type lensSystemConfigs struct {
	lensSystemConfigsDo lensSystemConfigsDo

	ALL         field.Asterisk
	Key         field.String
	Value       field.Field
	Category    field.String
	Description field.String
	IsSecret    field.Bool
	CreatedAt   field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (l lensSystemConfigs) Table(newTableName string) *lensSystemConfigs {
	l.lensSystemConfigsDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l lensSystemConfigs) As(alias string) *lensSystemConfigs {
	l.lensSystemConfigsDo.DO = *(l.lensSystemConfigsDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *lensSystemConfigs) updateTableName(table string) *lensSystemConfigs {
	l.ALL = field.NewAsterisk(table)
	l.Key = field.NewString(table, "key")
	l.Value = field.NewField(table, "value")
	l.Category = field.NewString(table, "category")
	l.Description = field.NewString(table, "description")
	l.IsSecret = field.NewBool(table, "is_secret")
	l.CreatedAt = field.NewTime(table, "created_at")
	l.UpdatedAt = field.NewTime(table, "updated_at")

	l.fillFieldMap()

	return l
}

func (l *lensSystemConfigs) WithContext(ctx context.Context) *lensSystemConfigsDo {
	return l.lensSystemConfigsDo.WithContext(ctx)
}

func (l lensSystemConfigs) TableName() string { return l.lensSystemConfigsDo.TableName() }

func (l lensSystemConfigs) Alias() string { return l.lensSystemConfigsDo.Alias() }

func (l lensSystemConfigs) Columns(cols ...field.Expr) gen.Columns {
	return l.lensSystemConfigsDo.Columns(cols...)
}

func (l *lensSystemConfigs) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *lensSystemConfigs) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 7)
	l.fieldMap["key"] = l.Key
	l.fieldMap["value"] = l.Value
	l.fieldMap["category"] = l.Category
	l.fieldMap["description"] = l.Description
	l.fieldMap["is_secret"] = l.IsSecret
	l.fieldMap["created_at"] = l.CreatedAt
	l.fieldMap["updated_at"] = l.UpdatedAt
}

func (l lensSystemConfigs) clone(db *gorm.DB) lensSystemConfigs {
	l.lensSystemConfigsDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l lensSystemConfigs) replaceDB(db *gorm.DB) lensSystemConfigs {
	l.lensSystemConfigsDo.ReplaceDB(db)
	return l
}

type lensSystemConfigsDo struct{ gen.DO }

func (l lensSystemConfigsDo) Debug() *lensSystemConfigsDo {
	return l.withDO(l.DO.Debug())
}

func (l lensSystemConfigsDo) WithContext(ctx context.Context) *lensSystemConfigsDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l lensSystemConfigsDo) ReadDB() *lensSystemConfigsDo {
	return l.Clauses(dbresolver.Read)
}

func (l lensSystemConfigsDo) WriteDB() *lensSystemConfigsDo {
	return l.Clauses(dbresolver.Write)
}

func (l lensSystemConfigsDo) Session(config *gorm.Session) *lensSystemConfigsDo {
	return l.withDO(l.DO.Session(config))
}

func (l lensSystemConfigsDo) Clauses(conds ...clause.Expression) *lensSystemConfigsDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l lensSystemConfigsDo) Returning(value interface{}, columns ...string) *lensSystemConfigsDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l lensSystemConfigsDo) Not(conds ...gen.Condition) *lensSystemConfigsDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l lensSystemConfigsDo) Or(conds ...gen.Condition) *lensSystemConfigsDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l lensSystemConfigsDo) Select(conds ...field.Expr) *lensSystemConfigsDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l lensSystemConfigsDo) Where(conds ...gen.Condition) *lensSystemConfigsDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l lensSystemConfigsDo) Order(conds ...field.Expr) *lensSystemConfigsDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l lensSystemConfigsDo) Distinct(cols ...field.Expr) *lensSystemConfigsDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l lensSystemConfigsDo) Omit(cols ...field.Expr) *lensSystemConfigsDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l lensSystemConfigsDo) Join(table schema.Tabler, on ...field.Expr) *lensSystemConfigsDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l lensSystemConfigsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *lensSystemConfigsDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l lensSystemConfigsDo) RightJoin(table schema.Tabler, on ...field.Expr) *lensSystemConfigsDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l lensSystemConfigsDo) Group(cols ...field.Expr) *lensSystemConfigsDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l lensSystemConfigsDo) Having(conds ...gen.Condition) *lensSystemConfigsDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l lensSystemConfigsDo) Limit(limit int) *lensSystemConfigsDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l lensSystemConfigsDo) Offset(offset int) *lensSystemConfigsDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l lensSystemConfigsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *lensSystemConfigsDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l lensSystemConfigsDo) Unscoped() *lensSystemConfigsDo {
	return l.withDO(l.DO.Unscoped())
}

func (l lensSystemConfigsDo) Create(values ...*model.LensSystemConfigs) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l lensSystemConfigsDo) CreateInBatches(values []*model.LensSystemConfigs, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l lensSystemConfigsDo) Save(values ...*model.LensSystemConfigs) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l lensSystemConfigsDo) First() (*model.LensSystemConfigs, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LensSystemConfigs), nil
	}
}

func (l lensSystemConfigsDo) Take() (*model.LensSystemConfigs, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LensSystemConfigs), nil
	}
}

func (l lensSystemConfigsDo) Last() (*model.LensSystemConfigs, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LensSystemConfigs), nil
	}
}

func (l lensSystemConfigsDo) Find() ([]*model.LensSystemConfigs, error) {
	result, err := l.DO.Find()
	return result.([]*model.LensSystemConfigs), err
}

func (l lensSystemConfigsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LensSystemConfigs, err error) {
	buf := make([]*model.LensSystemConfigs, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l lensSystemConfigsDo) FindInBatches(result *[]*model.LensSystemConfigs, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l lensSystemConfigsDo) Attrs(attrs ...field.AssignExpr) *lensSystemConfigsDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l lensSystemConfigsDo) Assign(attrs ...field.AssignExpr) *lensSystemConfigsDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l lensSystemConfigsDo) Joins(fields ...field.RelationField) *lensSystemConfigsDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l lensSystemConfigsDo) Preload(fields ...field.RelationField) *lensSystemConfigsDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l lensSystemConfigsDo) FirstOrInit() (*model.LensSystemConfigs, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LensSystemConfigs), nil
	}
}

func (l lensSystemConfigsDo) FirstOrCreate() (*model.LensSystemConfigs, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LensSystemConfigs), nil
	}
}

func (l lensSystemConfigsDo) FindByPage(offset int, limit int) (result []*model.LensSystemConfigs, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l lensSystemConfigsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l lensSystemConfigsDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l lensSystemConfigsDo) Delete(models ...*model.LensSystemConfigs) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *lensSystemConfigsDo) withDO(do gen.Dao) *lensSystemConfigsDo {
	l.DO = *do.(*gen.DO)
	return l
}
