// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newNodeContainer(db *gorm.DB, opts ...gen.DOOption) nodeContainer {
	_nodeContainer := nodeContainer{}

	_nodeContainer.nodeContainerDo.UseDB(db, opts...)
	_nodeContainer.nodeContainerDo.UseModel(&model.NodeContainer{})

	tableName := _nodeContainer.nodeContainerDo.TableName()
	_nodeContainer.ALL = field.NewAsterisk(tableName)
	_nodeContainer.ID = field.NewInt32(tableName, "id")
	_nodeContainer.ContainerID = field.NewString(tableName, "container_id")
	_nodeContainer.ContainerName = field.NewString(tableName, "container_name")
	_nodeContainer.PodUID = field.NewString(tableName, "pod_uid")
	_nodeContainer.PodName = field.NewString(tableName, "pod_name")
	_nodeContainer.PodNamespace = field.NewString(tableName, "pod_namespace")
	_nodeContainer.Status = field.NewString(tableName, "status")
	_nodeContainer.CreatedAt = field.NewTime(tableName, "created_at")
	_nodeContainer.UpdatedAt = field.NewTime(tableName, "updated_at")
	_nodeContainer.NodeName = field.NewString(tableName, "node_name")
	_nodeContainer.Source = field.NewString(tableName, "source")

	_nodeContainer.fillFieldMap()

	return _nodeContainer
}

type nodeContainer struct {
	nodeContainerDo nodeContainerDo

	ALL           field.Asterisk
	ID            field.Int32
	ContainerID   field.String
	ContainerName field.String
	PodUID        field.String
	PodName       field.String
	PodNamespace  field.String
	Status        field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time
	NodeName      field.String
	Source        field.String

	fieldMap map[string]field.Expr
}

func (n nodeContainer) Table(newTableName string) *nodeContainer {
	n.nodeContainerDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n nodeContainer) As(alias string) *nodeContainer {
	n.nodeContainerDo.DO = *(n.nodeContainerDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *nodeContainer) updateTableName(table string) *nodeContainer {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt32(table, "id")
	n.ContainerID = field.NewString(table, "container_id")
	n.ContainerName = field.NewString(table, "container_name")
	n.PodUID = field.NewString(table, "pod_uid")
	n.PodName = field.NewString(table, "pod_name")
	n.PodNamespace = field.NewString(table, "pod_namespace")
	n.Status = field.NewString(table, "status")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")
	n.NodeName = field.NewString(table, "node_name")
	n.Source = field.NewString(table, "source")

	n.fillFieldMap()

	return n
}

func (n *nodeContainer) WithContext(ctx context.Context) *nodeContainerDo {
	return n.nodeContainerDo.WithContext(ctx)
}

func (n nodeContainer) TableName() string { return n.nodeContainerDo.TableName() }

func (n nodeContainer) Alias() string { return n.nodeContainerDo.Alias() }

func (n nodeContainer) Columns(cols ...field.Expr) gen.Columns {
	return n.nodeContainerDo.Columns(cols...)
}

func (n *nodeContainer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *nodeContainer) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 11)
	n.fieldMap["id"] = n.ID
	n.fieldMap["container_id"] = n.ContainerID
	n.fieldMap["container_name"] = n.ContainerName
	n.fieldMap["pod_uid"] = n.PodUID
	n.fieldMap["pod_name"] = n.PodName
	n.fieldMap["pod_namespace"] = n.PodNamespace
	n.fieldMap["status"] = n.Status
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
	n.fieldMap["node_name"] = n.NodeName
	n.fieldMap["source"] = n.Source
}

func (n nodeContainer) clone(db *gorm.DB) nodeContainer {
	n.nodeContainerDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n nodeContainer) replaceDB(db *gorm.DB) nodeContainer {
	n.nodeContainerDo.ReplaceDB(db)
	return n
}

type nodeContainerDo struct{ gen.DO }

func (n nodeContainerDo) Debug() *nodeContainerDo {
	return n.withDO(n.DO.Debug())
}

func (n nodeContainerDo) WithContext(ctx context.Context) *nodeContainerDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n nodeContainerDo) ReadDB() *nodeContainerDo {
	return n.Clauses(dbresolver.Read)
}

func (n nodeContainerDo) WriteDB() *nodeContainerDo {
	return n.Clauses(dbresolver.Write)
}

func (n nodeContainerDo) Session(config *gorm.Session) *nodeContainerDo {
	return n.withDO(n.DO.Session(config))
}

func (n nodeContainerDo) Clauses(conds ...clause.Expression) *nodeContainerDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n nodeContainerDo) Returning(value interface{}, columns ...string) *nodeContainerDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n nodeContainerDo) Not(conds ...gen.Condition) *nodeContainerDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n nodeContainerDo) Or(conds ...gen.Condition) *nodeContainerDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n nodeContainerDo) Select(conds ...field.Expr) *nodeContainerDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n nodeContainerDo) Where(conds ...gen.Condition) *nodeContainerDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n nodeContainerDo) Order(conds ...field.Expr) *nodeContainerDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n nodeContainerDo) Distinct(cols ...field.Expr) *nodeContainerDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n nodeContainerDo) Omit(cols ...field.Expr) *nodeContainerDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n nodeContainerDo) Join(table schema.Tabler, on ...field.Expr) *nodeContainerDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n nodeContainerDo) LeftJoin(table schema.Tabler, on ...field.Expr) *nodeContainerDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n nodeContainerDo) RightJoin(table schema.Tabler, on ...field.Expr) *nodeContainerDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n nodeContainerDo) Group(cols ...field.Expr) *nodeContainerDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n nodeContainerDo) Having(conds ...gen.Condition) *nodeContainerDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n nodeContainerDo) Limit(limit int) *nodeContainerDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n nodeContainerDo) Offset(offset int) *nodeContainerDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n nodeContainerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *nodeContainerDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n nodeContainerDo) Unscoped() *nodeContainerDo {
	return n.withDO(n.DO.Unscoped())
}

func (n nodeContainerDo) Create(values ...*model.NodeContainer) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n nodeContainerDo) CreateInBatches(values []*model.NodeContainer, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n nodeContainerDo) Save(values ...*model.NodeContainer) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n nodeContainerDo) First() (*model.NodeContainer, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeContainer), nil
	}
}

func (n nodeContainerDo) Take() (*model.NodeContainer, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeContainer), nil
	}
}

func (n nodeContainerDo) Last() (*model.NodeContainer, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeContainer), nil
	}
}

func (n nodeContainerDo) Find() ([]*model.NodeContainer, error) {
	result, err := n.DO.Find()
	return result.([]*model.NodeContainer), err
}

func (n nodeContainerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NodeContainer, err error) {
	buf := make([]*model.NodeContainer, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n nodeContainerDo) FindInBatches(result *[]*model.NodeContainer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n nodeContainerDo) Attrs(attrs ...field.AssignExpr) *nodeContainerDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n nodeContainerDo) Assign(attrs ...field.AssignExpr) *nodeContainerDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n nodeContainerDo) Joins(fields ...field.RelationField) *nodeContainerDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n nodeContainerDo) Preload(fields ...field.RelationField) *nodeContainerDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n nodeContainerDo) FirstOrInit() (*model.NodeContainer, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeContainer), nil
	}
}

func (n nodeContainerDo) FirstOrCreate() (*model.NodeContainer, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NodeContainer), nil
	}
}

func (n nodeContainerDo) FindByPage(offset int, limit int) (result []*model.NodeContainer, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n nodeContainerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n nodeContainerDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n nodeContainerDo) Delete(models ...*model.NodeContainer) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *nodeContainerDo) withDO(do gen.Dao) *nodeContainerDo {
	n.DO = *do.(*gen.DO)
	return n
}
