// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newStorage(db *gorm.DB, opts ...gen.DOOption) storage {
	_storage := storage{}

	_storage.storageDo.UseDB(db, opts...)
	_storage.storageDo.UseModel(&model.Storage{})

	tableName := _storage.storageDo.TableName()
	_storage.ALL = field.NewAsterisk(tableName)
	_storage.ID = field.NewInt32(tableName, "id")
	_storage.Name = field.NewString(tableName, "name")
	_storage.Kind = field.NewString(tableName, "kind")
	_storage.Config = field.NewField(tableName, "config")
	_storage.Source = field.NewString(tableName, "source")
	_storage.Status = field.NewString(tableName, "status")
	_storage.CreatedAt = field.NewTime(tableName, "created_at")
	_storage.UpdatedAt = field.NewTime(tableName, "updated_at")
	_storage.DeletedAt = field.NewField(tableName, "deleted_at")

	_storage.fillFieldMap()

	return _storage
}

type storage struct {
	storageDo storageDo

	ALL       field.Asterisk
	ID        field.Int32
	Name      field.String
	Kind      field.String
	Config    field.Field
	Source    field.String
	Status    field.String
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (s storage) Table(newTableName string) *storage {
	s.storageDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s storage) As(alias string) *storage {
	s.storageDo.DO = *(s.storageDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *storage) updateTableName(table string) *storage {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.Name = field.NewString(table, "name")
	s.Kind = field.NewString(table, "kind")
	s.Config = field.NewField(table, "config")
	s.Source = field.NewString(table, "source")
	s.Status = field.NewString(table, "status")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *storage) WithContext(ctx context.Context) *storageDo { return s.storageDo.WithContext(ctx) }

func (s storage) TableName() string { return s.storageDo.TableName() }

func (s storage) Alias() string { return s.storageDo.Alias() }

func (s storage) Columns(cols ...field.Expr) gen.Columns { return s.storageDo.Columns(cols...) }

func (s *storage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *storage) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["name"] = s.Name
	s.fieldMap["kind"] = s.Kind
	s.fieldMap["config"] = s.Config
	s.fieldMap["source"] = s.Source
	s.fieldMap["status"] = s.Status
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s storage) clone(db *gorm.DB) storage {
	s.storageDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s storage) replaceDB(db *gorm.DB) storage {
	s.storageDo.ReplaceDB(db)
	return s
}

type storageDo struct{ gen.DO }

func (s storageDo) Debug() *storageDo {
	return s.withDO(s.DO.Debug())
}

func (s storageDo) WithContext(ctx context.Context) *storageDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s storageDo) ReadDB() *storageDo {
	return s.Clauses(dbresolver.Read)
}

func (s storageDo) WriteDB() *storageDo {
	return s.Clauses(dbresolver.Write)
}

func (s storageDo) Session(config *gorm.Session) *storageDo {
	return s.withDO(s.DO.Session(config))
}

func (s storageDo) Clauses(conds ...clause.Expression) *storageDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s storageDo) Returning(value interface{}, columns ...string) *storageDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s storageDo) Not(conds ...gen.Condition) *storageDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s storageDo) Or(conds ...gen.Condition) *storageDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s storageDo) Select(conds ...field.Expr) *storageDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s storageDo) Where(conds ...gen.Condition) *storageDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s storageDo) Order(conds ...field.Expr) *storageDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s storageDo) Distinct(cols ...field.Expr) *storageDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s storageDo) Omit(cols ...field.Expr) *storageDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s storageDo) Join(table schema.Tabler, on ...field.Expr) *storageDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s storageDo) LeftJoin(table schema.Tabler, on ...field.Expr) *storageDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s storageDo) RightJoin(table schema.Tabler, on ...field.Expr) *storageDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s storageDo) Group(cols ...field.Expr) *storageDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s storageDo) Having(conds ...gen.Condition) *storageDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s storageDo) Limit(limit int) *storageDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s storageDo) Offset(offset int) *storageDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s storageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *storageDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s storageDo) Unscoped() *storageDo {
	return s.withDO(s.DO.Unscoped())
}

func (s storageDo) Create(values ...*model.Storage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s storageDo) CreateInBatches(values []*model.Storage, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s storageDo) Save(values ...*model.Storage) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s storageDo) First() (*model.Storage, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) Take() (*model.Storage, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) Last() (*model.Storage, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) Find() ([]*model.Storage, error) {
	result, err := s.DO.Find()
	return result.([]*model.Storage), err
}

func (s storageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Storage, err error) {
	buf := make([]*model.Storage, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s storageDo) FindInBatches(result *[]*model.Storage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s storageDo) Attrs(attrs ...field.AssignExpr) *storageDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s storageDo) Assign(attrs ...field.AssignExpr) *storageDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s storageDo) Joins(fields ...field.RelationField) *storageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s storageDo) Preload(fields ...field.RelationField) *storageDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s storageDo) FirstOrInit() (*model.Storage, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) FirstOrCreate() (*model.Storage, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Storage), nil
	}
}

func (s storageDo) FindByPage(offset int, limit int) (result []*model.Storage, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s storageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s storageDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s storageDo) Delete(models ...*model.Storage) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *storageDo) withDO(do gen.Dao) *storageDo {
	s.DO = *do.(*gen.DO)
	return s
}
