// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newWorkloadTaskState(db *gorm.DB, opts ...gen.DOOption) workloadTaskState {
	_workloadTaskState := workloadTaskState{}

	_workloadTaskState.workloadTaskStateDo.UseDB(db, opts...)
	_workloadTaskState.workloadTaskStateDo.UseModel(&model.WorkloadTaskState{})

	tableName := _workloadTaskState.workloadTaskStateDo.TableName()
	_workloadTaskState.ALL = field.NewAsterisk(tableName)
	_workloadTaskState.ID = field.NewInt64(tableName, "id")
	_workloadTaskState.WorkloadUID = field.NewString(tableName, "workload_uid")
	_workloadTaskState.TaskType = field.NewString(tableName, "task_type")
	_workloadTaskState.Status = field.NewString(tableName, "status")
	_workloadTaskState.LockOwner = field.NewString(tableName, "lock_owner")
	_workloadTaskState.LockAcquiredAt = field.NewTime(tableName, "lock_acquired_at")
	_workloadTaskState.LockExpiresAt = field.NewTime(tableName, "lock_expires_at")
	_workloadTaskState.LockVersion = field.NewInt64(tableName, "lock_version")
	_workloadTaskState.Ext = field.NewField(tableName, "ext")
	_workloadTaskState.CreatedAt = field.NewTime(tableName, "created_at")
	_workloadTaskState.UpdatedAt = field.NewTime(tableName, "updated_at")

	_workloadTaskState.fillFieldMap()

	return _workloadTaskState
}

type workloadTaskState struct {
	workloadTaskStateDo workloadTaskStateDo

	ALL            field.Asterisk
	ID             field.Int64
	WorkloadUID    field.String // Workload unique identifier
	TaskType       field.String // Task type: detection, metadata_collection, tensorboard_stream, etc
	Status         field.String // Task status: pending, running, completed, failed, cancelled
	LockOwner      field.String // Instance ID that currently owns this task
	LockAcquiredAt field.Time   // Timestamp when lock was acquired
	LockExpiresAt  field.Time   // Timestamp when lock expires (for stale lock detection)
	LockVersion    field.Int64  // Version number for optimistic locking
	Ext            field.Field  // Extension field (JSONB) for all other task data
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (w workloadTaskState) Table(newTableName string) *workloadTaskState {
	w.workloadTaskStateDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workloadTaskState) As(alias string) *workloadTaskState {
	w.workloadTaskStateDo.DO = *(w.workloadTaskStateDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workloadTaskState) updateTableName(table string) *workloadTaskState {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt64(table, "id")
	w.WorkloadUID = field.NewString(table, "workload_uid")
	w.TaskType = field.NewString(table, "task_type")
	w.Status = field.NewString(table, "status")
	w.LockOwner = field.NewString(table, "lock_owner")
	w.LockAcquiredAt = field.NewTime(table, "lock_acquired_at")
	w.LockExpiresAt = field.NewTime(table, "lock_expires_at")
	w.LockVersion = field.NewInt64(table, "lock_version")
	w.Ext = field.NewField(table, "ext")
	w.CreatedAt = field.NewTime(table, "created_at")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *workloadTaskState) WithContext(ctx context.Context) *workloadTaskStateDo {
	return w.workloadTaskStateDo.WithContext(ctx)
}

func (w workloadTaskState) TableName() string { return w.workloadTaskStateDo.TableName() }

func (w workloadTaskState) Alias() string { return w.workloadTaskStateDo.Alias() }

func (w workloadTaskState) Columns(cols ...field.Expr) gen.Columns {
	return w.workloadTaskStateDo.Columns(cols...)
}

func (w *workloadTaskState) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workloadTaskState) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 11)
	w.fieldMap["id"] = w.ID
	w.fieldMap["workload_uid"] = w.WorkloadUID
	w.fieldMap["task_type"] = w.TaskType
	w.fieldMap["status"] = w.Status
	w.fieldMap["lock_owner"] = w.LockOwner
	w.fieldMap["lock_acquired_at"] = w.LockAcquiredAt
	w.fieldMap["lock_expires_at"] = w.LockExpiresAt
	w.fieldMap["lock_version"] = w.LockVersion
	w.fieldMap["ext"] = w.Ext
	w.fieldMap["created_at"] = w.CreatedAt
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w workloadTaskState) clone(db *gorm.DB) workloadTaskState {
	w.workloadTaskStateDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w workloadTaskState) replaceDB(db *gorm.DB) workloadTaskState {
	w.workloadTaskStateDo.ReplaceDB(db)
	return w
}

type workloadTaskStateDo struct{ gen.DO }

func (w workloadTaskStateDo) Debug() *workloadTaskStateDo {
	return w.withDO(w.DO.Debug())
}

func (w workloadTaskStateDo) WithContext(ctx context.Context) *workloadTaskStateDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workloadTaskStateDo) ReadDB() *workloadTaskStateDo {
	return w.Clauses(dbresolver.Read)
}

func (w workloadTaskStateDo) WriteDB() *workloadTaskStateDo {
	return w.Clauses(dbresolver.Write)
}

func (w workloadTaskStateDo) Session(config *gorm.Session) *workloadTaskStateDo {
	return w.withDO(w.DO.Session(config))
}

func (w workloadTaskStateDo) Clauses(conds ...clause.Expression) *workloadTaskStateDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workloadTaskStateDo) Returning(value interface{}, columns ...string) *workloadTaskStateDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workloadTaskStateDo) Not(conds ...gen.Condition) *workloadTaskStateDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workloadTaskStateDo) Or(conds ...gen.Condition) *workloadTaskStateDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workloadTaskStateDo) Select(conds ...field.Expr) *workloadTaskStateDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workloadTaskStateDo) Where(conds ...gen.Condition) *workloadTaskStateDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workloadTaskStateDo) Order(conds ...field.Expr) *workloadTaskStateDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workloadTaskStateDo) Distinct(cols ...field.Expr) *workloadTaskStateDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workloadTaskStateDo) Omit(cols ...field.Expr) *workloadTaskStateDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workloadTaskStateDo) Join(table schema.Tabler, on ...field.Expr) *workloadTaskStateDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workloadTaskStateDo) LeftJoin(table schema.Tabler, on ...field.Expr) *workloadTaskStateDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workloadTaskStateDo) RightJoin(table schema.Tabler, on ...field.Expr) *workloadTaskStateDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workloadTaskStateDo) Group(cols ...field.Expr) *workloadTaskStateDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workloadTaskStateDo) Having(conds ...gen.Condition) *workloadTaskStateDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workloadTaskStateDo) Limit(limit int) *workloadTaskStateDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workloadTaskStateDo) Offset(offset int) *workloadTaskStateDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workloadTaskStateDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *workloadTaskStateDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workloadTaskStateDo) Unscoped() *workloadTaskStateDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workloadTaskStateDo) Create(values ...*model.WorkloadTaskState) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workloadTaskStateDo) CreateInBatches(values []*model.WorkloadTaskState, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workloadTaskStateDo) Save(values ...*model.WorkloadTaskState) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workloadTaskStateDo) First() (*model.WorkloadTaskState, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadTaskState), nil
	}
}

func (w workloadTaskStateDo) Take() (*model.WorkloadTaskState, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadTaskState), nil
	}
}

func (w workloadTaskStateDo) Last() (*model.WorkloadTaskState, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadTaskState), nil
	}
}

func (w workloadTaskStateDo) Find() ([]*model.WorkloadTaskState, error) {
	result, err := w.DO.Find()
	return result.([]*model.WorkloadTaskState), err
}

func (w workloadTaskStateDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkloadTaskState, err error) {
	buf := make([]*model.WorkloadTaskState, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workloadTaskStateDo) FindInBatches(result *[]*model.WorkloadTaskState, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workloadTaskStateDo) Attrs(attrs ...field.AssignExpr) *workloadTaskStateDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workloadTaskStateDo) Assign(attrs ...field.AssignExpr) *workloadTaskStateDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workloadTaskStateDo) Joins(fields ...field.RelationField) *workloadTaskStateDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workloadTaskStateDo) Preload(fields ...field.RelationField) *workloadTaskStateDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workloadTaskStateDo) FirstOrInit() (*model.WorkloadTaskState, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadTaskState), nil
	}
}

func (w workloadTaskStateDo) FirstOrCreate() (*model.WorkloadTaskState, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadTaskState), nil
	}
}

func (w workloadTaskStateDo) FindByPage(offset int, limit int) (result []*model.WorkloadTaskState, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workloadTaskStateDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workloadTaskStateDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workloadTaskStateDo) Delete(models ...*model.WorkloadTaskState) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workloadTaskStateDo) withDO(do gen.Dao) *workloadTaskStateDo {
	w.DO = *do.(*gen.DO)
	return w
}
