// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dal

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/AMD-AGI/Primus-SaFE/Lens/core/pkg/database/model"
)

func newWorkloadResource(db *gorm.DB, opts ...gen.DOOption) workloadResource {
	_workloadResource := workloadResource{}

	_workloadResource.workloadResourceDo.UseDB(db, opts...)
	_workloadResource.workloadResourceDo.UseModel(&model.WorkloadResource{})

	tableName := _workloadResource.workloadResourceDo.TableName()
	_workloadResource.ALL = field.NewAsterisk(tableName)
	_workloadResource.ID = field.NewInt32(tableName, "id")
	_workloadResource.WorkloadUID = field.NewString(tableName, "workload_uid")
	_workloadResource.GpuTimeSeconds = field.NewFloat64(tableName, "gpu_time_seconds")
	_workloadResource.GpuRequest = field.NewInt32(tableName, "gpu_request")
	_workloadResource.GpuModel = field.NewString(tableName, "gpu_model")
	_workloadResource.PodCount = field.NewInt32(tableName, "pod_count")
	_workloadResource.UpdatedAt = field.NewTime(tableName, "updated_at")

	_workloadResource.fillFieldMap()

	return _workloadResource
}

type workloadResource struct {
	workloadResourceDo workloadResourceDo

	ALL            field.Asterisk
	ID             field.Int32
	WorkloadUID    field.String
	GpuTimeSeconds field.Float64
	GpuRequest     field.Int32
	GpuModel       field.String
	PodCount       field.Int32
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (w workloadResource) Table(newTableName string) *workloadResource {
	w.workloadResourceDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w workloadResource) As(alias string) *workloadResource {
	w.workloadResourceDo.DO = *(w.workloadResourceDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *workloadResource) updateTableName(table string) *workloadResource {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewInt32(table, "id")
	w.WorkloadUID = field.NewString(table, "workload_uid")
	w.GpuTimeSeconds = field.NewFloat64(table, "gpu_time_seconds")
	w.GpuRequest = field.NewInt32(table, "gpu_request")
	w.GpuModel = field.NewString(table, "gpu_model")
	w.PodCount = field.NewInt32(table, "pod_count")
	w.UpdatedAt = field.NewTime(table, "updated_at")

	w.fillFieldMap()

	return w
}

func (w *workloadResource) WithContext(ctx context.Context) *workloadResourceDo {
	return w.workloadResourceDo.WithContext(ctx)
}

func (w workloadResource) TableName() string { return w.workloadResourceDo.TableName() }

func (w workloadResource) Alias() string { return w.workloadResourceDo.Alias() }

func (w workloadResource) Columns(cols ...field.Expr) gen.Columns {
	return w.workloadResourceDo.Columns(cols...)
}

func (w *workloadResource) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *workloadResource) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 7)
	w.fieldMap["id"] = w.ID
	w.fieldMap["workload_uid"] = w.WorkloadUID
	w.fieldMap["gpu_time_seconds"] = w.GpuTimeSeconds
	w.fieldMap["gpu_request"] = w.GpuRequest
	w.fieldMap["gpu_model"] = w.GpuModel
	w.fieldMap["pod_count"] = w.PodCount
	w.fieldMap["updated_at"] = w.UpdatedAt
}

func (w workloadResource) clone(db *gorm.DB) workloadResource {
	w.workloadResourceDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w workloadResource) replaceDB(db *gorm.DB) workloadResource {
	w.workloadResourceDo.ReplaceDB(db)
	return w
}

type workloadResourceDo struct{ gen.DO }

func (w workloadResourceDo) Debug() *workloadResourceDo {
	return w.withDO(w.DO.Debug())
}

func (w workloadResourceDo) WithContext(ctx context.Context) *workloadResourceDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w workloadResourceDo) ReadDB() *workloadResourceDo {
	return w.Clauses(dbresolver.Read)
}

func (w workloadResourceDo) WriteDB() *workloadResourceDo {
	return w.Clauses(dbresolver.Write)
}

func (w workloadResourceDo) Session(config *gorm.Session) *workloadResourceDo {
	return w.withDO(w.DO.Session(config))
}

func (w workloadResourceDo) Clauses(conds ...clause.Expression) *workloadResourceDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w workloadResourceDo) Returning(value interface{}, columns ...string) *workloadResourceDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w workloadResourceDo) Not(conds ...gen.Condition) *workloadResourceDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w workloadResourceDo) Or(conds ...gen.Condition) *workloadResourceDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w workloadResourceDo) Select(conds ...field.Expr) *workloadResourceDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w workloadResourceDo) Where(conds ...gen.Condition) *workloadResourceDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w workloadResourceDo) Order(conds ...field.Expr) *workloadResourceDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w workloadResourceDo) Distinct(cols ...field.Expr) *workloadResourceDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w workloadResourceDo) Omit(cols ...field.Expr) *workloadResourceDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w workloadResourceDo) Join(table schema.Tabler, on ...field.Expr) *workloadResourceDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w workloadResourceDo) LeftJoin(table schema.Tabler, on ...field.Expr) *workloadResourceDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w workloadResourceDo) RightJoin(table schema.Tabler, on ...field.Expr) *workloadResourceDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w workloadResourceDo) Group(cols ...field.Expr) *workloadResourceDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w workloadResourceDo) Having(conds ...gen.Condition) *workloadResourceDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w workloadResourceDo) Limit(limit int) *workloadResourceDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w workloadResourceDo) Offset(offset int) *workloadResourceDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w workloadResourceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *workloadResourceDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w workloadResourceDo) Unscoped() *workloadResourceDo {
	return w.withDO(w.DO.Unscoped())
}

func (w workloadResourceDo) Create(values ...*model.WorkloadResource) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w workloadResourceDo) CreateInBatches(values []*model.WorkloadResource, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w workloadResourceDo) Save(values ...*model.WorkloadResource) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w workloadResourceDo) First() (*model.WorkloadResource, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadResource), nil
	}
}

func (w workloadResourceDo) Take() (*model.WorkloadResource, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadResource), nil
	}
}

func (w workloadResourceDo) Last() (*model.WorkloadResource, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadResource), nil
	}
}

func (w workloadResourceDo) Find() ([]*model.WorkloadResource, error) {
	result, err := w.DO.Find()
	return result.([]*model.WorkloadResource), err
}

func (w workloadResourceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WorkloadResource, err error) {
	buf := make([]*model.WorkloadResource, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w workloadResourceDo) FindInBatches(result *[]*model.WorkloadResource, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w workloadResourceDo) Attrs(attrs ...field.AssignExpr) *workloadResourceDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w workloadResourceDo) Assign(attrs ...field.AssignExpr) *workloadResourceDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w workloadResourceDo) Joins(fields ...field.RelationField) *workloadResourceDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w workloadResourceDo) Preload(fields ...field.RelationField) *workloadResourceDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w workloadResourceDo) FirstOrInit() (*model.WorkloadResource, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadResource), nil
	}
}

func (w workloadResourceDo) FirstOrCreate() (*model.WorkloadResource, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WorkloadResource), nil
	}
}

func (w workloadResourceDo) FindByPage(offset int, limit int) (result []*model.WorkloadResource, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w workloadResourceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w workloadResourceDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w workloadResourceDo) Delete(models ...*model.WorkloadResource) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *workloadResourceDo) withDO(do gen.Dao) *workloadResourceDo {
	w.DO = *do.(*gen.DO)
	return w
}
