// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/AMD-AIG-AIMA/SAFE/common/pkg/database/client (interfaces: Interface)

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	reflect "reflect"

	client "github.com/AMD-AIG-AIMA/SAFE/common/pkg/database/client"
	model "github.com/AMD-AIG-AIMA/SAFE/common/pkg/database/client/model"
	squirrel "github.com/Masterminds/squirrel"
	gomock "github.com/golang/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// AckEmailOutbox mocks base method.
func (m *MockInterface) AckEmailOutbox(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckEmailOutbox", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AckEmailOutbox indicates an expected call of AckEmailOutbox.
func (mr *MockInterfaceMockRecorder) AckEmailOutbox(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckEmailOutbox", reflect.TypeOf((*MockInterface)(nil).AckEmailOutbox), arg0, arg1)
}

// BatchInsertAuditLogs mocks base method.
func (m *MockInterface) BatchInsertAuditLogs(arg0 context.Context, arg1 []*client.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsertAuditLogs", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsertAuditLogs indicates an expected call of BatchInsertAuditLogs.
func (mr *MockInterfaceMockRecorder) BatchInsertAuditLogs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsertAuditLogs", reflect.TypeOf((*MockInterface)(nil).BatchInsertAuditLogs), arg0, arg1)
}

// CheckDatasetNameExists mocks base method.
func (m *MockInterface) CheckDatasetNameExists(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDatasetNameExists", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckDatasetNameExists indicates an expected call of CheckDatasetNameExists.
func (mr *MockInterfaceMockRecorder) CheckDatasetNameExists(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDatasetNameExists", reflect.TypeOf((*MockInterface)(nil).CheckDatasetNameExists), arg0, arg1)
}

// CountApiKeys mocks base method.
func (m *MockInterface) CountApiKeys(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountApiKeys", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountApiKeys indicates an expected call of CountApiKeys.
func (mr *MockInterfaceMockRecorder) CountApiKeys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountApiKeys", reflect.TypeOf((*MockInterface)(nil).CountApiKeys), arg0, arg1)
}

// CountAuditLogs mocks base method.
func (m *MockInterface) CountAuditLogs(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAuditLogs", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAuditLogs indicates an expected call of CountAuditLogs.
func (mr *MockInterfaceMockRecorder) CountAuditLogs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAuditLogs", reflect.TypeOf((*MockInterface)(nil).CountAuditLogs), arg0, arg1)
}

// CountDatasets mocks base method.
func (m *MockInterface) CountDatasets(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDatasets", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDatasets indicates an expected call of CountDatasets.
func (mr *MockInterfaceMockRecorder) CountDatasets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDatasets", reflect.TypeOf((*MockInterface)(nil).CountDatasets), arg0, arg1)
}

// CountDeploymentRequests mocks base method.
func (m *MockInterface) CountDeploymentRequests(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDeploymentRequests", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDeploymentRequests indicates an expected call of CountDeploymentRequests.
func (mr *MockInterfaceMockRecorder) CountDeploymentRequests(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDeploymentRequests", reflect.TypeOf((*MockInterface)(nil).CountDeploymentRequests), arg0, arg1)
}

// CountEvaluationTasks mocks base method.
func (m *MockInterface) CountEvaluationTasks(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountEvaluationTasks", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountEvaluationTasks indicates an expected call of CountEvaluationTasks.
func (mr *MockInterfaceMockRecorder) CountEvaluationTasks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountEvaluationTasks", reflect.TypeOf((*MockInterface)(nil).CountEvaluationTasks), arg0, arg1)
}

// CountFaults mocks base method.
func (m *MockInterface) CountFaults(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFaults", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFaults indicates an expected call of CountFaults.
func (mr *MockInterfaceMockRecorder) CountFaults(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFaults", reflect.TypeOf((*MockInterface)(nil).CountFaults), arg0, arg1)
}

// CountJobs mocks base method.
func (m *MockInterface) CountJobs(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountJobs", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountJobs indicates an expected call of CountJobs.
func (mr *MockInterfaceMockRecorder) CountJobs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountJobs", reflect.TypeOf((*MockInterface)(nil).CountJobs), arg0, arg1)
}

// CountPlaygroundSessions mocks base method.
func (m *MockInterface) CountPlaygroundSessions(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPlaygroundSessions", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPlaygroundSessions indicates an expected call of CountPlaygroundSessions.
func (mr *MockInterfaceMockRecorder) CountPlaygroundSessions(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPlaygroundSessions", reflect.TypeOf((*MockInterface)(nil).CountPlaygroundSessions), arg0, arg1)
}

// CountPublicKeys mocks base method.
func (m *MockInterface) CountPublicKeys(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountPublicKeys", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountPublicKeys indicates an expected call of CountPublicKeys.
func (mr *MockInterfaceMockRecorder) CountPublicKeys(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountPublicKeys", reflect.TypeOf((*MockInterface)(nil).CountPublicKeys), arg0, arg1)
}

// CountWorkloads mocks base method.
func (m *MockInterface) CountWorkloads(arg0 context.Context, arg1 squirrel.Sqlizer) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountWorkloads", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountWorkloads indicates an expected call of CountWorkloads.
func (mr *MockInterfaceMockRecorder) CountWorkloads(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountWorkloads", reflect.TypeOf((*MockInterface)(nil).CountWorkloads), arg0, arg1)
}

// CreateDeploymentRequest mocks base method.
func (m *MockInterface) CreateDeploymentRequest(arg0 context.Context, arg1 *client.DeploymentRequest) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeploymentRequest", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeploymentRequest indicates an expected call of CreateDeploymentRequest.
func (mr *MockInterfaceMockRecorder) CreateDeploymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeploymentRequest", reflect.TypeOf((*MockInterface)(nil).CreateDeploymentRequest), arg0, arg1)
}

// CreateEmailOutbox mocks base method.
func (m *MockInterface) CreateEmailOutbox(arg0 context.Context, arg1 *model.EmailOutbox) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmailOutbox", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEmailOutbox indicates an expected call of CreateEmailOutbox.
func (mr *MockInterfaceMockRecorder) CreateEmailOutbox(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmailOutbox", reflect.TypeOf((*MockInterface)(nil).CreateEmailOutbox), arg0, arg1)
}

// CreateEnvironmentSnapshot mocks base method.
func (m *MockInterface) CreateEnvironmentSnapshot(arg0 context.Context, arg1 *client.EnvironmentSnapshot) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironmentSnapshot", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironmentSnapshot indicates an expected call of CreateEnvironmentSnapshot.
func (mr *MockInterfaceMockRecorder) CreateEnvironmentSnapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironmentSnapshot", reflect.TypeOf((*MockInterface)(nil).CreateEnvironmentSnapshot), arg0, arg1)
}

// CreateLLMBinding mocks base method.
func (m *MockInterface) CreateLLMBinding(arg0 context.Context, arg1 *client.LLMGatewayUserBinding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLLMBinding", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLLMBinding indicates an expected call of CreateLLMBinding.
func (mr *MockInterfaceMockRecorder) CreateLLMBinding(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLLMBinding", reflect.TypeOf((*MockInterface)(nil).CreateLLMBinding), arg0, arg1)
}

// CreateNodeStatistic mocks base method.
func (m *MockInterface) CreateNodeStatistic(arg0 context.Context, arg1 *model.NodeStatistic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNodeStatistic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateNodeStatistic indicates an expected call of CreateNodeStatistic.
func (mr *MockInterfaceMockRecorder) CreateNodeStatistic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNodeStatistic", reflect.TypeOf((*MockInterface)(nil).CreateNodeStatistic), arg0, arg1)
}

// CreateWorkloadStatistic mocks base method.
func (m *MockInterface) CreateWorkloadStatistic(arg0 context.Context, arg1 *model.WorkloadStatistic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWorkloadStatistic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWorkloadStatistic indicates an expected call of CreateWorkloadStatistic.
func (mr *MockInterfaceMockRecorder) CreateWorkloadStatistic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWorkloadStatistic", reflect.TypeOf((*MockInterface)(nil).CreateWorkloadStatistic), arg0, arg1)
}

// DeleteFault mocks base method.
func (m *MockInterface) DeleteFault(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFault", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFault indicates an expected call of DeleteFault.
func (mr *MockInterfaceMockRecorder) DeleteFault(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFault", reflect.TypeOf((*MockInterface)(nil).DeleteFault), arg0, arg1)
}

// DeleteImage mocks base method.
func (m *MockInterface) DeleteImage(arg0 context.Context, arg1 int32, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImage", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImage indicates an expected call of DeleteImage.
func (mr *MockInterfaceMockRecorder) DeleteImage(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImage", reflect.TypeOf((*MockInterface)(nil).DeleteImage), arg0, arg1, arg2)
}

// DeleteImageDigest mocks base method.
func (m *MockInterface) DeleteImageDigest(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteImageDigest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteImageDigest indicates an expected call of DeleteImageDigest.
func (mr *MockInterfaceMockRecorder) DeleteImageDigest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteImageDigest", reflect.TypeOf((*MockInterface)(nil).DeleteImageDigest), arg0, arg1)
}

// DeleteLLMBinding mocks base method.
func (m *MockInterface) DeleteLLMBinding(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLLMBinding", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLLMBinding indicates an expected call of DeleteLLMBinding.
func (mr *MockInterfaceMockRecorder) DeleteLLMBinding(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLLMBinding", reflect.TypeOf((*MockInterface)(nil).DeleteLLMBinding), arg0, arg1)
}

// DeleteModel mocks base method.
func (m *MockInterface) DeleteModel(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteModel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteModel indicates an expected call of DeleteModel.
func (mr *MockInterfaceMockRecorder) DeleteModel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteModel", reflect.TypeOf((*MockInterface)(nil).DeleteModel), arg0, arg1)
}

// DeleteNodeStatistic mocks base method.
func (m *MockInterface) DeleteNodeStatistic(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeStatistic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeStatistic indicates an expected call of DeleteNodeStatistic.
func (mr *MockInterfaceMockRecorder) DeleteNodeStatistic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeStatistic", reflect.TypeOf((*MockInterface)(nil).DeleteNodeStatistic), arg0, arg1)
}

// DeleteNodeStatisticByClusterAndNode mocks base method.
func (m *MockInterface) DeleteNodeStatisticByClusterAndNode(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeStatisticByClusterAndNode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeStatisticByClusterAndNode indicates an expected call of DeleteNodeStatisticByClusterAndNode.
func (mr *MockInterfaceMockRecorder) DeleteNodeStatisticByClusterAndNode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeStatisticByClusterAndNode", reflect.TypeOf((*MockInterface)(nil).DeleteNodeStatisticByClusterAndNode), arg0, arg1, arg2)
}

// DeleteNodeStatisticsByCluster mocks base method.
func (m *MockInterface) DeleteNodeStatisticsByCluster(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNodeStatisticsByCluster", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNodeStatisticsByCluster indicates an expected call of DeleteNodeStatisticsByCluster.
func (mr *MockInterfaceMockRecorder) DeleteNodeStatisticsByCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNodeStatisticsByCluster", reflect.TypeOf((*MockInterface)(nil).DeleteNodeStatisticsByCluster), arg0, arg1)
}

// DeletePublicKey mocks base method.
func (m *MockInterface) DeletePublicKey(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePublicKey", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePublicKey indicates an expected call of DeletePublicKey.
func (mr *MockInterfaceMockRecorder) DeletePublicKey(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePublicKey", reflect.TypeOf((*MockInterface)(nil).DeletePublicKey), arg0, arg1, arg2)
}

// DeleteRegistryInfo mocks base method.
func (m *MockInterface) DeleteRegistryInfo(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegistryInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegistryInfo indicates an expected call of DeleteRegistryInfo.
func (mr *MockInterfaceMockRecorder) DeleteRegistryInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegistryInfo", reflect.TypeOf((*MockInterface)(nil).DeleteRegistryInfo), arg0, arg1)
}

// DeleteWorkloadStatistic mocks base method.
func (m *MockInterface) DeleteWorkloadStatistic(arg0 context.Context, arg1 int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkloadStatistic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkloadStatistic indicates an expected call of DeleteWorkloadStatistic.
func (mr *MockInterfaceMockRecorder) DeleteWorkloadStatistic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkloadStatistic", reflect.TypeOf((*MockInterface)(nil).DeleteWorkloadStatistic), arg0, arg1)
}

// DeleteWorkloadStatisticsByWorkloadID mocks base method.
func (m *MockInterface) DeleteWorkloadStatisticsByWorkloadID(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWorkloadStatisticsByWorkloadID", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWorkloadStatisticsByWorkloadID indicates an expected call of DeleteWorkloadStatisticsByWorkloadID.
func (mr *MockInterfaceMockRecorder) DeleteWorkloadStatisticsByWorkloadID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWorkloadStatisticsByWorkloadID", reflect.TypeOf((*MockInterface)(nil).DeleteWorkloadStatisticsByWorkloadID), arg0, arg1)
}

// FailEmailOutbox mocks base method.
func (m *MockInterface) FailEmailOutbox(arg0 context.Context, arg1 int32, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FailEmailOutbox", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// FailEmailOutbox indicates an expected call of FailEmailOutbox.
func (mr *MockInterfaceMockRecorder) FailEmailOutbox(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FailEmailOutbox", reflect.TypeOf((*MockInterface)(nil).FailEmailOutbox), arg0, arg1, arg2)
}

// GetApiKeyById mocks base method.
func (m *MockInterface) GetApiKeyById(arg0 context.Context, arg1 int64) (*client.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeyById", arg0, arg1)
	ret0, _ := ret[0].(*client.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeyById indicates an expected call of GetApiKeyById.
func (mr *MockInterfaceMockRecorder) GetApiKeyById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeyById", reflect.TypeOf((*MockInterface)(nil).GetApiKeyById), arg0, arg1)
}

// GetApiKeyByKey mocks base method.
func (m *MockInterface) GetApiKeyByKey(arg0 context.Context, arg1 string) (*client.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiKeyByKey", arg0, arg1)
	ret0, _ := ret[0].(*client.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiKeyByKey indicates an expected call of GetApiKeyByKey.
func (mr *MockInterfaceMockRecorder) GetApiKeyByKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiKeyByKey", reflect.TypeOf((*MockInterface)(nil).GetApiKeyByKey), arg0, arg1)
}

// GetDataset mocks base method.
func (m *MockInterface) GetDataset(arg0 context.Context, arg1 string) (*client.Dataset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDataset", arg0, arg1)
	ret0, _ := ret[0].(*client.Dataset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDataset indicates an expected call of GetDataset.
func (mr *MockInterfaceMockRecorder) GetDataset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDataset", reflect.TypeOf((*MockInterface)(nil).GetDataset), arg0, arg1)
}

// GetDefaultRegistryInfo mocks base method.
func (m *MockInterface) GetDefaultRegistryInfo(arg0 context.Context) (*model.RegistryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultRegistryInfo", arg0)
	ret0, _ := ret[0].(*model.RegistryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultRegistryInfo indicates an expected call of GetDefaultRegistryInfo.
func (mr *MockInterfaceMockRecorder) GetDefaultRegistryInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultRegistryInfo", reflect.TypeOf((*MockInterface)(nil).GetDefaultRegistryInfo), arg0)
}

// GetDeploymentRequest mocks base method.
func (m *MockInterface) GetDeploymentRequest(arg0 context.Context, arg1 int64) (*client.DeploymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeploymentRequest", arg0, arg1)
	ret0, _ := ret[0].(*client.DeploymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeploymentRequest indicates an expected call of GetDeploymentRequest.
func (mr *MockInterfaceMockRecorder) GetDeploymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeploymentRequest", reflect.TypeOf((*MockInterface)(nil).GetDeploymentRequest), arg0, arg1)
}

// GetEmailOutbox mocks base method.
func (m *MockInterface) GetEmailOutbox(arg0 context.Context, arg1 int32) (*model.EmailOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmailOutbox", arg0, arg1)
	ret0, _ := ret[0].(*model.EmailOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmailOutbox indicates an expected call of GetEmailOutbox.
func (mr *MockInterfaceMockRecorder) GetEmailOutbox(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmailOutbox", reflect.TypeOf((*MockInterface)(nil).GetEmailOutbox), arg0, arg1)
}

// GetEnvironmentSnapshot mocks base method.
func (m *MockInterface) GetEnvironmentSnapshot(arg0 context.Context, arg1 int64) (*client.EnvironmentSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironmentSnapshot", arg0, arg1)
	ret0, _ := ret[0].(*client.EnvironmentSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironmentSnapshot indicates an expected call of GetEnvironmentSnapshot.
func (mr *MockInterfaceMockRecorder) GetEnvironmentSnapshot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironmentSnapshot", reflect.TypeOf((*MockInterface)(nil).GetEnvironmentSnapshot), arg0, arg1)
}

// GetEnvironmentSnapshotByRequestId mocks base method.
func (m *MockInterface) GetEnvironmentSnapshotByRequestId(arg0 context.Context, arg1 int64) (*client.EnvironmentSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironmentSnapshotByRequestId", arg0, arg1)
	ret0, _ := ret[0].(*client.EnvironmentSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironmentSnapshotByRequestId indicates an expected call of GetEnvironmentSnapshotByRequestId.
func (mr *MockInterfaceMockRecorder) GetEnvironmentSnapshotByRequestId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironmentSnapshotByRequestId", reflect.TypeOf((*MockInterface)(nil).GetEnvironmentSnapshotByRequestId), arg0, arg1)
}

// GetEvaluationTask mocks base method.
func (m *MockInterface) GetEvaluationTask(arg0 context.Context, arg1 string) (*client.EvaluationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvaluationTask", arg0, arg1)
	ret0, _ := ret[0].(*client.EvaluationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvaluationTask indicates an expected call of GetEvaluationTask.
func (mr *MockInterfaceMockRecorder) GetEvaluationTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvaluationTask", reflect.TypeOf((*MockInterface)(nil).GetEvaluationTask), arg0, arg1)
}

// GetFault mocks base method.
func (m *MockInterface) GetFault(arg0 context.Context, arg1 string) (*client.Fault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFault", arg0, arg1)
	ret0, _ := ret[0].(*client.Fault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFault indicates an expected call of GetFault.
func (mr *MockInterfaceMockRecorder) GetFault(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFault", reflect.TypeOf((*MockInterface)(nil).GetFault), arg0, arg1)
}

// GetImage mocks base method.
func (m *MockInterface) GetImage(arg0 context.Context, arg1 int32) (*model.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImage", arg0, arg1)
	ret0, _ := ret[0].(*model.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImage indicates an expected call of GetImage.
func (mr *MockInterfaceMockRecorder) GetImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImage", reflect.TypeOf((*MockInterface)(nil).GetImage), arg0, arg1)
}

// GetImageByTag mocks base method.
func (m *MockInterface) GetImageByTag(arg0 context.Context, arg1 string) (*model.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageByTag", arg0, arg1)
	ret0, _ := ret[0].(*model.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageByTag indicates an expected call of GetImageByTag.
func (mr *MockInterfaceMockRecorder) GetImageByTag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageByTag", reflect.TypeOf((*MockInterface)(nil).GetImageByTag), arg0, arg1)
}

// GetImageImportJobByJobName mocks base method.
func (m *MockInterface) GetImageImportJobByJobName(arg0 context.Context, arg1 string) (*model.ImageImportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageImportJobByJobName", arg0, arg1)
	ret0, _ := ret[0].(*model.ImageImportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageImportJobByJobName indicates an expected call of GetImageImportJobByJobName.
func (mr *MockInterfaceMockRecorder) GetImageImportJobByJobName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageImportJobByJobName", reflect.TypeOf((*MockInterface)(nil).GetImageImportJobByJobName), arg0, arg1)
}

// GetImageImportJobByTag mocks base method.
func (m *MockInterface) GetImageImportJobByTag(arg0 context.Context, arg1 string) (*model.ImageImportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageImportJobByTag", arg0, arg1)
	ret0, _ := ret[0].(*model.ImageImportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImageImportJobByTag indicates an expected call of GetImageImportJobByTag.
func (mr *MockInterfaceMockRecorder) GetImageImportJobByTag(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageImportJobByTag", reflect.TypeOf((*MockInterface)(nil).GetImageImportJobByTag), arg0, arg1)
}

// GetImportImageByImageID mocks base method.
func (m *MockInterface) GetImportImageByImageID(arg0 context.Context, arg1 int32) (*model.ImageImportJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImportImageByImageID", arg0, arg1)
	ret0, _ := ret[0].(*model.ImageImportJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImportImageByImageID indicates an expected call of GetImportImageByImageID.
func (mr *MockInterfaceMockRecorder) GetImportImageByImageID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImportImageByImageID", reflect.TypeOf((*MockInterface)(nil).GetImportImageByImageID), arg0, arg1)
}

// GetLLMBindingByApimKeyHash mocks base method.
func (m *MockInterface) GetLLMBindingByApimKeyHash(arg0 context.Context, arg1 string) (*client.LLMGatewayUserBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLLMBindingByApimKeyHash", arg0, arg1)
	ret0, _ := ret[0].(*client.LLMGatewayUserBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLLMBindingByApimKeyHash indicates an expected call of GetLLMBindingByApimKeyHash.
func (mr *MockInterfaceMockRecorder) GetLLMBindingByApimKeyHash(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLLMBindingByApimKeyHash", reflect.TypeOf((*MockInterface)(nil).GetLLMBindingByApimKeyHash), arg0, arg1)
}

// GetLLMBindingByEmail mocks base method.
func (m *MockInterface) GetLLMBindingByEmail(arg0 context.Context, arg1 string) (*client.LLMGatewayUserBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLLMBindingByEmail", arg0, arg1)
	ret0, _ := ret[0].(*client.LLMGatewayUserBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLLMBindingByEmail indicates an expected call of GetLLMBindingByEmail.
func (mr *MockInterfaceMockRecorder) GetLLMBindingByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLLMBindingByEmail", reflect.TypeOf((*MockInterface)(nil).GetLLMBindingByEmail), arg0, arg1)
}

// GetModelByID mocks base method.
func (m *MockInterface) GetModelByID(arg0 context.Context, arg1 string) (*client.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByID", arg0, arg1)
	ret0, _ := ret[0].(*client.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelByID indicates an expected call of GetModelByID.
func (mr *MockInterfaceMockRecorder) GetModelByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByID", reflect.TypeOf((*MockInterface)(nil).GetModelByID), arg0, arg1)
}

// GetModelByModelName mocks base method.
func (m *MockInterface) GetModelByModelName(arg0 context.Context, arg1 string) (*client.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelByModelName", arg0, arg1)
	ret0, _ := ret[0].(*client.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelByModelName indicates an expected call of GetModelByModelName.
func (mr *MockInterfaceMockRecorder) GetModelByModelName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelByModelName", reflect.TypeOf((*MockInterface)(nil).GetModelByModelName), arg0, arg1)
}

// GetNodeGpuUtilizationMap mocks base method.
func (m *MockInterface) GetNodeGpuUtilizationMap(arg0 context.Context, arg1 string, arg2 []string) (map[string]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeGpuUtilizationMap", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeGpuUtilizationMap indicates an expected call of GetNodeGpuUtilizationMap.
func (mr *MockInterfaceMockRecorder) GetNodeGpuUtilizationMap(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeGpuUtilizationMap", reflect.TypeOf((*MockInterface)(nil).GetNodeGpuUtilizationMap), arg0, arg1, arg2)
}

// GetNodeStatisticByClusterAndNode mocks base method.
func (m *MockInterface) GetNodeStatisticByClusterAndNode(arg0 context.Context, arg1, arg2 string) (*model.NodeStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeStatisticByClusterAndNode", arg0, arg1, arg2)
	ret0, _ := ret[0].(*model.NodeStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeStatisticByClusterAndNode indicates an expected call of GetNodeStatisticByClusterAndNode.
func (mr *MockInterfaceMockRecorder) GetNodeStatisticByClusterAndNode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeStatisticByClusterAndNode", reflect.TypeOf((*MockInterface)(nil).GetNodeStatisticByClusterAndNode), arg0, arg1, arg2)
}

// GetNodeStatisticByID mocks base method.
func (m *MockInterface) GetNodeStatisticByID(arg0 context.Context, arg1 int32) (*model.NodeStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeStatisticByID", arg0, arg1)
	ret0, _ := ret[0].(*model.NodeStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeStatisticByID indicates an expected call of GetNodeStatisticByID.
func (mr *MockInterfaceMockRecorder) GetNodeStatisticByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeStatisticByID", reflect.TypeOf((*MockInterface)(nil).GetNodeStatisticByID), arg0, arg1)
}

// GetNodeStatisticsByCluster mocks base method.
func (m *MockInterface) GetNodeStatisticsByCluster(arg0 context.Context, arg1 string) ([]*model.NodeStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeStatisticsByCluster", arg0, arg1)
	ret0, _ := ret[0].([]*model.NodeStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeStatisticsByCluster indicates an expected call of GetNodeStatisticsByCluster.
func (mr *MockInterfaceMockRecorder) GetNodeStatisticsByCluster(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeStatisticsByCluster", reflect.TypeOf((*MockInterface)(nil).GetNodeStatisticsByCluster), arg0, arg1)
}

// GetNodeStatisticsByNodeNames mocks base method.
func (m *MockInterface) GetNodeStatisticsByNodeNames(arg0 context.Context, arg1 string, arg2 []string) ([]*model.NodeStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeStatisticsByNodeNames", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.NodeStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeStatisticsByNodeNames indicates an expected call of GetNodeStatisticsByNodeNames.
func (mr *MockInterfaceMockRecorder) GetNodeStatisticsByNodeNames(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeStatisticsByNodeNames", reflect.TypeOf((*MockInterface)(nil).GetNodeStatisticsByNodeNames), arg0, arg1, arg2)
}

// GetOpsJob mocks base method.
func (m *MockInterface) GetOpsJob(arg0 context.Context, arg1 string) (*client.OpsJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpsJob", arg0, arg1)
	ret0, _ := ret[0].(*client.OpsJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpsJob indicates an expected call of GetOpsJob.
func (mr *MockInterfaceMockRecorder) GetOpsJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpsJob", reflect.TypeOf((*MockInterface)(nil).GetOpsJob), arg0, arg1)
}

// GetPlaygroundSession mocks base method.
func (m *MockInterface) GetPlaygroundSession(arg0 context.Context, arg1 int64) (*client.PlaygroundSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlaygroundSession", arg0, arg1)
	ret0, _ := ret[0].(*client.PlaygroundSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlaygroundSession indicates an expected call of GetPlaygroundSession.
func (mr *MockInterfaceMockRecorder) GetPlaygroundSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlaygroundSession", reflect.TypeOf((*MockInterface)(nil).GetPlaygroundSession), arg0, arg1)
}

// GetPublicKeyByUserId mocks base method.
func (m *MockInterface) GetPublicKeyByUserId(arg0 context.Context, arg1 string) ([]*client.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKeyByUserId", arg0, arg1)
	ret0, _ := ret[0].([]*client.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicKeyByUserId indicates an expected call of GetPublicKeyByUserId.
func (mr *MockInterfaceMockRecorder) GetPublicKeyByUserId(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKeyByUserId", reflect.TypeOf((*MockInterface)(nil).GetPublicKeyByUserId), arg0, arg1)
}

// GetRegistryInfoById mocks base method.
func (m *MockInterface) GetRegistryInfoById(arg0 context.Context, arg1 int32) (*model.RegistryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistryInfoById", arg0, arg1)
	ret0, _ := ret[0].(*model.RegistryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistryInfoById indicates an expected call of GetRegistryInfoById.
func (mr *MockInterfaceMockRecorder) GetRegistryInfoById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistryInfoById", reflect.TypeOf((*MockInterface)(nil).GetRegistryInfoById), arg0, arg1)
}

// GetRegistryInfoByUrl mocks base method.
func (m *MockInterface) GetRegistryInfoByUrl(arg0 context.Context, arg1 string) (*model.RegistryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistryInfoByUrl", arg0, arg1)
	ret0, _ := ret[0].(*model.RegistryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistryInfoByUrl indicates an expected call of GetRegistryInfoByUrl.
func (mr *MockInterfaceMockRecorder) GetRegistryInfoByUrl(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistryInfoByUrl", reflect.TypeOf((*MockInterface)(nil).GetRegistryInfoByUrl), arg0, arg1)
}

// GetWorkload mocks base method.
func (m *MockInterface) GetWorkload(arg0 context.Context, arg1 string) (*client.Workload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkload", arg0, arg1)
	ret0, _ := ret[0].(*client.Workload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkload indicates an expected call of GetWorkload.
func (mr *MockInterfaceMockRecorder) GetWorkload(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkload", reflect.TypeOf((*MockInterface)(nil).GetWorkload), arg0, arg1)
}

// GetWorkloadStatisticByID mocks base method.
func (m *MockInterface) GetWorkloadStatisticByID(arg0 context.Context, arg1 int32) (*model.WorkloadStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadStatisticByID", arg0, arg1)
	ret0, _ := ret[0].(*model.WorkloadStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadStatisticByID indicates an expected call of GetWorkloadStatisticByID.
func (mr *MockInterfaceMockRecorder) GetWorkloadStatisticByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadStatisticByID", reflect.TypeOf((*MockInterface)(nil).GetWorkloadStatisticByID), arg0, arg1)
}

// GetWorkloadStatisticByWorkloadID mocks base method.
func (m *MockInterface) GetWorkloadStatisticByWorkloadID(arg0 context.Context, arg1 string) (*model.WorkloadStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadStatisticByWorkloadID", arg0, arg1)
	ret0, _ := ret[0].(*model.WorkloadStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadStatisticByWorkloadID indicates an expected call of GetWorkloadStatisticByWorkloadID.
func (mr *MockInterfaceMockRecorder) GetWorkloadStatisticByWorkloadID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadStatisticByWorkloadID", reflect.TypeOf((*MockInterface)(nil).GetWorkloadStatisticByWorkloadID), arg0, arg1)
}

// GetWorkloadStatisticByWorkloadUID mocks base method.
func (m *MockInterface) GetWorkloadStatisticByWorkloadUID(arg0 context.Context, arg1 string) (*model.WorkloadStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadStatisticByWorkloadUID", arg0, arg1)
	ret0, _ := ret[0].(*model.WorkloadStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadStatisticByWorkloadUID indicates an expected call of GetWorkloadStatisticByWorkloadUID.
func (mr *MockInterfaceMockRecorder) GetWorkloadStatisticByWorkloadUID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadStatisticByWorkloadUID", reflect.TypeOf((*MockInterface)(nil).GetWorkloadStatisticByWorkloadUID), arg0, arg1)
}

// GetWorkloadStatisticsByClusterAndWorkspace mocks base method.
func (m *MockInterface) GetWorkloadStatisticsByClusterAndWorkspace(arg0 context.Context, arg1, arg2 string) ([]*model.WorkloadStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadStatisticsByClusterAndWorkspace", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.WorkloadStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadStatisticsByClusterAndWorkspace indicates an expected call of GetWorkloadStatisticsByClusterAndWorkspace.
func (mr *MockInterfaceMockRecorder) GetWorkloadStatisticsByClusterAndWorkspace(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadStatisticsByClusterAndWorkspace", reflect.TypeOf((*MockInterface)(nil).GetWorkloadStatisticsByClusterAndWorkspace), arg0, arg1, arg2)
}

// GetWorkloadStatisticsByType mocks base method.
func (m *MockInterface) GetWorkloadStatisticsByType(arg0 context.Context, arg1 string) ([]*model.WorkloadStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadStatisticsByType", arg0, arg1)
	ret0, _ := ret[0].([]*model.WorkloadStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadStatisticsByType indicates an expected call of GetWorkloadStatisticsByType.
func (mr *MockInterfaceMockRecorder) GetWorkloadStatisticsByType(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadStatisticsByType", reflect.TypeOf((*MockInterface)(nil).GetWorkloadStatisticsByType), arg0, arg1)
}

// GetWorkloadStatisticsByWorkloadID mocks base method.
func (m *MockInterface) GetWorkloadStatisticsByWorkloadID(arg0 context.Context, arg1 string) ([]*model.WorkloadStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadStatisticsByWorkloadID", arg0, arg1)
	ret0, _ := ret[0].([]*model.WorkloadStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadStatisticsByWorkloadID indicates an expected call of GetWorkloadStatisticsByWorkloadID.
func (mr *MockInterfaceMockRecorder) GetWorkloadStatisticsByWorkloadID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadStatisticsByWorkloadID", reflect.TypeOf((*MockInterface)(nil).GetWorkloadStatisticsByWorkloadID), arg0, arg1)
}

// GetWorkloadStatisticsByWorkloadUID mocks base method.
func (m *MockInterface) GetWorkloadStatisticsByWorkloadUID(arg0 context.Context, arg1 string) ([]*model.WorkloadStatistic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkloadStatisticsByWorkloadUID", arg0, arg1)
	ret0, _ := ret[0].([]*model.WorkloadStatistic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkloadStatisticsByWorkloadUID indicates an expected call of GetWorkloadStatisticsByWorkloadUID.
func (mr *MockInterfaceMockRecorder) GetWorkloadStatisticsByWorkloadUID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkloadStatisticsByWorkloadUID", reflect.TypeOf((*MockInterface)(nil).GetWorkloadStatisticsByWorkloadUID), arg0, arg1)
}

// InsertApiKey mocks base method.
func (m *MockInterface) InsertApiKey(arg0 context.Context, arg1 *client.ApiKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertApiKey", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertApiKey indicates an expected call of InsertApiKey.
func (mr *MockInterfaceMockRecorder) InsertApiKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertApiKey", reflect.TypeOf((*MockInterface)(nil).InsertApiKey), arg0, arg1)
}

// InsertAuditLog mocks base method.
func (m *MockInterface) InsertAuditLog(arg0 context.Context, arg1 *client.AuditLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAuditLog", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAuditLog indicates an expected call of InsertAuditLog.
func (mr *MockInterfaceMockRecorder) InsertAuditLog(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAuditLog", reflect.TypeOf((*MockInterface)(nil).InsertAuditLog), arg0, arg1)
}

// InsertPlaygroundSession mocks base method.
func (m *MockInterface) InsertPlaygroundSession(arg0 context.Context, arg1 *client.PlaygroundSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPlaygroundSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPlaygroundSession indicates an expected call of InsertPlaygroundSession.
func (mr *MockInterfaceMockRecorder) InsertPlaygroundSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPlaygroundSession", reflect.TypeOf((*MockInterface)(nil).InsertPlaygroundSession), arg0, arg1)
}

// InsertPublicKey mocks base method.
func (m *MockInterface) InsertPublicKey(arg0 context.Context, arg1 *client.PublicKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertPublicKey", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertPublicKey indicates an expected call of InsertPublicKey.
func (mr *MockInterfaceMockRecorder) InsertPublicKey(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertPublicKey", reflect.TypeOf((*MockInterface)(nil).InsertPublicKey), arg0, arg1)
}

// InsertSshSessionRecord mocks base method.
func (m *MockInterface) InsertSshSessionRecord(arg0 context.Context, arg1 *client.SshSessionRecords) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertSshSessionRecord", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertSshSessionRecord indicates an expected call of InsertSshSessionRecord.
func (mr *MockInterfaceMockRecorder) InsertSshSessionRecord(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertSshSessionRecord", reflect.TypeOf((*MockInterface)(nil).InsertSshSessionRecord), arg0, arg1)
}

// ListDeploymentRequests mocks base method.
func (m *MockInterface) ListDeploymentRequests(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.DeploymentRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeploymentRequests", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.DeploymentRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeploymentRequests indicates an expected call of ListDeploymentRequests.
func (mr *MockInterfaceMockRecorder) ListDeploymentRequests(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeploymentRequests", reflect.TypeOf((*MockInterface)(nil).ListDeploymentRequests), arg0, arg1, arg2, arg3, arg4)
}

// ListEnvironmentSnapshots mocks base method.
func (m *MockInterface) ListEnvironmentSnapshots(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.EnvironmentSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEnvironmentSnapshots", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.EnvironmentSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEnvironmentSnapshots indicates an expected call of ListEnvironmentSnapshots.
func (mr *MockInterfaceMockRecorder) ListEnvironmentSnapshots(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEnvironmentSnapshots", reflect.TypeOf((*MockInterface)(nil).ListEnvironmentSnapshots), arg0, arg1, arg2, arg3, arg4)
}

// ListLLMBindings mocks base method.
func (m *MockInterface) ListLLMBindings(arg0 context.Context, arg1, arg2 int) ([]*client.LLMGatewayUserBinding, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLLMBindings", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*client.LLMGatewayUserBinding)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLLMBindings indicates an expected call of ListLLMBindings.
func (mr *MockInterfaceMockRecorder) ListLLMBindings(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLLMBindings", reflect.TypeOf((*MockInterface)(nil).ListLLMBindings), arg0, arg1, arg2)
}

// ListModels mocks base method.
func (m *MockInterface) ListModels(arg0 context.Context, arg1, arg2 string, arg3 bool) ([]*client.Model, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListModels", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*client.Model)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListModels indicates an expected call of ListModels.
func (mr *MockInterfaceMockRecorder) ListModels(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListModels", reflect.TypeOf((*MockInterface)(nil).ListModels), arg0, arg1, arg2, arg3)
}

// ListPendingEmailOutbox mocks base method.
func (m *MockInterface) ListPendingEmailOutbox(arg0 context.Context, arg1 int) ([]*model.EmailOutbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingEmailOutbox", arg0, arg1)
	ret0, _ := ret[0].([]*model.EmailOutbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingEmailOutbox indicates an expected call of ListPendingEmailOutbox.
func (mr *MockInterfaceMockRecorder) ListPendingEmailOutbox(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingEmailOutbox", reflect.TypeOf((*MockInterface)(nil).ListPendingEmailOutbox), arg0, arg1)
}

// ListRegistryInfos mocks base method.
func (m *MockInterface) ListRegistryInfos(arg0 context.Context, arg1, arg2 int) ([]*model.RegistryInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegistryInfos", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*model.RegistryInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegistryInfos indicates an expected call of ListRegistryInfos.
func (mr *MockInterfaceMockRecorder) ListRegistryInfos(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegistryInfos", reflect.TypeOf((*MockInterface)(nil).ListRegistryInfos), arg0, arg1, arg2)
}

// ListUnprocessedNotifications mocks base method.
func (m *MockInterface) ListUnprocessedNotifications(arg0 context.Context) ([]*model.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnprocessedNotifications", arg0)
	ret0, _ := ret[0].([]*model.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnprocessedNotifications indicates an expected call of ListUnprocessedNotifications.
func (mr *MockInterfaceMockRecorder) ListUnprocessedNotifications(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnprocessedNotifications", reflect.TypeOf((*MockInterface)(nil).ListUnprocessedNotifications), arg0)
}

// SelectApiKeys mocks base method.
func (m *MockInterface) SelectApiKeys(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.ApiKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectApiKeys", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.ApiKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectApiKeys indicates an expected call of SelectApiKeys.
func (mr *MockInterfaceMockRecorder) SelectApiKeys(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectApiKeys", reflect.TypeOf((*MockInterface)(nil).SelectApiKeys), arg0, arg1, arg2, arg3, arg4)
}

// SelectAuditLogs mocks base method.
func (m *MockInterface) SelectAuditLogs(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.AuditLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAuditLogs", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.AuditLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAuditLogs indicates an expected call of SelectAuditLogs.
func (mr *MockInterfaceMockRecorder) SelectAuditLogs(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAuditLogs", reflect.TypeOf((*MockInterface)(nil).SelectAuditLogs), arg0, arg1, arg2, arg3, arg4)
}

// SelectDatasets mocks base method.
func (m *MockInterface) SelectDatasets(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.Dataset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectDatasets", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.Dataset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectDatasets indicates an expected call of SelectDatasets.
func (mr *MockInterfaceMockRecorder) SelectDatasets(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectDatasets", reflect.TypeOf((*MockInterface)(nil).SelectDatasets), arg0, arg1, arg2, arg3, arg4)
}

// SelectEvaluationTasks mocks base method.
func (m *MockInterface) SelectEvaluationTasks(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.EvaluationTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectEvaluationTasks", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.EvaluationTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectEvaluationTasks indicates an expected call of SelectEvaluationTasks.
func (mr *MockInterfaceMockRecorder) SelectEvaluationTasks(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectEvaluationTasks", reflect.TypeOf((*MockInterface)(nil).SelectEvaluationTasks), arg0, arg1, arg2, arg3, arg4)
}

// SelectFaults mocks base method.
func (m *MockInterface) SelectFaults(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.Fault, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectFaults", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.Fault)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectFaults indicates an expected call of SelectFaults.
func (mr *MockInterfaceMockRecorder) SelectFaults(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectFaults", reflect.TypeOf((*MockInterface)(nil).SelectFaults), arg0, arg1, arg2, arg3, arg4)
}

// SelectImages mocks base method.
func (m *MockInterface) SelectImages(arg0 context.Context, arg1 *client.ImageFilter) ([]*model.Image, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectImages", arg0, arg1)
	ret0, _ := ret[0].([]*model.Image)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SelectImages indicates an expected call of SelectImages.
func (mr *MockInterfaceMockRecorder) SelectImages(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectImages", reflect.TypeOf((*MockInterface)(nil).SelectImages), arg0, arg1)
}

// SelectJobs mocks base method.
func (m *MockInterface) SelectJobs(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.OpsJob, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectJobs", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.OpsJob)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectJobs indicates an expected call of SelectJobs.
func (mr *MockInterfaceMockRecorder) SelectJobs(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectJobs", reflect.TypeOf((*MockInterface)(nil).SelectJobs), arg0, arg1, arg2, arg3, arg4)
}

// SelectPlaygroundSessions mocks base method.
func (m *MockInterface) SelectPlaygroundSessions(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.PlaygroundSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPlaygroundSessions", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.PlaygroundSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPlaygroundSessions indicates an expected call of SelectPlaygroundSessions.
func (mr *MockInterfaceMockRecorder) SelectPlaygroundSessions(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPlaygroundSessions", reflect.TypeOf((*MockInterface)(nil).SelectPlaygroundSessions), arg0, arg1, arg2, arg3, arg4)
}

// SelectPublicKeys mocks base method.
func (m *MockInterface) SelectPublicKeys(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPublicKeys", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPublicKeys indicates an expected call of SelectPublicKeys.
func (mr *MockInterfaceMockRecorder) SelectPublicKeys(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPublicKeys", reflect.TypeOf((*MockInterface)(nil).SelectPublicKeys), arg0, arg1, arg2, arg3, arg4)
}

// SelectUserTokens mocks base method.
func (m *MockInterface) SelectUserTokens(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.UserToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUserTokens", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.UserToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserTokens indicates an expected call of SelectUserTokens.
func (mr *MockInterfaceMockRecorder) SelectUserTokens(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUserTokens", reflect.TypeOf((*MockInterface)(nil).SelectUserTokens), arg0, arg1, arg2, arg3, arg4)
}

// SelectWorkloads mocks base method.
func (m *MockInterface) SelectWorkloads(arg0 context.Context, arg1 squirrel.Sqlizer, arg2 []string, arg3, arg4 int) ([]*client.Workload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectWorkloads", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*client.Workload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectWorkloads indicates an expected call of SelectWorkloads.
func (mr *MockInterfaceMockRecorder) SelectWorkloads(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectWorkloads", reflect.TypeOf((*MockInterface)(nil).SelectWorkloads), arg0, arg1, arg2, arg3, arg4)
}

// SetApiKeyDeleted mocks base method.
func (m *MockInterface) SetApiKeyDeleted(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetApiKeyDeleted", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetApiKeyDeleted indicates an expected call of SetApiKeyDeleted.
func (mr *MockInterfaceMockRecorder) SetApiKeyDeleted(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetApiKeyDeleted", reflect.TypeOf((*MockInterface)(nil).SetApiKeyDeleted), arg0, arg1, arg2)
}

// SetDatasetDeleted mocks base method.
func (m *MockInterface) SetDatasetDeleted(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDatasetDeleted", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDatasetDeleted indicates an expected call of SetDatasetDeleted.
func (mr *MockInterfaceMockRecorder) SetDatasetDeleted(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDatasetDeleted", reflect.TypeOf((*MockInterface)(nil).SetDatasetDeleted), arg0, arg1)
}

// SetEvaluationTaskDeleted mocks base method.
func (m *MockInterface) SetEvaluationTaskDeleted(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEvaluationTaskDeleted", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEvaluationTaskDeleted indicates an expected call of SetEvaluationTaskDeleted.
func (mr *MockInterfaceMockRecorder) SetEvaluationTaskDeleted(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEvaluationTaskDeleted", reflect.TypeOf((*MockInterface)(nil).SetEvaluationTaskDeleted), arg0, arg1)
}

// SetEvaluationTaskFailed mocks base method.
func (m *MockInterface) SetEvaluationTaskFailed(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEvaluationTaskFailed", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetEvaluationTaskFailed indicates an expected call of SetEvaluationTaskFailed.
func (mr *MockInterfaceMockRecorder) SetEvaluationTaskFailed(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEvaluationTaskFailed", reflect.TypeOf((*MockInterface)(nil).SetEvaluationTaskFailed), arg0, arg1, arg2)
}

// SetOpsJobDeleted mocks base method.
func (m *MockInterface) SetOpsJobDeleted(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOpsJobDeleted", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOpsJobDeleted indicates an expected call of SetOpsJobDeleted.
func (mr *MockInterfaceMockRecorder) SetOpsJobDeleted(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOpsJobDeleted", reflect.TypeOf((*MockInterface)(nil).SetOpsJobDeleted), arg0, arg1)
}

// SetPlaygroundSessionDeleted mocks base method.
func (m *MockInterface) SetPlaygroundSessionDeleted(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPlaygroundSessionDeleted", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPlaygroundSessionDeleted indicates an expected call of SetPlaygroundSessionDeleted.
func (mr *MockInterfaceMockRecorder) SetPlaygroundSessionDeleted(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPlaygroundSessionDeleted", reflect.TypeOf((*MockInterface)(nil).SetPlaygroundSessionDeleted), arg0, arg1)
}

// SetPublicKeyDescription mocks base method.
func (m *MockInterface) SetPublicKeyDescription(arg0 context.Context, arg1 string, arg2 int64, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublicKeyDescription", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPublicKeyDescription indicates an expected call of SetPublicKeyDescription.
func (mr *MockInterfaceMockRecorder) SetPublicKeyDescription(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublicKeyDescription", reflect.TypeOf((*MockInterface)(nil).SetPublicKeyDescription), arg0, arg1, arg2, arg3)
}

// SetPublicKeyStatus mocks base method.
func (m *MockInterface) SetPublicKeyStatus(arg0 context.Context, arg1 string, arg2 int64, arg3 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPublicKeyStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPublicKeyStatus indicates an expected call of SetPublicKeyStatus.
func (mr *MockInterfaceMockRecorder) SetPublicKeyStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPublicKeyStatus", reflect.TypeOf((*MockInterface)(nil).SetPublicKeyStatus), arg0, arg1, arg2, arg3)
}

// SetSshDisconnect mocks base method.
func (m *MockInterface) SetSshDisconnect(arg0 context.Context, arg1 int64, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSshDisconnect", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSshDisconnect indicates an expected call of SetSshDisconnect.
func (mr *MockInterfaceMockRecorder) SetSshDisconnect(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSshDisconnect", reflect.TypeOf((*MockInterface)(nil).SetSshDisconnect), arg0, arg1, arg2)
}

// SetWorkloadDeleted mocks base method.
func (m *MockInterface) SetWorkloadDeleted(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkloadDeleted", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkloadDeleted indicates an expected call of SetWorkloadDeleted.
func (mr *MockInterfaceMockRecorder) SetWorkloadDeleted(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkloadDeleted", reflect.TypeOf((*MockInterface)(nil).SetWorkloadDeleted), arg0, arg1)
}

// SetWorkloadDescription mocks base method.
func (m *MockInterface) SetWorkloadDescription(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkloadDescription", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkloadDescription indicates an expected call of SetWorkloadDescription.
func (mr *MockInterfaceMockRecorder) SetWorkloadDescription(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkloadDescription", reflect.TypeOf((*MockInterface)(nil).SetWorkloadDescription), arg0, arg1, arg2)
}

// SetWorkloadStopped mocks base method.
func (m *MockInterface) SetWorkloadStopped(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWorkloadStopped", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWorkloadStopped indicates an expected call of SetWorkloadStopped.
func (mr *MockInterfaceMockRecorder) SetWorkloadStopped(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkloadStopped", reflect.TypeOf((*MockInterface)(nil).SetWorkloadStopped), arg0, arg1)
}

// SubmitNotification mocks base method.
func (m *MockInterface) SubmitNotification(arg0 context.Context, arg1 *model.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitNotification indicates an expected call of SubmitNotification.
func (mr *MockInterfaceMockRecorder) SubmitNotification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitNotification", reflect.TypeOf((*MockInterface)(nil).SubmitNotification), arg0, arg1)
}

// UpdateDatasetFileInfo mocks base method.
func (m *MockInterface) UpdateDatasetFileInfo(arg0 context.Context, arg1 string, arg2 int64, arg3 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDatasetFileInfo", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDatasetFileInfo indicates an expected call of UpdateDatasetFileInfo.
func (mr *MockInterfaceMockRecorder) UpdateDatasetFileInfo(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDatasetFileInfo", reflect.TypeOf((*MockInterface)(nil).UpdateDatasetFileInfo), arg0, arg1, arg2, arg3)
}

// UpdateDatasetLocalPath mocks base method.
func (m *MockInterface) UpdateDatasetLocalPath(arg0 context.Context, arg1, arg2 string, arg3 client.DatasetStatus, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDatasetLocalPath", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDatasetLocalPath indicates an expected call of UpdateDatasetLocalPath.
func (mr *MockInterfaceMockRecorder) UpdateDatasetLocalPath(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDatasetLocalPath", reflect.TypeOf((*MockInterface)(nil).UpdateDatasetLocalPath), arg0, arg1, arg2, arg3, arg4)
}

// UpdateDatasetStatus mocks base method.
func (m *MockInterface) UpdateDatasetStatus(arg0 context.Context, arg1 string, arg2 client.DatasetStatus, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDatasetStatus", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDatasetStatus indicates an expected call of UpdateDatasetStatus.
func (mr *MockInterfaceMockRecorder) UpdateDatasetStatus(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDatasetStatus", reflect.TypeOf((*MockInterface)(nil).UpdateDatasetStatus), arg0, arg1, arg2, arg3)
}

// UpdateDeploymentRequest mocks base method.
func (m *MockInterface) UpdateDeploymentRequest(arg0 context.Context, arg1 *client.DeploymentRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeploymentRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeploymentRequest indicates an expected call of UpdateDeploymentRequest.
func (mr *MockInterfaceMockRecorder) UpdateDeploymentRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeploymentRequest", reflect.TypeOf((*MockInterface)(nil).UpdateDeploymentRequest), arg0, arg1)
}

// UpdateEvaluationTaskOpsJobId mocks base method.
func (m *MockInterface) UpdateEvaluationTaskOpsJobId(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvaluationTaskOpsJobId", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvaluationTaskOpsJobId indicates an expected call of UpdateEvaluationTaskOpsJobId.
func (mr *MockInterfaceMockRecorder) UpdateEvaluationTaskOpsJobId(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvaluationTaskOpsJobId", reflect.TypeOf((*MockInterface)(nil).UpdateEvaluationTaskOpsJobId), arg0, arg1, arg2)
}

// UpdateEvaluationTaskResult mocks base method.
func (m *MockInterface) UpdateEvaluationTaskResult(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvaluationTaskResult", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvaluationTaskResult indicates an expected call of UpdateEvaluationTaskResult.
func (mr *MockInterfaceMockRecorder) UpdateEvaluationTaskResult(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvaluationTaskResult", reflect.TypeOf((*MockInterface)(nil).UpdateEvaluationTaskResult), arg0, arg1, arg2, arg3)
}

// UpdateEvaluationTaskStartTime mocks base method.
func (m *MockInterface) UpdateEvaluationTaskStartTime(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvaluationTaskStartTime", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvaluationTaskStartTime indicates an expected call of UpdateEvaluationTaskStartTime.
func (mr *MockInterfaceMockRecorder) UpdateEvaluationTaskStartTime(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvaluationTaskStartTime", reflect.TypeOf((*MockInterface)(nil).UpdateEvaluationTaskStartTime), arg0, arg1)
}

// UpdateEvaluationTaskStatus mocks base method.
func (m *MockInterface) UpdateEvaluationTaskStatus(arg0 context.Context, arg1 string, arg2 client.EvaluationTaskStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvaluationTaskStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvaluationTaskStatus indicates an expected call of UpdateEvaluationTaskStatus.
func (mr *MockInterfaceMockRecorder) UpdateEvaluationTaskStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvaluationTaskStatus", reflect.TypeOf((*MockInterface)(nil).UpdateEvaluationTaskStatus), arg0, arg1, arg2)
}

// UpdateImageImportJob mocks base method.
func (m *MockInterface) UpdateImageImportJob(arg0 context.Context, arg1 *model.ImageImportJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImageImportJob", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImageImportJob indicates an expected call of UpdateImageImportJob.
func (mr *MockInterfaceMockRecorder) UpdateImageImportJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImageImportJob", reflect.TypeOf((*MockInterface)(nil).UpdateImageImportJob), arg0, arg1)
}

// UpdateLLMBinding mocks base method.
func (m *MockInterface) UpdateLLMBinding(arg0 context.Context, arg1 *client.LLMGatewayUserBinding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLLMBinding", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLLMBinding indicates an expected call of UpdateLLMBinding.
func (mr *MockInterfaceMockRecorder) UpdateLLMBinding(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLLMBinding", reflect.TypeOf((*MockInterface)(nil).UpdateLLMBinding), arg0, arg1)
}

// UpdateNodeStatistic mocks base method.
func (m *MockInterface) UpdateNodeStatistic(arg0 context.Context, arg1 *model.NodeStatistic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNodeStatistic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNodeStatistic indicates an expected call of UpdateNodeStatistic.
func (mr *MockInterfaceMockRecorder) UpdateNodeStatistic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNodeStatistic", reflect.TypeOf((*MockInterface)(nil).UpdateNodeStatistic), arg0, arg1)
}

// UpdateNotification mocks base method.
func (m *MockInterface) UpdateNotification(arg0 context.Context, arg1 *model.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNotification", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNotification indicates an expected call of UpdateNotification.
func (mr *MockInterfaceMockRecorder) UpdateNotification(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNotification", reflect.TypeOf((*MockInterface)(nil).UpdateNotification), arg0, arg1)
}

// UpdatePlaygroundSession mocks base method.
func (m *MockInterface) UpdatePlaygroundSession(arg0 context.Context, arg1 *client.PlaygroundSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePlaygroundSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePlaygroundSession indicates an expected call of UpdatePlaygroundSession.
func (mr *MockInterfaceMockRecorder) UpdatePlaygroundSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePlaygroundSession", reflect.TypeOf((*MockInterface)(nil).UpdatePlaygroundSession), arg0, arg1)
}

// UpdateWorkloadStatistic mocks base method.
func (m *MockInterface) UpdateWorkloadStatistic(arg0 context.Context, arg1 *model.WorkloadStatistic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWorkloadStatistic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWorkloadStatistic indicates an expected call of UpdateWorkloadStatistic.
func (mr *MockInterfaceMockRecorder) UpdateWorkloadStatistic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWorkloadStatistic", reflect.TypeOf((*MockInterface)(nil).UpdateWorkloadStatistic), arg0, arg1)
}

// UpsertDataset mocks base method.
func (m *MockInterface) UpsertDataset(arg0 context.Context, arg1 *client.Dataset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDataset", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertDataset indicates an expected call of UpsertDataset.
func (mr *MockInterfaceMockRecorder) UpsertDataset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDataset", reflect.TypeOf((*MockInterface)(nil).UpsertDataset), arg0, arg1)
}

// UpsertEvaluationTask mocks base method.
func (m *MockInterface) UpsertEvaluationTask(arg0 context.Context, arg1 *client.EvaluationTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEvaluationTask", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEvaluationTask indicates an expected call of UpsertEvaluationTask.
func (mr *MockInterfaceMockRecorder) UpsertEvaluationTask(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEvaluationTask", reflect.TypeOf((*MockInterface)(nil).UpsertEvaluationTask), arg0, arg1)
}

// UpsertFault mocks base method.
func (m *MockInterface) UpsertFault(arg0 context.Context, arg1 *client.Fault) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertFault", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertFault indicates an expected call of UpsertFault.
func (mr *MockInterfaceMockRecorder) UpsertFault(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertFault", reflect.TypeOf((*MockInterface)(nil).UpsertFault), arg0, arg1)
}

// UpsertImage mocks base method.
func (m *MockInterface) UpsertImage(arg0 context.Context, arg1 *model.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertImage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertImage indicates an expected call of UpsertImage.
func (mr *MockInterfaceMockRecorder) UpsertImage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertImage", reflect.TypeOf((*MockInterface)(nil).UpsertImage), arg0, arg1)
}

// UpsertImageDigest mocks base method.
func (m *MockInterface) UpsertImageDigest(arg0 context.Context, arg1 *model.ImageDigest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertImageDigest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertImageDigest indicates an expected call of UpsertImageDigest.
func (mr *MockInterfaceMockRecorder) UpsertImageDigest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertImageDigest", reflect.TypeOf((*MockInterface)(nil).UpsertImageDigest), arg0, arg1)
}

// UpsertImageImportJob mocks base method.
func (m *MockInterface) UpsertImageImportJob(arg0 context.Context, arg1 *model.ImageImportJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertImageImportJob", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertImageImportJob indicates an expected call of UpsertImageImportJob.
func (mr *MockInterfaceMockRecorder) UpsertImageImportJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertImageImportJob", reflect.TypeOf((*MockInterface)(nil).UpsertImageImportJob), arg0, arg1)
}

// UpsertJob mocks base method.
func (m *MockInterface) UpsertJob(arg0 context.Context, arg1 *client.OpsJob) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertJob", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertJob indicates an expected call of UpsertJob.
func (mr *MockInterfaceMockRecorder) UpsertJob(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertJob", reflect.TypeOf((*MockInterface)(nil).UpsertJob), arg0, arg1)
}

// UpsertModel mocks base method.
func (m *MockInterface) UpsertModel(arg0 context.Context, arg1 *client.Model) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertModel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertModel indicates an expected call of UpsertModel.
func (mr *MockInterfaceMockRecorder) UpsertModel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertModel", reflect.TypeOf((*MockInterface)(nil).UpsertModel), arg0, arg1)
}

// UpsertNodeStatistic mocks base method.
func (m *MockInterface) UpsertNodeStatistic(arg0 context.Context, arg1 *model.NodeStatistic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertNodeStatistic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertNodeStatistic indicates an expected call of UpsertNodeStatistic.
func (mr *MockInterfaceMockRecorder) UpsertNodeStatistic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertNodeStatistic", reflect.TypeOf((*MockInterface)(nil).UpsertNodeStatistic), arg0, arg1)
}

// UpsertRegistryInfo mocks base method.
func (m *MockInterface) UpsertRegistryInfo(arg0 context.Context, arg1 *model.RegistryInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRegistryInfo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRegistryInfo indicates an expected call of UpsertRegistryInfo.
func (mr *MockInterfaceMockRecorder) UpsertRegistryInfo(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRegistryInfo", reflect.TypeOf((*MockInterface)(nil).UpsertRegistryInfo), arg0, arg1)
}

// UpsertUserToken mocks base method.
func (m *MockInterface) UpsertUserToken(arg0 context.Context, arg1 *client.UserToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserToken", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserToken indicates an expected call of UpsertUserToken.
func (mr *MockInterfaceMockRecorder) UpsertUserToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserToken", reflect.TypeOf((*MockInterface)(nil).UpsertUserToken), arg0, arg1)
}

// UpsertWorkload mocks base method.
func (m *MockInterface) UpsertWorkload(arg0 context.Context, arg1 *client.Workload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWorkload", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWorkload indicates an expected call of UpsertWorkload.
func (mr *MockInterfaceMockRecorder) UpsertWorkload(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWorkload", reflect.TypeOf((*MockInterface)(nil).UpsertWorkload), arg0, arg1)
}

// UpsertWorkloadStatistic mocks base method.
func (m *MockInterface) UpsertWorkloadStatistic(arg0 context.Context, arg1 *model.WorkloadStatistic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWorkloadStatistic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWorkloadStatistic indicates an expected call of UpsertWorkloadStatistic.
func (mr *MockInterfaceMockRecorder) UpsertWorkloadStatistic(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWorkloadStatistic", reflect.TypeOf((*MockInterface)(nil).UpsertWorkloadStatistic), arg0, arg1)
}
