# Control Plane Database Secret
#
# NOTE: If using PostgresCluster operator, the secret is auto-created with name:
#   primus-lens-control-plane-pguser-primus-lens-control-plane
# 
# The auto-created secret has fields: host, port, user, password, dbname
# No manual secret creation needed in this case.
#
# Only use this template if you need a custom secret:
#   kubectl apply -f 000_controlplane_db_secret.yaml
#
# Configure custom secret name via:
#   - Config file: controlPlane.secretName and controlPlane.secretNamespace
#   - Environment: CONTROLPLANE_DB_SECRET_NAME and CONTROLPLANE_DB_SECRET_NAMESPACE

apiVersion: v1
kind: Secret
metadata:
  name: lens-controlplane-db-custom  # Use custom name if needed
  namespace: primus-lens
type: Opaque
stringData:
  host: "primus-lens-control-plane-primary.primus-lens.svc.cluster.local"
  port: "5432"
  user: "primus-lens-control-plane"  # PostgresCluster uses "user" field
  password: "your-password-here"
  dbname: "primus-lens-control-plane"
  # sslmode is not in PostgresCluster secret, code defaults to "require"
