// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFault = "fault"

// Fault mapped from table <fault>
type Fault struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID            string    `gorm:"column:uid;not null" json:"uid"`
	MonitorID      string    `gorm:"column:monitor_id;not null" json:"monitor_id"`
	Message        string    `gorm:"column:message" json:"message"`
	Node           string    `gorm:"column:node" json:"node"`
	Action         string    `gorm:"column:action" json:"action"`
	Phase          string    `gorm:"column:phase" json:"phase"`
	Cluster        string    `gorm:"column:cluster" json:"cluster"`
	CreateTime     time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time" json:"update_time"`
	DeleteTime     time.Time `gorm:"column:delete_time" json:"delete_time"`
	IsAutoRepaired bool      `gorm:"column:is_auto_repaired" json:"is_auto_repaired"`
}

// TableName Fault's table name
func (*Fault) TableName() string {
	return TableNameFault
}
