// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImageImportJob = "image_import_job"

// ImageImportJob mapped from table <image_import_job>
type ImageImportJob struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SrcTag    string    `gorm:"column:src_tag" json:"src_tag"`
	DstName   string    `gorm:"column:dst_name" json:"dst_name"`
	Os        string    `gorm:"column:os" json:"os"`
	Arch      string    `gorm:"column:arch" json:"arch"`
	JobName   string    `gorm:"column:job_name" json:"job_name"`
	Log       string    `gorm:"column:log" json:"log"`
	Layer     ExtType   `gorm:"column:layer" json:"layer"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	ImageID   int32     `gorm:"column:image_id" json:"image_id"`
}

// TableName ImageImportJob's table name
func (*ImageImportJob) TableName() string {
	return TableNameImageImportJob
}
