/*
Copyright The AMD Authors.

*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/amd/v1"
	internal "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=amd.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("Cluster"):
		return &amdv1.ClusterApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ClusterSpec"):
		return &amdv1.ClusterSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Node"):
		return &amdv1.NodeApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) *testing.TypeConverter {
	return &testing.TypeConverter{Scheme: scheme, TypeResolver: internal.Parser()}
}
