/*
Copyright The AMD Authors.

*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/amd/v1"
	internal "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=amd.com, Version=v1
	case v1.SchemeGroupVersion.WithKind("ActiveState"):
		return &amdv1.ActiveStateApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Capacity"):
		return &amdv1.CapacityApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CephClusterStatus"):
		return &amdv1.CephClusterStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Cluster"):
		return &amdv1.ClusterApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ClusterSpec"):
		return &amdv1.ClusterSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ClusterStatus"):
		return &amdv1.ClusterStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CommandStatus"):
		return &amdv1.CommandStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ContainerFailedMessage"):
		return &amdv1.ContainerFailedMessageApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ControlPlane"):
		return &amdv1.ControlPlaneApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ControlPlaneStatus"):
		return &amdv1.ControlPlaneStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("CpuChip"):
		return &amdv1.CpuChipApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DiskFlavor"):
		return &amdv1.DiskFlavorApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("EndState"):
		return &amdv1.EndStateApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ErasureCodedSpec"):
		return &amdv1.ErasureCodedSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Fault"):
		return &amdv1.FaultApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FaultNode"):
		return &amdv1.FaultNodeApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FaultSpec"):
		return &amdv1.FaultSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("FaultStatus"):
		return &amdv1.FaultStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("GpuChip"):
		return &amdv1.GpuChipApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("HealthCheck"):
		return &amdv1.HealthCheckApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("HybridStorageSpec"):
		return &amdv1.HybridStorageSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MachineStatus"):
		return &amdv1.MachineStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Node"):
		return &amdv1.NodeApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodeClusterStatus"):
		return &amdv1.NodeClusterStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodeFlavor"):
		return &amdv1.NodeFlavorApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodeFlavorSpec"):
		return &amdv1.NodeFlavorSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodeSpec"):
		return &amdv1.NodeSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("NodeStatus"):
		return &amdv1.NodeStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("PodFailedMessage"):
		return &amdv1.PodFailedMessageApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ReplicatedSpec"):
		return &amdv1.ReplicatedSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ResourceTemplate"):
		return &amdv1.ResourceTemplateApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ResourceTemplateSpec"):
		return &amdv1.ResourceTemplateSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Service"):
		return &amdv1.ServiceApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Storage"):
		return &amdv1.StorageApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StorageCluster"):
		return &amdv1.StorageClusterApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StorageClusterSpec"):
		return &amdv1.StorageClusterSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StorageClusterStatus"):
		return &amdv1.StorageClusterStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("StorageStatus"):
		return &amdv1.StorageStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Template"):
		return &amdv1.TemplateApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("TemplatePhase"):
		return &amdv1.TemplatePhaseApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Workload"):
		return &amdv1.WorkloadApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("WorkloadPod"):
		return &amdv1.WorkloadPodApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("WorkloadResource"):
		return &amdv1.WorkloadResourceApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("WorkloadSpec"):
		return &amdv1.WorkloadSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("WorkloadStatus"):
		return &amdv1.WorkloadStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Workspace"):
		return &amdv1.WorkspaceApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("WorkspaceSpec"):
		return &amdv1.WorkspaceSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("WorkspaceStatus"):
		return &amdv1.WorkspaceStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("WorkspaceVolume"):
		return &amdv1.WorkspaceVolumeApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) *testing.TypeConverter {
	return &testing.TypeConverter{Scheme: scheme, TypeResolver: internal.Parser()}
}
