/*
 * Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by client-gen. DO NOT EDIT.

// This package has the automatically generated typed clients.
package v1
