/*
 * Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	applyconfigurationamdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/amd/v1"
	scheme "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// OpsJobsGetter has a method to return a OpsJobInterface.
// A group's client should implement this interface.
type OpsJobsGetter interface {
	OpsJobs(namespace string) OpsJobInterface
}

// OpsJobInterface has methods to work with OpsJob resources.
type OpsJobInterface interface {
	Create(ctx context.Context, opsJob *amdv1.OpsJob, opts metav1.CreateOptions) (*amdv1.OpsJob, error)
	Update(ctx context.Context, opsJob *amdv1.OpsJob, opts metav1.UpdateOptions) (*amdv1.OpsJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, opsJob *amdv1.OpsJob, opts metav1.UpdateOptions) (*amdv1.OpsJob, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*amdv1.OpsJob, error)
	List(ctx context.Context, opts metav1.ListOptions) (*amdv1.OpsJobList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *amdv1.OpsJob, err error)
	Apply(ctx context.Context, opsJob *applyconfigurationamdv1.OpsJobApplyConfiguration, opts metav1.ApplyOptions) (result *amdv1.OpsJob, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, opsJob *applyconfigurationamdv1.OpsJobApplyConfiguration, opts metav1.ApplyOptions) (result *amdv1.OpsJob, err error)
	OpsJobExpansion
}

// opsJobs implements OpsJobInterface
type opsJobs struct {
	*gentype.ClientWithListAndApply[*amdv1.OpsJob, *amdv1.OpsJobList, *applyconfigurationamdv1.OpsJobApplyConfiguration]
}

// newOpsJobs returns a OpsJobs
func newOpsJobs(c *AmdV1Client, namespace string) *opsJobs {
	return &opsJobs{
		gentype.NewClientWithListAndApply[*amdv1.OpsJob, *amdv1.OpsJobList, *applyconfigurationamdv1.OpsJobApplyConfiguration](
			"opsjobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *amdv1.OpsJob { return &amdv1.OpsJob{} },
			func() *amdv1.OpsJobList { return &amdv1.OpsJobList{} },
		),
	}
}
