/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	applyconfigurationamdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/amd/v1"
	scheme "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RolesGetter has a method to return a RoleInterface.
// A group's client should implement this interface.
type RolesGetter interface {
	Roles(namespace string) RoleInterface
}

// RoleInterface has methods to work with Role resources.
type RoleInterface interface {
	Create(ctx context.Context, role *amdv1.Role, opts metav1.CreateOptions) (*amdv1.Role, error)
	Update(ctx context.Context, role *amdv1.Role, opts metav1.UpdateOptions) (*amdv1.Role, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*amdv1.Role, error)
	List(ctx context.Context, opts metav1.ListOptions) (*amdv1.RoleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *amdv1.Role, err error)
	Apply(ctx context.Context, role *applyconfigurationamdv1.RoleApplyConfiguration, opts metav1.ApplyOptions) (result *amdv1.Role, err error)
	RoleExpansion
}

// roles implements RoleInterface
type roles struct {
	*gentype.ClientWithListAndApply[*amdv1.Role, *amdv1.RoleList, *applyconfigurationamdv1.RoleApplyConfiguration]
}

// newRoles returns a Roles
func newRoles(c *AmdV1Client, namespace string) *roles {
	return &roles{
		gentype.NewClientWithListAndApply[*amdv1.Role, *amdv1.RoleList, *applyconfigurationamdv1.RoleApplyConfiguration](
			"roles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *amdv1.Role { return &amdv1.Role{} },
			func() *amdv1.RoleList { return &amdv1.RoleList{} },
		),
	}
}
