/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	applyconfigurationamdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/applyconfiguration/amd/v1"
	scheme "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WorkspacesGetter has a method to return a WorkspaceInterface.
// A group's client should implement this interface.
type WorkspacesGetter interface {
	Workspaces(namespace string) WorkspaceInterface
}

// WorkspaceInterface has methods to work with Workspace resources.
type WorkspaceInterface interface {
	Create(ctx context.Context, workspace *amdv1.Workspace, opts metav1.CreateOptions) (*amdv1.Workspace, error)
	Update(ctx context.Context, workspace *amdv1.Workspace, opts metav1.UpdateOptions) (*amdv1.Workspace, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workspace *amdv1.Workspace, opts metav1.UpdateOptions) (*amdv1.Workspace, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*amdv1.Workspace, error)
	List(ctx context.Context, opts metav1.ListOptions) (*amdv1.WorkspaceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *amdv1.Workspace, err error)
	Apply(ctx context.Context, workspace *applyconfigurationamdv1.WorkspaceApplyConfiguration, opts metav1.ApplyOptions) (result *amdv1.Workspace, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, workspace *applyconfigurationamdv1.WorkspaceApplyConfiguration, opts metav1.ApplyOptions) (result *amdv1.Workspace, err error)
	WorkspaceExpansion
}

// workspaces implements WorkspaceInterface
type workspaces struct {
	*gentype.ClientWithListAndApply[*amdv1.Workspace, *amdv1.WorkspaceList, *applyconfigurationamdv1.WorkspaceApplyConfiguration]
}

// newWorkspaces returns a Workspaces
func newWorkspaces(c *AmdV1Client, namespace string) *workspaces {
	return &workspaces{
		gentype.NewClientWithListAndApply[*amdv1.Workspace, *amdv1.WorkspaceList, *applyconfigurationamdv1.WorkspaceApplyConfiguration](
			"workspaces",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *amdv1.Workspace { return &amdv1.Workspace{} },
			func() *amdv1.WorkspaceList { return &amdv1.WorkspaceList{} },
		),
	}
}
