/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// InferenceLister helps list Inferences.
// All objects returned here must be treated as read-only.
type InferenceLister interface {
	// List lists all Inferences in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*amdv1.Inference, err error)
	// Inferences returns an object that can list and get Inferences.
	Inferences(namespace string) InferenceNamespaceLister
	InferenceListerExpansion
}

// inferenceLister implements the InferenceLister interface.
type inferenceLister struct {
	listers.ResourceIndexer[*amdv1.Inference]
}

// NewInferenceLister returns a new InferenceLister.
func NewInferenceLister(indexer cache.Indexer) InferenceLister {
	return &inferenceLister{listers.New[*amdv1.Inference](indexer, amdv1.Resource("inference"))}
}

// Inferences returns an object that can list and get Inferences.
func (s *inferenceLister) Inferences(namespace string) InferenceNamespaceLister {
	return inferenceNamespaceLister{listers.NewNamespaced[*amdv1.Inference](s.ResourceIndexer, namespace)}
}

// InferenceNamespaceLister helps list and get Inferences.
// All objects returned here must be treated as read-only.
type InferenceNamespaceLister interface {
	// List lists all Inferences in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*amdv1.Inference, err error)
	// Get retrieves the Inference from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*amdv1.Inference, error)
	InferenceNamespaceListerExpansion
}

// inferenceNamespaceLister implements the InferenceNamespaceLister
// interface.
type inferenceNamespaceLister struct {
	listers.ResourceIndexer[*amdv1.Inference]
}
