/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// NodeFlavorLister helps list NodeFlavors.
// All objects returned here must be treated as read-only.
type NodeFlavorLister interface {
	// List lists all NodeFlavors in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*amdv1.NodeFlavor, err error)
	// NodeFlavors returns an object that can list and get NodeFlavors.
	NodeFlavors(namespace string) NodeFlavorNamespaceLister
	NodeFlavorListerExpansion
}

// nodeFlavorLister implements the NodeFlavorLister interface.
type nodeFlavorLister struct {
	listers.ResourceIndexer[*amdv1.NodeFlavor]
}

// NewNodeFlavorLister returns a new NodeFlavorLister.
func NewNodeFlavorLister(indexer cache.Indexer) NodeFlavorLister {
	return &nodeFlavorLister{listers.New[*amdv1.NodeFlavor](indexer, amdv1.Resource("nodeflavor"))}
}

// NodeFlavors returns an object that can list and get NodeFlavors.
func (s *nodeFlavorLister) NodeFlavors(namespace string) NodeFlavorNamespaceLister {
	return nodeFlavorNamespaceLister{listers.NewNamespaced[*amdv1.NodeFlavor](s.ResourceIndexer, namespace)}
}

// NodeFlavorNamespaceLister helps list and get NodeFlavors.
// All objects returned here must be treated as read-only.
type NodeFlavorNamespaceLister interface {
	// List lists all NodeFlavors in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*amdv1.NodeFlavor, err error)
	// Get retrieves the NodeFlavor from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*amdv1.NodeFlavor, error)
	NodeFlavorNamespaceListerExpansion
}

// nodeFlavorNamespaceLister implements the NodeFlavorNamespaceLister
// interface.
type nodeFlavorNamespaceLister struct {
	listers.ResourceIndexer[*amdv1.NodeFlavor]
}
