-- Migration: dashboard_performance_tables
-- Description: Tables for F1 Nightly Build Performance Dashboard feature with AI enhancements
-- Database: PostgreSQL
--
-- This migration creates tables for:
-- 1. dashboard_summaries - Pre-computed dashboard summary data with AI insights
-- 2. metric_baselines - Performance baseline values for regression detection
-- 3. commit_impact_analysis - AI-powered commit impact analysis results

-- ============================================================================
-- Table: dashboard_summaries
-- Pre-computed dashboard summary data for fast queries
-- ============================================================================

CREATE TABLE IF NOT EXISTS dashboard_summaries (
    id BIGSERIAL PRIMARY KEY,
    config_id BIGINT NOT NULL,
    date DATE NOT NULL,
    build_status VARCHAR(50) NOT NULL DEFAULT 'unknown',
    perf_change DOUBLE PRECISION NOT NULL DEFAULT 0,
    commit_count INTEGER NOT NULL DEFAULT 0,
    contributor_count INTEGER NOT NULL DEFAULT 0,
    alert_info JSONB DEFAULT '{}',
    top_improvements JSONB DEFAULT '[]',
    top_regressions JSONB DEFAULT '[]',
    ai_insights TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_config_date UNIQUE (config_id, date)
);

-- Comments
COMMENT ON TABLE dashboard_summaries IS 'Pre-computed dashboard summary data for each config and date';
COMMENT ON COLUMN dashboard_summaries.config_id IS 'Associated workflow config ID';
COMMENT ON COLUMN dashboard_summaries.date IS 'Date of the summary';
COMMENT ON COLUMN dashboard_summaries.build_status IS 'Build status: success, failure, cancelled, in_progress';
COMMENT ON COLUMN dashboard_summaries.perf_change IS 'Overall performance change percentage';
COMMENT ON COLUMN dashboard_summaries.commit_count IS 'Number of commits since previous run';
COMMENT ON COLUMN dashboard_summaries.contributor_count IS 'Number of unique contributors';
COMMENT ON COLUMN dashboard_summaries.alert_info IS 'JSON containing regression/improvement alerts with AI analysis';
COMMENT ON COLUMN dashboard_summaries.top_improvements IS 'JSON array of top performance improvements';
COMMENT ON COLUMN dashboard_summaries.top_regressions IS 'JSON array of top performance regressions';
COMMENT ON COLUMN dashboard_summaries.ai_insights IS 'Natural language insights generated by AI';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_dashboard_summaries_config ON dashboard_summaries(config_id);
CREATE INDEX IF NOT EXISTS idx_dashboard_summaries_date ON dashboard_summaries(date DESC);
CREATE INDEX IF NOT EXISTS idx_dashboard_summaries_config_date ON dashboard_summaries(config_id, date DESC);


-- ============================================================================
-- Table: metric_baselines
-- Store baseline values for performance metrics used in regression detection
-- ============================================================================

CREATE TABLE IF NOT EXISTS metric_baselines (
    id BIGSERIAL PRIMARY KEY,
    config_id BIGINT NOT NULL,
    metric_name VARCHAR(255) NOT NULL,
    dimensions JSONB NOT NULL DEFAULT '{}',
    baseline_value DOUBLE PRECISION NOT NULL,
    std_deviation DOUBLE PRECISION,
    unit VARCHAR(100),
    sample_count INTEGER NOT NULL DEFAULT 0,
    calculation_method VARCHAR(50) DEFAULT 'median',
    last_updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_config_metric_dimensions UNIQUE (config_id, metric_name, dimensions)
);

-- Comments
COMMENT ON TABLE metric_baselines IS 'Baseline values for performance metrics used in regression detection';
COMMENT ON COLUMN metric_baselines.config_id IS 'Associated workflow config ID';
COMMENT ON COLUMN metric_baselines.metric_name IS 'Name of the metric';
COMMENT ON COLUMN metric_baselines.dimensions IS 'JSON dimensions to uniquely identify a metric variant';
COMMENT ON COLUMN metric_baselines.baseline_value IS 'Baseline value for comparison';
COMMENT ON COLUMN metric_baselines.std_deviation IS 'Standard deviation of the metric';
COMMENT ON COLUMN metric_baselines.unit IS 'Unit of measurement (e.g., TFLOPS, ms, MB)';
COMMENT ON COLUMN metric_baselines.sample_count IS 'Number of samples used for calculation';
COMMENT ON COLUMN metric_baselines.calculation_method IS 'Method used to calculate baseline (e.g., median, mean, p95)';
COMMENT ON COLUMN metric_baselines.last_updated IS 'When this baseline was last updated';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_metric_baselines_config ON metric_baselines(config_id);
CREATE INDEX IF NOT EXISTS idx_metric_baselines_metric ON metric_baselines(config_id, metric_name);
CREATE INDEX IF NOT EXISTS idx_metric_baselines_dimensions ON metric_baselines USING GIN(dimensions);


-- ============================================================================
-- Table: commit_impact_analysis
-- Store AI-powered commit impact analysis results
-- ============================================================================

CREATE TABLE IF NOT EXISTS commit_impact_analysis (
    id BIGSERIAL PRIMARY KEY,
    config_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    commit_sha VARCHAR(64) NOT NULL,
    impact_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    risk_level VARCHAR(50),
    impact_categories JSONB DEFAULT '[]',
    affected_metrics JSONB DEFAULT '[]',
    explanation TEXT,
    recommendations JSONB DEFAULT '[]',
    is_ai_generated BOOLEAN NOT NULL DEFAULT false,
    confidence DOUBLE PRECISION,
    analyzed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_commit_config UNIQUE (config_id, commit_sha)
);

-- Comments
COMMENT ON TABLE commit_impact_analysis IS 'AI-powered analysis of commit impact on performance metrics';
COMMENT ON COLUMN commit_impact_analysis.config_id IS 'Associated workflow config ID';
COMMENT ON COLUMN commit_impact_analysis.run_id IS 'Associated workflow run ID';
COMMENT ON COLUMN commit_impact_analysis.commit_sha IS 'Git commit SHA (up to 64 chars for full SHA)';
COMMENT ON COLUMN commit_impact_analysis.impact_score IS 'Numerical score (0-100) indicating magnitude of impact';
COMMENT ON COLUMN commit_impact_analysis.risk_level IS 'Risk level: low, medium, high, critical';
COMMENT ON COLUMN commit_impact_analysis.impact_categories IS 'Categories like ["performance", "memory", "throughput"]';
COMMENT ON COLUMN commit_impact_analysis.affected_metrics IS 'JSON array of affected metrics with change details';
COMMENT ON COLUMN commit_impact_analysis.explanation IS 'Natural language explanation of the impact';
COMMENT ON COLUMN commit_impact_analysis.recommendations IS 'JSON array of recommended actions';
COMMENT ON COLUMN commit_impact_analysis.is_ai_generated IS 'True if analysis was generated by AI, false for rule-based';
COMMENT ON COLUMN commit_impact_analysis.confidence IS 'AI confidence score (0.0-1.0)';
COMMENT ON COLUMN commit_impact_analysis.analyzed_at IS 'When this analysis was performed';

-- Indexes
CREATE INDEX IF NOT EXISTS idx_commit_impact_config ON commit_impact_analysis(config_id);
CREATE INDEX IF NOT EXISTS idx_commit_impact_commit ON commit_impact_analysis(commit_sha);
CREATE INDEX IF NOT EXISTS idx_commit_impact_run ON commit_impact_analysis(run_id);
CREATE INDEX IF NOT EXISTS idx_commit_impact_analyzed ON commit_impact_analysis(analyzed_at DESC);
CREATE INDEX IF NOT EXISTS idx_commit_impact_risk ON commit_impact_analysis(config_id, risk_level) WHERE risk_level IN ('high', 'critical');
