{
 "title": "RDMA",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tx Bytes/min by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_bytes{}[1m]) by (node))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Tx Pkts/min by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_pkts{}[1m]) by (node))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Rx Bytes/min by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_rx_bytes{}[1m]) by (node))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Rx Pkts/min by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_rx_pkts{}[1m]) by (node))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Atomic Req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_atomic_req{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_atomic_req{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Read Resp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_read_resp{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_read_resp{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Read Req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_read_req{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_read_req{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Send Resp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_send_req{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_send_req{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Write Req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_write_req{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_write_req{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Roce Only Bytes/min by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_roce_only_bytes{}[1m]) by (node)) or rate(sum(rdma_stat_tx_rdma_ucast_bytes{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_roce_only_bytes{}[1m]) by (node)) or rate(sum(rdma_stat_rx_rdma_ucast_bytes{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Roce Only Pkts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_roce_only_pkts{}[1m]) by (node)) or rate(sum(rdma_stat_tx_rdma_ucast_pkts{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_roce_only_pkts{}[1m]) by (node)) or rate(sum(rdma_stat_rx_rdma_ucast_pkts{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "OOS Drop COunt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_oos_drop_count{}[1m]) by (node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Good Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_good_pkts{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_good_pkts{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Db Fifo Register",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_db_fifo_register{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Cnp Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_tx_cnp_pkts{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_cnp_pkts{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Ecn Marked Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_rx_ecn_marked_pkts{}[1m]) by (node))",
     "legendFormat": "Tx:{{node}}"
    },
    {
     "expr": "rate(sum(rdma_stat_rx_ecn_marked_pkts{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Rx Out of Buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_rx_out_of_buffer{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Pacing Reschedule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_pacing_reschedule{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Pacing Complete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_pacing_complete{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  {
   "title": "Pacing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(sum(rdma_stat_pacing_alerts{}[1m]) by (node))",
     "legendFormat": "Rx:{{node}}"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "increase(rdma_stat_rx_roce_discards{}[1m]) > 0 or increase(rdma_stat_rx_rdma_mtu_discard_pkts{}[1m]) > 0",
     "legendFormat": "RX Roce Discards:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_tx_roce_discards{}[1m]) > 0 or increase(rdma_stat_tx_rdma_mtu_discard_pkts{}[1m]) > 0",
     "legendFormat": "TX Roce Discards:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_tx_roce_errors{}[1m]) > 0",
     "legendFormat": "TX Roce Errors:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_rx_roce_errors{}[1m]) > 0",
     "legendFormat": "RX Roce Errors:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_seq_err_naks_rcvd{}[1m]) > 0 or increase(rdma_stat_req_rx_pkt_seq_err{}[1m]) > 0",
     "legendFormat": "NAK(Seq err):{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_rnr_naks_rcvd{}[1m]) > 0 or increase(rdma_stat_req_rx_rnr_retry_err{}[1m]) > 0",
     "legendFormat": "NAK(RNR):{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_missing_resp{}[1m]) > 0 or increase(rdma_stat_resp_rx_outouf_seq{}[1m]) > 0",
     "legendFormat": "Missing Resp:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_to_retransmits{}[1m]) > 0 or increase(rdma_stat_tx_rdma_retx_pkts{}[1m]) > 0",
     "legendFormat": "ReTransmit:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_max_retry_exceeded{}[1m]) > 0 or increase(rdma_stat_req_tx_retry_excd_err{}[1m]) > 0",
     "legendFormat": "MaxRetryExceeded:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_missing_resp{}[1m]) > 0 or increase(rdma_stat_resp_rx_outouf_seq{}[1m]) > 0",
     "legendFormat": "MissingResp:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_unrecoverable_err{}[1m]) > 0 or increase(rdma_stat_req_rx_cqe_err{}[1m]) > 0",
     "legendFormat": "UnrecoverableErr:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_local_qp_op_err{}[1m]) > 0 or increase(rdma_stat_req_tx_loc_oper_err{}[1m]) > 0",
     "legendFormat": "LocalQpOpErr:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_local_protection_err{}[1m]) > 0 or increase(rdma_stat_req_tx_loc_acc_err{}[1m]) > 0",
     "legendFormat": "LocalProtectionErr:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_remote_access_err{}[1m]) > 0  or increase(rdma_stat_req_rx_rmt_acc_err{}[1m]) > 0 ",
     "legendFormat": "RemoteAccessErr:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_remote_invalid_req_err{}[1m]) > 0 or increase(rdma_stat_req_rx_rmt_req_err{}[1m]) > 0",
     "legendFormat": "RemoteInvalidReqErr:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_remote_op_err{}[1m]) > 0  or increase(rdma_stat_resp_tx_rmt_oper_err{}[1m]) > 0 ",
     "legendFormat": "RemoteOpErr:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_opcode_err{}[1m]) > 0 ",
     "legendFormat": "Res Opcode Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_domain_err{}[1m]) > 0 ",
     "legendFormat": "Res Rx Domain Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_no_perm{}[1m]) > 0 ",
     "legendFormat": "Res Rx No Perm:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_range_err{}[1m]) > 0 ",
     "legendFormat": "Res Rx Range Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_domain_err{}[1m]) > 0 ",
     "legendFormat": "Res Tx Domain Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_no_perm{}[1m]) > 0 ",
     "legendFormat": "Res Tx No Perm:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_range_err{}[1m]) > 0 ",
     "legendFormat": "Res Tx Range Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rem_inv_err{}[1m]) > 0  or increase(rdma_stat_resp_tx_rmt_inval_req_err{}[1m]) > 0 ",
     "legendFormat": "Res Rem Inv Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_mem_err{}[1m]) > 0  or increase(rdma_stat_req_tx_mem_mgmt_err{}[1m]) > 0 ",
     "legendFormat": "Res Mem Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_srq_err{}[1m]) > 0 ",
     "legendFormat": "Res Srq Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_cmp_err{}[1m]) > 0  or increase(rdma_stat_req_rx_cqe_err{}[1m]) > 0 ",
     "legendFormat": "Res Cmp Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_wqe_format_err{}[1m]) > 0 ",
     "legendFormat": "Res Wqe Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_cq_load_err{}[1m]) > 0 ",
     "legendFormat": "Res Cq Load Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_srq_load_err{}[1m]) > 0 ",
     "legendFormat": "Res Srq Load Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_pci_err{}[1m]) > 0 ",
     "legendFormat": "Res Tx Pci Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_pci_err{}[1m]) > 0 ",
     "legendFormat": "Res Rx Pci Err:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_tx_rdma_cnp_pkts{}[1m]) > 0",
     "legendFormat": "TX CNP Pkts:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_rx_rdma_cnp_pkts{}[1m]) > 0",
     "legendFormat": "RX CNP Pkts:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_rx_rdma_ecn_pkts{}[1m]) > 0",
     "legendFormat": "RX ECN Pkts:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_tx_rdma_retx_bytes{}[1m]) > 0",
     "legendFormat": "TX Retransmit Bytes:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_tx_rdma_ack_timeout{}[1m]) > 0",
     "legendFormat": "TX ACK Timeout:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_req_rx_oper_err{}[1m]) > 0",
     "legendFormat": "Req RX Oper Err:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_req_rx_impl_nak_seq_err{}[1m]) > 0",
     "legendFormat": "Req RX Implied NAK Seq Err:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_req_rx_cqe_flush{}[1m]) > 0",
     "legendFormat": "Req RX CQE Flush:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_req_rx_dup_response{}[1m]) > 0",
     "legendFormat": "Req RX Dup Response:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_req_tx_loc_sgl_inv_err{}[1m]) > 0",
     "legendFormat": "Req TX Local SGL Invalid:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_rx_cqe_err{}[1m]) > 0",
     "legendFormat": "Resp RX CQE Err:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_rx_cqe_flush{}[1m]) > 0",
     "legendFormat": "Resp RX CQE Flush:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_rx_inval_request{}[1m]) > 0",
     "legendFormat": "Resp RX Invalid Request:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_rx_loc_oper_err{}[1m]) > 0",
     "legendFormat": "Resp RX Local Oper Err:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_tx_pkt_seq_err{}[1m]) > 0",
     "legendFormat": "Resp TX Pkt Seq Err:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_tx_rmt_acc_err{}[1m]) > 0",
     "legendFormat": "Resp TX Remote Access Err:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_tx_rnr_retry_err{}[1m]) > 0",
     "legendFormat": "Resp TX RNR Retry Err:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_tx_loc_sgl_inv_err{}[1m]) > 0",
     "legendFormat": "Resp TX Local SGL Invalid:{{node}}"
    },
    {
     "expr": "increase(rdma_stat_resp_rx_s0_table_err{}[1m]) > 0",
     "legendFormat": "Resp RX S0 Table Err:{{node}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "increase(rdma_stat_dup_req{}[1m]) > 0 or increase(rdma_stat_resp_rx_dup_request{}[1m]) > 0",
     "legendFormat": "DupReq:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_exceed_max{}[1m]) > 0 or increase(rdma_stat_req_tx_retry_excd_err{}[1m]) > 0",
     "legendFormat": "ResExceedMax:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_length_mismatch{}[1m]) > 0 or increase(rdma_stat_resp_rx_loc_len_err{}[1m]) > 0",
     "legendFormat": "ResLengthMismatch:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_exceeds_wqe{}[1m]) > 0",
     "legendFormat": "ResExceedsWqe:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_rx_invalid_rkey{}[1m]) > 0",
     "legendFormat": "Res Rx Invalid Rkey:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_tx_invalid_rkey{}[1m]) > 0",
     "legendFormat": "Res Tx Invalid Rkey:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_irrq_oflow{}[1m]) > 0 or increase(rdma_stat_resp_rx_outof_buf{}[1m]) > 0",
     "legendFormat": "Res Irrq Oflow:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_unsup_opcode{}[1m]) > 0 or increase(rdma_stat_req_rx_inval_pkts{}[1m]) > 0",
     "legendFormat": "Res Unsupported OpCode:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_unaligned_atomic{}[1m]) > 0 or increase(rdma_stat_resp_rx_outof_atomic{}[1m]) > 0",
     "legendFormat": "Res Unaligned Atomic:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_missing_resp{}[1m]) > 0 or increase(rdma_stat_resp_rx_outouf_seq{}[1m]) > 0",
     "legendFormat": "MissingResp:{{node}}:{{device}}"
    },
    {
     "expr": "increase(rdma_stat_res_invalid_dup_rkey{}[1m]) > 0",
     "legendFormat": "Res Invalid Dup Rkey:{{node}}:{{device}}"
    }
   ]
  }
 ]
}