apiVersion: v1
data:
  .dockerconfigjson: e30=
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-image
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
---
apiVersion: v1
data:
  .dockerconfigjson: e30=
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-image
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}