// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlertRules = "alert_rules"

// AlertRules mapped from table <alert_rules>
type AlertRules struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string    `gorm:"column:name;not null" json:"name"`
	Source       string    `gorm:"column:source;not null" json:"source"`
	Enabled      bool      `gorm:"column:enabled;default:true" json:"enabled"`
	RuleType     string    `gorm:"column:rule_type;not null" json:"rule_type"`
	RuleConfig   ExtType   `gorm:"column:rule_config;not null" json:"rule_config"`
	Severity     string    `gorm:"column:severity;default:warning" json:"severity"`
	Labels       ExtType   `gorm:"column:labels" json:"labels"`
	Annotations  ExtType   `gorm:"column:annotations" json:"annotations"`
	RouteConfig  ExtType   `gorm:"column:route_config" json:"route_config"`
	InhibitRules ExtType   `gorm:"column:inhibit_rules" json:"inhibit_rules"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	CreatedBy    string    `gorm:"column:created_by" json:"created_by"`
}

// TableName AlertRules's table name
func (*AlertRules) TableName() string {
	return TableNameAlertRules
}
