// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlertCorrelations = "alert_correlations"

// AlertCorrelations mapped from table <alert_correlations>
type AlertCorrelations struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CorrelationID       string    `gorm:"column:correlation_id;not null" json:"correlation_id"`
	AlertID             string    `gorm:"column:alert_id;not null" json:"alert_id"`
	CorrelationType     string    `gorm:"column:correlation_type;not null;comment:Type of correlation: time, entity, causal, or cross_source" json:"correlation_type"` // Type of correlation: time, entity, causal, or cross_source
	CorrelationScore    float64   `gorm:"column:correlation_score" json:"correlation_score"`
	CorrelationReason   string    `gorm:"column:correlation_reason" json:"correlation_reason"`
	CorrelationMetadata ExtType   `gorm:"column:correlation_metadata" json:"correlation_metadata"`
	CreatedAt           time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName AlertCorrelations's table name
func (*AlertCorrelations) TableName() string {
	return TableNameAlertCorrelations
}
