// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDetectionConflictLog = "detection_conflict_log"

// DetectionConflictLog mapped from table <detection_conflict_log>
type DetectionConflictLog struct {
	ID                 int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	WorkloadUID        string    `gorm:"column:workload_uid;not null;comment:UID of the workload with conflicting detections" json:"workload_uid"`                // UID of the workload with conflicting detections
	Source1            string    `gorm:"column:source_1;not null;comment:First detection source (e.g., component, log, image)" json:"source_1"`                   // First detection source (e.g., component, log, image)
	Source2            string    `gorm:"column:source_2;not null;comment:Second detection source that conflicts with first" json:"source_2"`                      // Second detection source that conflicts with first
	Framework1         string    `gorm:"column:framework_1;not null;comment:Framework detected by source_1" json:"framework_1"`                                   // Framework detected by source_1
	Framework2         string    `gorm:"column:framework_2;not null;comment:Framework detected by source_2 (conflicts with framework_1)" json:"framework_2"`      // Framework detected by source_2 (conflicts with framework_1)
	Confidence1        float64   `gorm:"column:confidence_1;not null;comment:Confidence level from source_1 (0.00-1.00)" json:"confidence_1"`                     // Confidence level from source_1 (0.00-1.00)
	Confidence2        float64   `gorm:"column:confidence_2;not null;comment:Confidence level from source_2 (0.00-1.00)" json:"confidence_2"`                     // Confidence level from source_2 (0.00-1.00)
	ResolutionStrategy string    `gorm:"column:resolution_strategy;comment:Strategy used to resolve the conflict" json:"resolution_strategy"`                     // Strategy used to resolve the conflict
	ResolvedFramework  string    `gorm:"column:resolved_framework;comment:Final framework after conflict resolution" json:"resolved_framework"`                   // Final framework after conflict resolution
	ResolvedConfidence float64   `gorm:"column:resolved_confidence;comment:Final confidence after conflict resolution" json:"resolved_confidence"`                // Final confidence after conflict resolution
	ResolvedAt         time.Time `gorm:"column:resolved_at;comment:Timestamp when the conflict was resolved" json:"resolved_at"`                                  // Timestamp when the conflict was resolved
	Evidence1          ExtType   `gorm:"column:evidence_1;comment:Evidence/details from source_1" json:"evidence_1"`                                              // Evidence/details from source_1
	Evidence2          ExtType   `gorm:"column:evidence_2;comment:Evidence/details from source_2" json:"evidence_2"`                                              // Evidence/details from source_2
	CreatedAt          time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:Timestamp when the conflict was detected" json:"created_at"` // Timestamp when the conflict was detected
}

// TableName DetectionConflictLog's table name
func (*DetectionConflictLog) TableName() string {
	return TableNameDetectionConflictLog
}
