// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFrameworkDetectionVersioned = "framework_detection_versioned"

// FrameworkDetectionVersioned mapped from table <framework_detection_versioned>
type FrameworkDetectionVersioned struct {
	WorkloadUID string    `gorm:"column:workload_uid;primaryKey" json:"workload_uid"`
	Version     string    `gorm:"column:version;default:1.0" json:"version"`
	Data        ExtType   `gorm:"column:data" json:"data"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName FrameworkDetectionVersioned's table name
func (*FrameworkDetectionVersioned) TableName() string {
	return TableNameFrameworkDetectionVersioned
}
