// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGenericCache = "generic_cache"

// GenericCache mapped from table <generic_cache>
type GenericCache struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Key       string    `gorm:"column:key;not null;comment:Unique cache key identifier" json:"key"`                                                              // Unique cache key identifier
	Value     ExtType   `gorm:"column:value;not null;comment:JSONB value containing cached data" json:"value"`                                                   // JSONB value containing cached data
	ExpiresAt time.Time `gorm:"column:expires_at;comment:Optional expiration timestamp, NULL means no expiration" json:"expires_at"`                             // Optional expiration timestamp, NULL means no expiration
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:Timestamp when the cache entry was first created" json:"created_at"` // Timestamp when the cache entry was first created
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:Timestamp when the cache entry was last updated" json:"updated_at"`  // Timestamp when the cache entry was last updated
}

// TableName GenericCache's table name
func (*GenericCache) TableName() string {
	return TableNameGenericCache
}
