// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGithubWorkflowCommits = "github_workflow_commits"

// GithubWorkflowCommits mapped from table <github_workflow_commits>
type GithubWorkflowCommits struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RunID          int64     `gorm:"column:run_id;not null" json:"run_id"`
	Sha            string    `gorm:"column:sha;not null" json:"sha"`
	Message        string    `gorm:"column:message" json:"message"`
	AuthorName     string    `gorm:"column:author_name" json:"author_name"`
	AuthorEmail    string    `gorm:"column:author_email" json:"author_email"`
	AuthorDate     time.Time `gorm:"column:author_date" json:"author_date"`
	CommitterName  string    `gorm:"column:committer_name" json:"committer_name"`
	CommitterEmail string    `gorm:"column:committer_email" json:"committer_email"`
	CommitterDate  time.Time `gorm:"column:committer_date" json:"committer_date"`
	Additions      int32     `gorm:"column:additions;not null" json:"additions"`
	Deletions      int32     `gorm:"column:deletions;not null" json:"deletions"`
	FilesChanged   int32     `gorm:"column:files_changed;not null" json:"files_changed"`
	ParentShas     ExtJSON   `gorm:"column:parent_shas;not null;default:[]" json:"parent_shas"`
	Files          ExtType   `gorm:"column:files" json:"files"`
	HTMLURL        string    `gorm:"column:html_url" json:"html_url"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName GithubWorkflowCommits's table name
func (*GithubWorkflowCommits) TableName() string {
	return TableNameGithubWorkflowCommits
}
