// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGithubWorkflowRunSummaries = "github_workflow_run_summaries"

// GithubWorkflowRunSummaries mapped from table <github_workflow_run_summaries>
type GithubWorkflowRunSummaries struct {
	ID                        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GithubRunID               int64     `gorm:"column:github_run_id;not null" json:"github_run_id"`
	GithubRunNumber           int32     `gorm:"column:github_run_number;not null" json:"github_run_number"`
	GithubRunAttempt          int32     `gorm:"column:github_run_attempt;default:1" json:"github_run_attempt"`
	Owner                     string    `gorm:"column:owner;not null" json:"owner"`
	Repo                      string    `gorm:"column:repo;not null" json:"repo"`
	WorkflowName              string    `gorm:"column:workflow_name" json:"workflow_name"`
	WorkflowPath              string    `gorm:"column:workflow_path" json:"workflow_path"`
	WorkflowID                int64     `gorm:"column:workflow_id" json:"workflow_id"`
	HeadSha                   string    `gorm:"column:head_sha" json:"head_sha"`
	HeadBranch                string    `gorm:"column:head_branch" json:"head_branch"`
	BaseBranch                string    `gorm:"column:base_branch" json:"base_branch"`
	EventName                 string    `gorm:"column:event_name" json:"event_name"`
	Actor                     string    `gorm:"column:actor" json:"actor"`
	TriggeringActor           string    `gorm:"column:triggering_actor" json:"triggering_actor"`
	Status                    string    `gorm:"column:status" json:"status"`
	Conclusion                string    `gorm:"column:conclusion" json:"conclusion"`
	RunStartedAt              time.Time `gorm:"column:run_started_at" json:"run_started_at"`
	RunCompletedAt            time.Time `gorm:"column:run_completed_at" json:"run_completed_at"`
	TotalJobs                 int32     `gorm:"column:total_jobs;default:0" json:"total_jobs"`
	CompletedJobs             int32     `gorm:"column:completed_jobs;default:0" json:"completed_jobs"`
	SuccessfulJobs            int32     `gorm:"column:successful_jobs;default:0" json:"successful_jobs"`
	FailedJobs                int32     `gorm:"column:failed_jobs;default:0" json:"failed_jobs"`
	CancelledJobs             int32     `gorm:"column:cancelled_jobs;default:0" json:"cancelled_jobs"`
	SkippedJobs               int32     `gorm:"column:skipped_jobs;default:0" json:"skipped_jobs"`
	InProgressJobs            int32     `gorm:"column:in_progress_jobs;default:0" json:"in_progress_jobs"`
	QueuedJobs                int32     `gorm:"column:queued_jobs;default:0" json:"queued_jobs"`
	CurrentJobName            string    `gorm:"column:current_job_name" json:"current_job_name"`
	CurrentStepName           string    `gorm:"column:current_step_name" json:"current_step_name"`
	ProgressPercent           int32     `gorm:"column:progress_percent;default:0" json:"progress_percent"`
	TotalFilesProcessed       int32     `gorm:"column:total_files_processed;default:0" json:"total_files_processed"`
	TotalMetricsCount         int32     `gorm:"column:total_metrics_count;default:0" json:"total_metrics_count"`
	CollectionStatus          string    `gorm:"column:collection_status" json:"collection_status"`
	PrimaryRunnerSetID        int64     `gorm:"column:primary_runner_set_id" json:"primary_runner_set_id"`
	ConfigID                  int64     `gorm:"column:config_id" json:"config_id"`
	LastSyncedAt              time.Time `gorm:"column:last_synced_at" json:"last_synced_at"`
	SyncErrorMessage          string    `gorm:"column:sync_error_message" json:"sync_error_message"`
	GraphFetched              bool      `gorm:"column:graph_fetched;default:false" json:"graph_fetched"`
	GraphFetchedAt            time.Time `gorm:"column:graph_fetched_at" json:"graph_fetched_at"`
	CodeAnalysisTriggered     bool      `gorm:"column:code_analysis_triggered;default:false" json:"code_analysis_triggered"`
	CodeAnalysisTriggeredAt   time.Time `gorm:"column:code_analysis_triggered_at" json:"code_analysis_triggered_at"`
	FailureAnalysisTriggered  bool      `gorm:"column:failure_analysis_triggered;default:false" json:"failure_analysis_triggered"`
	FailureAnalysisTriggeredAt time.Time `gorm:"column:failure_analysis_triggered_at" json:"failure_analysis_triggered_at"`
	CreatedAt                 time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt                 time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName GithubWorkflowRunSummaries's table name
func (*GithubWorkflowRunSummaries) TableName() string {
	return TableNameGithubWorkflowRunSummaries
}
