// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGpuPodsEvent = "gpu_pods_event"

// GpuPodsEvent mapped from table <gpu_pods_event>
type GpuPodsEvent struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PodUUID      string    `gorm:"column:pod_uuid" json:"pod_uuid"`
	PodPhase     string    `gorm:"column:pod_phase" json:"pod_phase"`
	EventType    string    `gorm:"column:event_type" json:"event_type"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	RestartCount int32     `gorm:"column:restart_count" json:"restart_count"`
}

// TableName GpuPodsEvent's table name
func (*GpuPodsEvent) TableName() string {
	return TableNameGpuPodsEvent
}
