// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameGpuWorkloadSnapshot = "gpu_workload_snapshot"

// GpuWorkloadSnapshot mapped from table <gpu_workload_snapshot>
type GpuWorkloadSnapshot struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID             string    `gorm:"column:uid" json:"uid"`
	GroupVersion    string    `gorm:"column:group_version" json:"group_version"`
	Kind            string    `gorm:"column:kind" json:"kind"`
	Name            string    `gorm:"column:name" json:"name"`
	Namespace       string    `gorm:"column:namespace" json:"namespace"`
	Metadata        ExtType   `gorm:"column:metadata" json:"metadata"`
	Detail          ExtType   `gorm:"column:detail" json:"detail"`
	ResourceVersion int32     `gorm:"column:resource_version" json:"resource_version"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
}

// TableName GpuWorkloadSnapshot's table name
func (*GpuWorkloadSnapshot) TableName() string {
	return TableNameGpuWorkloadSnapshot
}
