// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameImageRegistryCache = "image_registry_cache"

// ImageRegistryCache mapped from table <image_registry_cache>
type ImageRegistryCache struct {
	ID                int64      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ImageRef          string     `gorm:"column:image_ref;not null;comment:Full image reference including registry/repo:tag" json:"image_ref"`
	Digest            string     `gorm:"column:digest;not null;comment:Image SHA256 digest (unique index)" json:"digest"`
	Registry          string     `gorm:"column:registry;comment:Registry address" json:"registry"`
	Repository        string     `gorm:"column:repository;comment:Repository path (e.g. teamA/training)" json:"repository"`
	Tag               string     `gorm:"column:tag;comment:Image tag" json:"tag"`
	BaseImage         string     `gorm:"column:base_image;comment:Base image parsed from layer history" json:"base_image"`
	LayerCount        int32      `gorm:"column:layer_count;not null;default:0;comment:Total number of layers" json:"layer_count"`
	LayerHistory      ExtJSON    `gorm:"column:layer_history;default:[];comment:Complete layer history: [{created_by, size, comment}, ...] (JSONB)" json:"layer_history"`
	ImageLabels       ExtType    `gorm:"column:image_labels;default:{};comment:Image OCI/Docker labels (JSONB)" json:"image_labels"`
	ImageEnv          ExtType    `gorm:"column:image_env;default:{};comment:Image built-in environment variables (JSONB)" json:"image_env"`
	ImageEntrypoint   string     `gorm:"column:image_entrypoint;comment:Image default entrypoint" json:"image_entrypoint"`
	InstalledPackages ExtJSON    `gorm:"column:installed_packages;default:[];comment:Packages extracted from layer history: [{manager, name, version}, ...] (JSONB)" json:"installed_packages"`
	FrameworkHints    ExtType    `gorm:"column:framework_hints;default:{};comment:Framework hints from layer analysis: {frameworks, libraries, gpu_platform} (JSONB)" json:"framework_hints"`
	TotalSize         int64      `gorm:"column:total_size;not null;default:0;comment:Total image size in bytes" json:"total_size"`
	ImageCreatedAt    *time.Time `gorm:"column:image_created_at;comment:Image build timestamp" json:"image_created_at"`
	CachedAt          time.Time  `gorm:"column:cached_at;not null;default:now();comment:Cache entry creation time" json:"cached_at"`
	ExpiresAt         *time.Time `gorm:"column:expires_at;comment:Cache expiration time for tag-based lookups" json:"expires_at"`
}

// TableName ImageRegistryCache's table name
func (*ImageRegistryCache) TableName() string {
	return TableNameImageRegistryCache
}
