// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLogAlertRuleVersions = "log_alert_rule_versions"

// LogAlertRuleVersions mapped from table <log_alert_rule_versions>
type LogAlertRuleVersions struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RuleID     int64     `gorm:"column:rule_id;not null" json:"rule_id"`
	Version    int32     `gorm:"column:version;not null" json:"version"`
	Config     ExtType   `gorm:"column:config;not null" json:"config"`
	Status     string    `gorm:"column:status;default:draft" json:"status"`
	DeployedAt time.Time `gorm:"column:deployed_at" json:"deployed_at"`
	CreatedBy  string    `gorm:"column:created_by" json:"created_by"`
	CreatedAt  time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
	ChangeLog  string    `gorm:"column:change_log" json:"change_log"`
}

// TableName LogAlertRuleVersions's table name
func (*LogAlertRuleVersions) TableName() string {
	return TableNameLogAlertRuleVersions
}
