// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameNodeNamespaceMappingHistory = "node_namespace_mapping_history"

// NodeNamespaceMappingHistory mapped from table <node_namespace_mapping_history>
type NodeNamespaceMappingHistory struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:Primary key" json:"id"`                                                                                // Primary key
	MappingID     int32     `gorm:"column:mapping_id;not null;comment:Reference to the original mapping record" json:"mapping_id"`                                                        // Reference to the original mapping record
	NodeID        int32     `gorm:"column:node_id;not null;comment:Node ID at the time of the change" json:"node_id"`                                                                     // Node ID at the time of the change
	NodeName      string    `gorm:"column:node_name;not null;comment:Node name at the time of the change" json:"node_name"`                                                               // Node name at the time of the change
	NamespaceID   int64     `gorm:"column:namespace_id;not null;comment:Namespace ID at the time of the change" json:"namespace_id"`                                                      // Namespace ID at the time of the change
	NamespaceName string    `gorm:"column:namespace_name;not null;comment:Namespace name at the time of the change" json:"namespace_name"`                                                // Namespace name at the time of the change
	Action        string    `gorm:"column:action;not null;comment:Type of change: added (node joined namespace) or removed (node left namespace)" json:"action"`                          // Type of change: added (node joined namespace) or removed (node left namespace)
	RecordStart   time.Time `gorm:"column:record_start;not null;default:CURRENT_TIMESTAMP;comment:Start time when this node-namespace relationship became effective" json:"record_start"` // Start time when this node-namespace relationship became effective
	RecordEnd     time.Time `gorm:"column:record_end;comment:End time when this relationship ended (NULL means currently active)" json:"record_end"`                                      // End time when this relationship ended (NULL means currently active)
}

// TableName NodeNamespaceMappingHistory's table name
func (*NodeNamespaceMappingHistory) TableName() string {
	return TableNameNodeNamespaceMappingHistory
}
