// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProfilerFiles = "profiler_files"

// ProfilerFiles mapped from table <profiler_files>
type ProfilerFiles struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	WorkloadUID   string    `gorm:"column:workload_uid;not null" json:"workload_uid"`
	PodUID        string    `gorm:"column:pod_uid" json:"pod_uid"`
	PodName       string    `gorm:"column:pod_name" json:"pod_name"`
	PodNamespace  string    `gorm:"column:pod_namespace" json:"pod_namespace"`
	FileName      string    `gorm:"column:file_name;not null" json:"file_name"`
	FilePath      string    `gorm:"column:file_path" json:"file_path"`
	FileType      string    `gorm:"column:file_type;not null" json:"file_type"`
	FileSize      int64     `gorm:"column:file_size" json:"file_size"`
	StorageType   string    `gorm:"column:storage_type;not null" json:"storage_type"`
	StoragePath   string    `gorm:"column:storage_path" json:"storage_path"`
	StorageBucket string    `gorm:"column:storage_bucket" json:"storage_bucket"`
	DownloadURL   string    `gorm:"column:download_url" json:"download_url"`
	Confidence    string    `gorm:"column:confidence" json:"confidence"`
	SourcePid     int32     `gorm:"column:source_pid" json:"source_pid"`
	DetectedAt    time.Time `gorm:"column:detected_at" json:"detected_at"`
	CollectedAt   time.Time `gorm:"column:collected_at;not null;default:now()" json:"collected_at"`
	ExpiresAt     time.Time `gorm:"column:expires_at" json:"expires_at"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	Metadata      ExtType   `gorm:"column:metadata" json:"metadata"`
}

// TableName ProfilerFiles's table name
func (*ProfilerFiles) TableName() string {
	return TableNameProfilerFiles
}
