{
 "title": "Training Workload",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   {
    "name": "workload_uid",
    "query": {
     "query": "label_values(workload_gpu_clock,workload_uid)"
    }
   },
   {
    "name": "training_perf_datasource",
    "label": "Perf Datasource",
    "query": {}
   },
   {
    "name": "training_perf_metrics",
    "label": "Metrics",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Training Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.data[*].metric_name", "name": "" },
      { "jsonPath": "$.data[*].timestamp", "language": "jsonpath", "name": "", "type": "time" },
      { "jsonPath": "$.data[*].value", "language": "jsonpath", "name": " ", "type": "number" }
     ],
     "method": "GET",
     "params": [
      [
       "data_source",
       "$training_perf_datasource"
      ],
      [
       "start",
       "${__from}"
      ],
      [
       "end",
       "${__to}"
      ],
      [
       "metrics",
       "$training_perf_metrics"
      ]
     ],
     "urlPath": "/v1/workloads/${workload_uid}/metrics/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.data[*].timestamp", "language": "jsonpath", "name": "", "type": "time" },
      { "jsonPath": "$.data[*].metric_name", "language": "jsonpath", "name": "", "type": "string" },
      { "jsonPath": "$.data[*].value", "language": "jsonpath", "name": "-", "type": "number" }
     ],
     "method": "GET",
     "params": [
      [
       "data_source",
       "$training_perf_datasource"
      ],
      [
       "start",
       "${__from}"
      ],
      [
       "end",
       "${__to}"
      ]
     ],
     "urlPath": "/v1/workloads/${workload_uid}/metrics/iteration-times"
    }
   ]
  },
  {
   "title": "RDMA Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_discards{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_rx_rdma_mtu_discard_pkts{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name)> 0",
     "legendFormat": "RX Roce Discards:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_discards{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_tx_rdma_mtu_discard_pkts{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name)> 0",
     "legendFormat": "TX Roce Discards:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "TX Roce Errors:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "RX Roce Errors:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_seq_err_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_rx_pkt_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "NAK(Seq err):{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rnr_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_rx_rnr_retry_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "NAK(RNR):{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_resp_rx_outouf_seq{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Missing Resp:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_to_retransmits{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_tx_rdma_retx_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "ReTransmit:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_max_retry_exceeded{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_tx_retry_excd_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "MaxRetryExceeded:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_resp_rx_outouf_seq{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "MissingResp:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_unrecoverable_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "UnrecoverableErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_qp_op_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_tx_loc_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "LocalQpOpErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_protection_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_tx_loc_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "LocalProtectionErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_access_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_req_rx_rmt_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "RemoteAccessErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_invalid_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_rx_rmt_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "RemoteInvalidReqErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_op_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_resp_tx_rmt_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "RemoteOpErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_opcode_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Opcode Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rx Domain Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rx No Perm:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rx Range Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Tx Domain Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Tx No Perm:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Tx Range Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rem_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_resp_tx_rmt_inval_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rem Inv Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_mem_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_req_tx_mem_mgmt_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Mem Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Srq Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cmp_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_req_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Cmp Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_wqe_format_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Wqe Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Cq Load Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Srq Load Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Tx Pci Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rx Pci Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_cnp_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "TX CNP Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_rdma_cnp_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "RX CNP Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_rdma_ecn_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "RX ECN Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_retx_bytes{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "TX Retransmit Bytes:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_ack_timeout{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "TX ACK Timeout:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req RX Oper Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_impl_nak_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req RX Implied NAK Seq Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_cqe_flush{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req RX CQE Flush:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_dup_response{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req RX Dup Response:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_tx_loc_sgl_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req TX Local SGL Invalid:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX CQE Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_cqe_flush{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX CQE Flush:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_inval_request{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX Invalid Request:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_loc_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX Local Oper Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_pkt_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp TX Pkt Seq Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_rmt_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp TX Remote Access Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_rnr_retry_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp TX RNR Retry Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_loc_sgl_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp TX Local SGL Invalid:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_s0_table_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX S0 Table Err:{{primus_lens_node_name}}"
    }
   ]
  },
  { "title": "Training Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Training Performance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.data[*].metric_name" },
      { "jsonPath": "$.data[*].timestamp", "language": "jsonpath", "name": "", "type": "time" },
      { "jsonPath": "$.data[*].value", "language": "jsonpath", "name": "", "type": "number" }
     ],
     "method": "GET",
     "params": [
      [
       "data_source",
       "$training_perf_datasource"
      ],
      [
       "start",
       "${__from}"
      ],
      [
       "end",
       "${__to}"
      ],
      [
       "metrics",
       "$training_perf_metrics"
      ]
     ],
     "urlPath": "/v1/workloads/${workload_uid}/metrics/data"
    },
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.data[*].timestamp", "language": "jsonpath", "name": "", "type": "time" },
      { "jsonPath": "$.data[*].iteration", "language": "jsonpath", "name": "", "type": "number" }
     ],
     "method": "GET",
     "params": [
      [
       "data_source",
       "$training_perf_datasource"
      ],
      [
       "start",
       "${__from}"
      ],
      [
       "end",
       "${__to}"
      ]
     ],
     "urlPath": "/v1/workloads/${workload_uid}/metrics/iteration-times"
    }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Pod Cpu Usage(cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(workload_container_cpu_usage_seconds_total{workload_uid=\"$workload_uid\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum by (pod) (\n    workload_container_memory_working_set_bytes{container!=\"\",pod!=\"\",workload_uid = \"$workload_uid\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Utilzation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "(\n  sum by (pod) (\n    workload_container_memory_working_set_bytes{container!=\"\",pod!=\"\",workload_uid = \"$workload_uid\"}\n  )\n)\n/\n(\n  sum by (pod) (\n    workload_kube_pod_container_resource_requests{resource=\"memory\",workload_uid = \"$workload_uid\"}\n  )\n)\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Ephemeral Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum by (pod) (\n    workload_pod_ephemeral_storage_usage_bytes{workload_uid = \"$workload_uid\"}\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Write Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod,container) (\n  rate(workload_container_fs_writes_bytes_total{container!=\"\",pod!=\"\",workload_uid=\"$workload_uid\"}[5m])\n)",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  {
   "title": "Pod Read Bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod,container) (\n  rate(workload_container_fs_reads_bytes_total{container!=\"\",pod!=\"\",workload_uid=\"$workload_uid\"}[5m])\n)",
     "legendFormat": "{{pod}}:{{container}}"
    }
   ]
  },
  { "title": "Node Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "avg(workload_gpu_utilization{workload_uid=\"$workload_uid\"}) by (primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "100 - ((avg(workload_gpu_free_vram{workload_uid=\"$workload_uid\"}) by (primus_lens_node_name))/(avg(workload_gpu_total_vram{workload_uid=\"$workload_uid\"}) by (primus_lens_node_name)) * 100)",
     "legendFormat": "{{primus_lens_node_name}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(workload_gpu_socket_power_watts{workload_uid=\"$workload_uid\"}) by (primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "(avg(workload_gpu_total_vram{workload_uid=\"$workload_uid\"}) by (primus_lens_node_name)) - (avg(workload_gpu_free_vram{workload_uid=\"$workload_uid\"}) by (primus_lens_node_name))",
     "legendFormat": "{{primus_lens_node_name}}"
    }
   ]
  },
  {
   "title": "RDMA Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_rdma_stat_tx_roce_only_bytes{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name) or sum(rate(workload_rdma_stat_tx_rdma_ucast_bytes{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}}  TX"
    },
    {
     "expr": "sum(rate(workload_rdma_stat_rx_roce_only_bytes{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name) or sum(rate(workload_rdma_stat_rx_rdma_ucast_bytes{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}}  RX"
    }
   ]
  },
  {
   "title": "RDMA Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "sum(rate(workload_rdma_stat_tx_roce_only_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name) or sum(rate(workload_rdma_stat_tx_rdma_ucast_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}}  TX"
    },
    {
     "expr": "sum(rate(workload_rdma_stat_rx_roce_only_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name) or sum(rate(workload_rdma_stat_rx_rdma_ucast_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}}  RX"
    }
   ]
  },
  {
   "title": "RDMA Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_discards{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_rx_rdma_mtu_discard_pkts{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name)> 0",
     "legendFormat": "RX Roce Discards:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_discards{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_tx_rdma_mtu_discard_pkts{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name)> 0",
     "legendFormat": "TX Roce Discards:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "TX Roce Errors:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "RX Roce Errors:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_seq_err_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_rx_pkt_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "NAK(Seq err):{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rnr_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_rx_rnr_retry_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "NAK(RNR):{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_resp_rx_outouf_seq{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Missing Resp:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_to_retransmits{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_tx_rdma_retx_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "ReTransmit:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_max_retry_exceeded{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_tx_retry_excd_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "MaxRetryExceeded:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_resp_rx_outouf_seq{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "MissingResp:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_unrecoverable_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "UnrecoverableErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_qp_op_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_tx_loc_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "LocalQpOpErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_protection_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_tx_loc_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "LocalProtectionErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_access_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_req_rx_rmt_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "RemoteAccessErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_invalid_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 or sum(increase(workload_rdma_stat_req_rx_rmt_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "RemoteInvalidReqErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_op_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_resp_tx_rmt_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "RemoteOpErr:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_opcode_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Opcode Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rx Domain Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rx No Perm:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rx Range Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Tx Domain Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Tx No Perm:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Tx Range Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rem_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_resp_tx_rmt_inval_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rem Inv Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_mem_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_req_tx_mem_mgmt_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Mem Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Srq Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cmp_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0  or sum(increase(workload_rdma_stat_req_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Cmp Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_wqe_format_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Wqe Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Cq Load Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Srq Load Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Tx Pci Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0 ",
     "legendFormat": "Res Rx Pci Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_cnp_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "TX CNP Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_rdma_cnp_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "RX CNP Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_rdma_ecn_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "RX ECN Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_retx_bytes{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "TX Retransmit Bytes:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_ack_timeout{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "TX ACK Timeout:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req RX Oper Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_impl_nak_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req RX Implied NAK Seq Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_cqe_flush{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req RX CQE Flush:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_dup_response{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req RX Dup Response:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_tx_loc_sgl_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Req TX Local SGL Invalid:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX CQE Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_cqe_flush{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX CQE Flush:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_inval_request{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX Invalid Request:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_loc_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX Local Oper Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_pkt_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp TX Pkt Seq Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_rmt_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp TX Remote Access Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_rnr_retry_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp TX RNR Retry Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_loc_sgl_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp TX Local SGL Invalid:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_s0_table_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)> 0",
     "legendFormat": "Resp RX S0 Table Err:{{primus_lens_node_name}}"
    }
   ]
  },
  {
   "title": "RDMA Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "increase(workload_rdma_stat_dup_req{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_dup_request{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "DupReq:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_exceed_max{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_req_tx_retry_excd_err{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResExceedMax:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_length_mismatch{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_loc_len_err{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResLengthMismatch:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_exceeds_wqe{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResExceedsWqe:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_rx_invalid_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Rx Invalid Rkey:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_tx_invalid_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Tx Invalid Rkey:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_irrq_oflow{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_outof_buf{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Irrq Oflow:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_unsup_opcode{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_req_rx_inval_pkts{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Unsupported OpCode:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_unaligned_atomic{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_outof_atomic{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Unaligned Atomic:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_outouf_seq{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "MissingResp:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_invalid_dup_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Invalid Dup Rkey:{{primus_lens_node_name}}:{{device}}"
    }
   ]
  },
  {
   "title": "XGMI Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_gpu_xgmi_link_tx{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}}  TX"
    },
    {
     "expr": "sum(rate(gpu_xgmi_link_rx{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}}  RX"
    }
   ]
  },
  {
   "title": "PCIE Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_gpu_pcie_bandwidth_mbs{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "workload_gpu_utilization{workload_uid=\"$workload_uid\"}",
     "legendFormat": "{{primus_lens_node_name}}-GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Memory Util",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "100 - (workload_gpu_free_vram{workload_uid=\"$workload_uid\"}/workload_gpu_total_vram{workload_uid=\"$workload_uid\"} * 100)",
     "legendFormat": "{{primus_lens_node_name}}-GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "workload_gpu_socket_power_watts{workload_uid=\"$workload_uid\"}",
     "legendFormat": "{{primus_lens_node_name}}-GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "workload_gpu_total_vram{workload_uid=\"$workload_uid\"} - workload_gpu_free_vram{workload_uid=\"$workload_uid\"}",
     "legendFormat": "{{primus_lens_node_name}}-GPU{{gpu_id}}"
    }
   ]
  },
  {
   "title": "RDMA Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_rdma_stat_tx_roce_only_bytes{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name) or sum(rate(workload_rdma_stat_tx_rdma_ucast_bytes{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}} GPU {{gpu_id}} TX"
    },
    {
     "expr": "sum(rate(workload_rdma_stat_rx_roce_only_bytes{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name) or sum(rate(workload_rdma_stat_rx_rdma_ucast_bytes{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}} GPU {{gpu_id}} RX"
    }
   ]
  },
  {
   "title": "RDMA Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "sum(rate(workload_rdma_stat_tx_roce_only_pkts{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name) or sum(rate(workload_rdma_stat_tx_rdma_ucast_pkts{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}} GPU {{gpu_id}} TX"
    },
    {
     "expr": "sum(rate(workload_rdma_stat_rx_roce_only_pkts{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name) or sum(rate(workload_rdma_stat_rx_rdma_ucast_pkts{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}} GPU {{gpu_id}} RX"
    }
   ]
  },
  {
   "title": "RDMA Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_discards{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_rx_rdma_mtu_discard_pkts{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name,device)> 0",
     "legendFormat": "RX Roce Discards:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_discards{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_tx_rdma_mtu_discard_pkts{workload_uid=\"$workload_uid\"})) by (primus_lens_node_name,device)> 0",
     "legendFormat": "TX Roce Discards:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "TX Roce Errors:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_roce_errors{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "RX Roce Errors:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_seq_err_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_req_rx_pkt_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "NAK(Seq err):{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rnr_naks_rcvd{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_req_rx_rnr_retry_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "NAK(RNR):{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_resp_rx_outouf_seq{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Missing Resp:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_to_retransmits{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_tx_rdma_retx_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "ReTransmit:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_max_retry_exceeded{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_req_tx_retry_excd_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "MaxRetryExceeded:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_resp_rx_outouf_seq{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "MissingResp:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_unrecoverable_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_req_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "UnrecoverableErr:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_qp_op_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_req_tx_loc_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "LocalQpOpErr:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_local_protection_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_req_tx_loc_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "LocalProtectionErr:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_access_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0  or sum(increase(workload_rdma_stat_req_rx_rmt_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "RemoteAccessErr:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_invalid_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 or sum(increase(workload_rdma_stat_req_rx_rmt_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "RemoteInvalidReqErr:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_remote_op_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0  or sum(increase(workload_rdma_stat_resp_tx_rmt_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "RemoteOpErr:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_opcode_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Opcode Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Rx Domain Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Rx No Perm:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Rx Range Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_domain_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Tx Domain Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_no_perm{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Tx No Perm:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_range_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Tx Range Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rem_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0  or sum(increase(workload_rdma_stat_resp_tx_rmt_inval_req_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Rem Inv Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_mem_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0  or sum(increase(workload_rdma_stat_req_tx_mem_mgmt_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Mem Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Srq Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cmp_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0  or sum(increase(workload_rdma_stat_req_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Cmp Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_wqe_format_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Wqe Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_cq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Cq Load Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_srq_load_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Srq Load Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_tx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Tx Pci Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_res_rx_pci_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0 ",
     "legendFormat": "Res Rx Pci Err:{{primus_lens_node_name}}-{{device}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_cnp_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "TX CNP Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_rdma_cnp_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "RX CNP Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_rx_rdma_ecn_pkts{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "RX ECN Pkts:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_retx_bytes{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "TX Retransmit Bytes:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_tx_rdma_ack_timeout{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "TX ACK Timeout:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Req RX Oper Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_impl_nak_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Req RX Implied NAK Seq Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_cqe_flush{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Req RX CQE Flush:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_rx_dup_response{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Req RX Dup Response:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_req_tx_loc_sgl_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Req TX Local SGL Invalid:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_cqe_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp RX CQE Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_cqe_flush{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp RX CQE Flush:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_inval_request{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp RX Invalid Request:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_loc_oper_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp RX Local Oper Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_pkt_seq_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp TX Pkt Seq Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_rmt_acc_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp TX Remote Access Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_rnr_retry_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp TX RNR Retry Err:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_tx_loc_sgl_inv_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp TX Local SGL Invalid:{{primus_lens_node_name}}"
    },
    {
     "expr": "sum(increase(workload_rdma_stat_resp_rx_s0_table_err{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,device)> 0",
     "legendFormat": "Resp RX S0 Table Err:{{primus_lens_node_name}}"
    }
   ]
  },
  {
   "title": "XGMI Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "KiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_gpu_xgmi_link_tx{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}} GPU {{gpu_id}} TX"
    },
    {
     "expr": "sum(rate(gpu_xgmi_link_rx{workload_uid=\"$workload_uid\"}[1m])) by (gpu_id,primus_lens_node_name)",
     "legendFormat": "{{primus_lens_node_name}} GPU {{gpu_id}} RX"
    }
   ]
  },
  {
   "title": "PCIE Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "sum(rate(workload_gpu_pcie_bandwidth_mbs{workload_uid=\"$workload_uid\"}[1m])) by (primus_lens_node_name,gpu_id)",
     "legendFormat": "GPU {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "increase(workload_rdma_stat_dup_req{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_dup_request{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "DupReq:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_exceed_max{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_req_tx_retry_excd_err{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResExceedMax:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_length_mismatch{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_loc_len_err{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResLengthMismatch:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_exceeds_wqe{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "ResExceedsWqe:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_rx_invalid_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Rx Invalid Rkey:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_tx_invalid_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Tx Invalid Rkey:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_irrq_oflow{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_outof_buf{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Irrq Oflow:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_unsup_opcode{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_req_rx_inval_pkts{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Unsupported OpCode:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_unaligned_atomic{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_outof_atomic{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Unaligned Atomic:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_missing_resp{workload_uid=\"$workload_uid\"}[1m]) > 0 or increase(workload_rdma_stat_resp_rx_outouf_seq{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "MissingResp:{{primus_lens_node_name}}:{{device}}"
    },
    {
     "expr": "increase(workload_rdma_stat_res_invalid_dup_rkey{workload_uid=\"$workload_uid\"}[1m]) > 0",
     "legendFormat": "Res Invalid Dup Rkey:{{primus_lens_node_name}}:{{device}}"
    }
   ]
  }
 ]
}