{{- if and .Values.langfuse_proxy .Values.langfuse_proxy.enable .Values.langfuse_proxy.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.langfuse_proxy.secret }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  public_key: "{{ .Values.langfuse_proxy.public_key }}"
  secret_key: "{{ .Values.langfuse_proxy.secret_key }}"
{{- end }}
