#
# Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
# See LICENSE for license information.
#

{{- if and .Values.llm_gateway .Values.llm_gateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-llm-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  litellm_admin_key: "{{ .Values.llm_gateway.litellm_admin_key }}"
  litellm_endpoint: "{{ .Values.llm_gateway.litellm_endpoint }}"
  litellm_team_id: "{{ .Values.llm_gateway.litellm_team_id }}"
{{- end }}
