{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lens.serviceAccountName" . }}
  namespace: {{ include "lens.namespace" . }}
  labels:
    {{- include "lens.labels" . | nindent 4 }}
{{- end }}
