/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// AddonSourceStatusApplyConfiguration represents a declarative configuration of the AddonSourceStatus type for use
// with apply.
type AddonSourceStatusApplyConfiguration struct {
	HelmRepositoryStatus *HelmRepositoryStatusApplyConfiguration `json:"helm,omitempty"`
}

// AddonSourceStatusApplyConfiguration constructs a declarative configuration of the AddonSourceStatus type for use with
// apply.
func AddonSourceStatus() *AddonSourceStatusApplyConfiguration {
	return &AddonSourceStatusApplyConfiguration{}
}

// WithHelmRepositoryStatus sets the HelmRepositoryStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HelmRepositoryStatus field is set to the value of the last call.
func (b *AddonSourceStatusApplyConfiguration) WithHelmRepositoryStatus(value *HelmRepositoryStatusApplyConfiguration) *AddonSourceStatusApplyConfiguration {
	b.HelmRepositoryStatus = value
	return b
}
