/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ClusterStatusApplyConfiguration represents a declarative configuration of the ClusterStatus type for use
// with apply.
type ClusterStatusApplyConfiguration struct {
	ControlPlaneStatus *ControlPlaneStatusApplyConfiguration `json:"controlPlaneStatus,omitempty"`
	StorageStatus      []StorageStatusApplyConfiguration     `json:"storageStatus,omitempty"`
}

// ClusterStatusApplyConfiguration constructs a declarative configuration of the ClusterStatus type for use with
// apply.
func ClusterStatus() *ClusterStatusApplyConfiguration {
	return &ClusterStatusApplyConfiguration{}
}

// WithControlPlaneStatus sets the ControlPlaneStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ControlPlaneStatus field is set to the value of the last call.
func (b *ClusterStatusApplyConfiguration) WithControlPlaneStatus(value *ControlPlaneStatusApplyConfiguration) *ClusterStatusApplyConfiguration {
	b.ControlPlaneStatus = value
	return b
}

// WithStorageStatus adds the given value to the StorageStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the StorageStatus field.
func (b *ClusterStatusApplyConfiguration) WithStorageStatus(values ...*StorageStatusApplyConfiguration) *ClusterStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithStorageStatus")
		}
		b.StorageStatus = append(b.StorageStatus, *values[i])
	}
	return b
}
