/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HelmStatusApplyConfiguration represents a declarative configuration of the HelmStatus type for use
// with apply.
type HelmStatusApplyConfiguration struct {
	Values     *string `json:"values,omitempty"`
	ValuesYAML *string `json:"valuesYaml,omitempty"`
}

// HelmStatusApplyConfiguration constructs a declarative configuration of the HelmStatus type for use with
// apply.
func HelmStatus() *HelmStatusApplyConfiguration {
	return &HelmStatusApplyConfiguration{}
}

// WithValues sets the Values field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Values field is set to the value of the last call.
func (b *HelmStatusApplyConfiguration) WithValues(value string) *HelmStatusApplyConfiguration {
	b.Values = &value
	return b
}

// WithValuesYAML sets the ValuesYAML field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ValuesYAML field is set to the value of the last call.
func (b *HelmStatusApplyConfiguration) WithValuesYAML(value string) *HelmStatusApplyConfiguration {
	b.ValuesYAML = &value
	return b
}
