/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HybridStorageSpecApplyConfiguration represents a declarative configuration of the HybridStorageSpec type for use
// with apply.
type HybridStorageSpecApplyConfiguration struct {
	PrimaryDeviceClass   *string `json:"primaryDeviceClass,omitempty"`
	SecondaryDeviceClass *string `json:"secondaryDeviceClass,omitempty"`
}

// HybridStorageSpecApplyConfiguration constructs a declarative configuration of the HybridStorageSpec type for use with
// apply.
func HybridStorageSpec() *HybridStorageSpecApplyConfiguration {
	return &HybridStorageSpecApplyConfiguration{}
}

// WithPrimaryDeviceClass sets the PrimaryDeviceClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrimaryDeviceClass field is set to the value of the last call.
func (b *HybridStorageSpecApplyConfiguration) WithPrimaryDeviceClass(value string) *HybridStorageSpecApplyConfiguration {
	b.PrimaryDeviceClass = &value
	return b
}

// WithSecondaryDeviceClass sets the SecondaryDeviceClass field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecondaryDeviceClass field is set to the value of the last call.
func (b *HybridStorageSpecApplyConfiguration) WithSecondaryDeviceClass(value string) *HybridStorageSpecApplyConfiguration {
	b.SecondaryDeviceClass = &value
	return b
}
