/*
 * Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// InferenceInstanceApplyConfiguration represents a declarative configuration of the InferenceInstance type for use
// with apply.
type InferenceInstanceApplyConfiguration struct {
	BaseUrl    *string `json:"baseUrl,omitempty"`
	ApiKey     *string `json:"apiKey,omitempty"`
	Model      *string `json:"model,omitempty"`
	WorkloadID *string `json:"workloadID,omitempty"`
}

// InferenceInstanceApplyConfiguration constructs a declarative configuration of the InferenceInstance type for use with
// apply.
func InferenceInstance() *InferenceInstanceApplyConfiguration {
	return &InferenceInstanceApplyConfiguration{}
}

// WithBaseUrl sets the BaseUrl field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseUrl field is set to the value of the last call.
func (b *InferenceInstanceApplyConfiguration) WithBaseUrl(value string) *InferenceInstanceApplyConfiguration {
	b.BaseUrl = &value
	return b
}

// WithApiKey sets the ApiKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiKey field is set to the value of the last call.
func (b *InferenceInstanceApplyConfiguration) WithApiKey(value string) *InferenceInstanceApplyConfiguration {
	b.ApiKey = &value
	return b
}

// WithModel sets the Model field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Model field is set to the value of the last call.
func (b *InferenceInstanceApplyConfiguration) WithModel(value string) *InferenceInstanceApplyConfiguration {
	b.Model = &value
	return b
}

// WithWorkloadID sets the WorkloadID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WorkloadID field is set to the value of the last call.
func (b *InferenceInstanceApplyConfiguration) WithWorkloadID(value string) *InferenceInstanceApplyConfiguration {
	b.WorkloadID = &value
	return b
}
