/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ModelSpecApplyConfiguration represents a declarative configuration of the ModelSpec type for use
// with apply.
//
// ModelSpec defines the desired state of Model
type ModelSpecApplyConfiguration struct {
	// DisplayName is the friendly name shown in the UI
	DisplayName *string `json:"displayName,omitempty"`
	// Description describes the model
	Description *string `json:"description,omitempty"`
	// Icon is the URL or Base64 of the model icon
	Icon *string `json:"icon,omitempty"`
	// Label is the model label
	Label *string `json:"label,omitempty"`
	// Tags are used for search and classification (e.g. "LLM", "CV", "ASR")
	Tags []string `json:"tags,omitempty"`
	// MaxTokens is the maximum context length of the model (from config.json max_position_embeddings)
	MaxTokens *int `json:"maxTokens,omitempty"`
	// Source defines where to pull the model from
	Source *ModelSourceApplyConfiguration `json:"source,omitempty"`
	// Workspace specifies which workspace this model belongs to (for local models only)
	// Empty string means "public" - the model will be downloaded to all workspaces
	// Non-empty means the model is private to a specific workspace
	Workspace *string `json:"workspace,omitempty"`
	// Origin indicates where the model came from:
	// - "external": downloaded from HuggingFace or connected via remote API (default)
	// - "fine_tuned": produced by SFT training within the platform
	// - "rl_trained": produced by RL training (GRPO/PPO) within the platform
	Origin *string `json:"origin,omitempty"`
	// SftJobId is the workload ID of the training job that produced this model
	// (origin=fine_tuned for SFT, origin=rl_trained for RL)
	SftJobId *string `json:"sftJobId,omitempty"`
	// BaseModel is the HuggingFace name of the base model used for fine-tuning (origin=fine_tuned only)
	BaseModel *string `json:"baseModel,omitempty"`
	// TargetVolume optionally selects which volume of the workspace to download to
	// when the workspace has multiple volumes (e.g. PFS+HostPath). Value is a volume's
	// MountPath (or HostPath when MountPath is empty). If empty, the controller uses
	// the workspace's first PFS volume (or first volume).
	TargetVolume *string `json:"targetVolume,omitempty"`
	// TargetSubpath is an optional sub-directory under "<volume>/models/<safe-name>"
	// to keep multiple imports of the same model separated. Empty = default layout.
	TargetSubpath *string `json:"targetSubpath,omitempty"`
}

// ModelSpecApplyConfiguration constructs a declarative configuration of the ModelSpec type for use with
// apply.
func ModelSpec() *ModelSpecApplyConfiguration {
	return &ModelSpecApplyConfiguration{}
}

// WithDisplayName sets the DisplayName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayName field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithDisplayName(value string) *ModelSpecApplyConfiguration {
	b.DisplayName = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithDescription(value string) *ModelSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithIcon sets the Icon field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Icon field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithIcon(value string) *ModelSpecApplyConfiguration {
	b.Icon = &value
	return b
}

// WithLabel sets the Label field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Label field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithLabel(value string) *ModelSpecApplyConfiguration {
	b.Label = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *ModelSpecApplyConfiguration) WithTags(values ...string) *ModelSpecApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}

// WithMaxTokens sets the MaxTokens field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxTokens field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithMaxTokens(value int) *ModelSpecApplyConfiguration {
	b.MaxTokens = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithSource(value *ModelSourceApplyConfiguration) *ModelSpecApplyConfiguration {
	b.Source = value
	return b
}

// WithWorkspace sets the Workspace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Workspace field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithWorkspace(value string) *ModelSpecApplyConfiguration {
	b.Workspace = &value
	return b
}

// WithOrigin sets the Origin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Origin field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithOrigin(value string) *ModelSpecApplyConfiguration {
	b.Origin = &value
	return b
}

// WithSftJobId sets the SftJobId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SftJobId field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithSftJobId(value string) *ModelSpecApplyConfiguration {
	b.SftJobId = &value
	return b
}

// WithBaseModel sets the BaseModel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseModel field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithBaseModel(value string) *ModelSpecApplyConfiguration {
	b.BaseModel = &value
	return b
}

// WithTargetVolume sets the TargetVolume field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetVolume field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithTargetVolume(value string) *ModelSpecApplyConfiguration {
	b.TargetVolume = &value
	return b
}

// WithTargetSubpath sets the TargetSubpath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetSubpath field is set to the value of the last call.
func (b *ModelSpecApplyConfiguration) WithTargetSubpath(value string) *ModelSpecApplyConfiguration {
	b.TargetSubpath = &value
	return b
}
