/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	amdv1 "github.com/AMD-AIG-AIMA/SAFE/apis/pkg/apis/amd/v1"
	corev1 "k8s.io/api/core/v1"
)

// ModelSourceApplyConfiguration represents a declarative configuration of the ModelSource type for use
// with apply.
//
// ModelSource describes the model storage location
type ModelSourceApplyConfiguration struct {
	// URL is the pull address (e.g., "meta-llama/Llama-2-7b", "s3://bucket/model", "https://api.openai.com")
	URL *string `json:"url,omitempty"`
	// AccessMode defines how to access the model:
	// - "remote_api": Call external API directly (e.g., OpenAI, DeepSeek)
	// - "local": Download model and run inference service locally
	AccessMode *amdv1.AccessMode `json:"accessMode,omitempty"`
	// ModelName is the model identifier used when calling the API
	// Required for remote_api mode (e.g., "gpt-4", "deepseek-chat")
	// For local mode, this is auto-extracted from URL or user-specified
	ModelName *string `json:"modelName,omitempty"`
	// Token references a Secret containing the auth token for pulling the model (HuggingFace token)
	// Used for local mode to access private models
	Token *corev1.LocalObjectReference `json:"token,omitempty"`
	// ApiKey references a Secret containing the API key for remote API access
	// Used for remote_api mode to authenticate with external services (e.g., OpenAI, DeepSeek)
	ApiKey *corev1.LocalObjectReference `json:"apiKey,omitempty"`
	// LocalPath is the NFS/PFS path where the model files already exist.
	// Used for "local_path" access mode (SFT training output) — skips download entirely.
	LocalPath *string `json:"localPath,omitempty"`
}

// ModelSourceApplyConfiguration constructs a declarative configuration of the ModelSource type for use with
// apply.
func ModelSource() *ModelSourceApplyConfiguration {
	return &ModelSourceApplyConfiguration{}
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithURL(value string) *ModelSourceApplyConfiguration {
	b.URL = &value
	return b
}

// WithAccessMode sets the AccessMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessMode field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithAccessMode(value amdv1.AccessMode) *ModelSourceApplyConfiguration {
	b.AccessMode = &value
	return b
}

// WithModelName sets the ModelName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelName field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithModelName(value string) *ModelSourceApplyConfiguration {
	b.ModelName = &value
	return b
}

// WithToken sets the Token field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Token field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithToken(value corev1.LocalObjectReference) *ModelSourceApplyConfiguration {
	b.Token = &value
	return b
}

// WithApiKey sets the ApiKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiKey field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithApiKey(value corev1.LocalObjectReference) *ModelSourceApplyConfiguration {
	b.ApiKey = &value
	return b
}

// WithLocalPath sets the LocalPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalPath field is set to the value of the last call.
func (b *ModelSourceApplyConfiguration) WithLocalPath(value string) *ModelSourceApplyConfiguration {
	b.LocalPath = &value
	return b
}
