/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NodePodUsageApplyConfiguration represents a declarative configuration of the NodePodUsage type for use
// with apply.
//
// NodePodUsage aggregates a workload's pods on a single admin node, bucketed by
// the workload resource index (resourceId). It lets the resource/scheduling
// hot path compute usage without per-pod records:
//
// usage(node) = sum over rid of count * perPodResource[rid]
//
// Running counts pods in the Running phase (current actual usage); Active counts
// non-terminated pods (Pending/Running/Unknown — reserved usage used by quota /
// scheduling). Terminated pods (Succeeded/Failed) are excluded from both.
type NodePodUsageApplyConfiguration struct {
	// Node is the admin node name these pods are scheduled on.
	Node *string `json:"node,omitempty"`
	// Running maps resourceId (decimal string, e.g. "0") -> number of running
	// pods of that resource on this node. CRD/OpenAPI map keys must be strings,
	// so the int8 resourceId is encoded as its decimal string.
	Running map[string]int `json:"running,omitempty"`
	// Active maps resourceId (decimal string) -> number of non-terminated pods
	// of that resource on this node.
	Active map[string]int `json:"active,omitempty"`
}

// NodePodUsageApplyConfiguration constructs a declarative configuration of the NodePodUsage type for use with
// apply.
func NodePodUsage() *NodePodUsageApplyConfiguration {
	return &NodePodUsageApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *NodePodUsageApplyConfiguration) WithNode(value string) *NodePodUsageApplyConfiguration {
	b.Node = &value
	return b
}

// WithRunning puts the entries into the Running field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Running field,
// overwriting an existing map entries in Running field with the same key.
func (b *NodePodUsageApplyConfiguration) WithRunning(entries map[string]int) *NodePodUsageApplyConfiguration {
	if b.Running == nil && len(entries) > 0 {
		b.Running = make(map[string]int, len(entries))
	}
	for k, v := range entries {
		b.Running[k] = v
	}
	return b
}

// WithActive puts the entries into the Active field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Active field,
// overwriting an existing map entries in Active field with the same key.
func (b *NodePodUsageApplyConfiguration) WithActive(entries map[string]int) *NodePodUsageApplyConfiguration {
	if b.Active == nil && len(entries) > 0 {
		b.Active = make(map[string]int, len(entries))
	}
	for k, v := range entries {
		b.Active[k] = v
	}
	return b
}
