/*
 * Copyright (c) 2025, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// NodeTemplateSpecApplyConfiguration represents a declarative configuration of the NodeTemplateSpec type for use
// with apply.
type NodeTemplateSpecApplyConfiguration struct {
	AddOnTemplates []string `json:"addOnTemplates,omitempty"`
}

// NodeTemplateSpecApplyConfiguration constructs a declarative configuration of the NodeTemplateSpec type for use with
// apply.
func NodeTemplateSpec() *NodeTemplateSpecApplyConfiguration {
	return &NodeTemplateSpecApplyConfiguration{}
}

// WithAddOnTemplates adds the given value to the AddOnTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AddOnTemplates field.
func (b *NodeTemplateSpecApplyConfiguration) WithAddOnTemplates(values ...string) *NodeTemplateSpecApplyConfiguration {
	for i := range values {
		b.AddOnTemplates = append(b.AddOnTemplates, values[i])
	}
	return b
}
