/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ResourceStatusApplyConfiguration represents a declarative configuration of the ResourceStatus type for use
// with apply.
type ResourceStatusApplyConfiguration struct {
	PrePaths     []string                            `json:"prePaths,omitempty"`
	MessagePaths []string                            `json:"messagePaths,omitempty"`
	ReasonPaths  []string                            `json:"reasonPaths,omitempty"`
	Phases       []PhaseExpressionApplyConfiguration `json:"phases,omitempty"`
}

// ResourceStatusApplyConfiguration constructs a declarative configuration of the ResourceStatus type for use with
// apply.
func ResourceStatus() *ResourceStatusApplyConfiguration {
	return &ResourceStatusApplyConfiguration{}
}

// WithPrePaths adds the given value to the PrePaths field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PrePaths field.
func (b *ResourceStatusApplyConfiguration) WithPrePaths(values ...string) *ResourceStatusApplyConfiguration {
	for i := range values {
		b.PrePaths = append(b.PrePaths, values[i])
	}
	return b
}

// WithMessagePaths adds the given value to the MessagePaths field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MessagePaths field.
func (b *ResourceStatusApplyConfiguration) WithMessagePaths(values ...string) *ResourceStatusApplyConfiguration {
	for i := range values {
		b.MessagePaths = append(b.MessagePaths, values[i])
	}
	return b
}

// WithReasonPaths adds the given value to the ReasonPaths field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ReasonPaths field.
func (b *ResourceStatusApplyConfiguration) WithReasonPaths(values ...string) *ResourceStatusApplyConfiguration {
	for i := range values {
		b.ReasonPaths = append(b.ReasonPaths, values[i])
	}
	return b
}

// WithPhases adds the given value to the Phases field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Phases field.
func (b *ResourceStatusApplyConfiguration) WithPhases(values ...*PhaseExpressionApplyConfiguration) *ResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPhases")
		}
		b.Phases = append(b.Phases, *values[i])
	}
	return b
}
