/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
)

// ServiceApplyConfiguration represents a declarative configuration of the Service type for use
// with apply.
type ServiceApplyConfiguration struct {
	Protocol    *corev1.Protocol    `json:"protocol,omitempty"`
	Port        *int                `json:"port,omitempty"`
	NodePort    *int                `json:"nodePort,omitempty"`
	TargetPort  *int                `json:"targetPort,omitempty"`
	ServiceType *corev1.ServiceType `json:"serviceType,omitempty"`
	Extends     map[string]string   `json:"extends,omitempty"`
}

// ServiceApplyConfiguration constructs a declarative configuration of the Service type for use with
// apply.
func Service() *ServiceApplyConfiguration {
	return &ServiceApplyConfiguration{}
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *ServiceApplyConfiguration) WithProtocol(value corev1.Protocol) *ServiceApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ServiceApplyConfiguration) WithPort(value int) *ServiceApplyConfiguration {
	b.Port = &value
	return b
}

// WithNodePort sets the NodePort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodePort field is set to the value of the last call.
func (b *ServiceApplyConfiguration) WithNodePort(value int) *ServiceApplyConfiguration {
	b.NodePort = &value
	return b
}

// WithTargetPort sets the TargetPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetPort field is set to the value of the last call.
func (b *ServiceApplyConfiguration) WithTargetPort(value int) *ServiceApplyConfiguration {
	b.TargetPort = &value
	return b
}

// WithServiceType sets the ServiceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceType field is set to the value of the last call.
func (b *ServiceApplyConfiguration) WithServiceType(value corev1.ServiceType) *ServiceApplyConfiguration {
	b.ServiceType = &value
	return b
}

// WithExtends puts the entries into the Extends field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Extends field,
// overwriting an existing map entries in Extends field with the same key.
func (b *ServiceApplyConfiguration) WithExtends(entries map[string]string) *ServiceApplyConfiguration {
	if b.Extends == nil && len(entries) > 0 {
		b.Extends = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Extends[k] = v
	}
	return b
}
