/*
 * Copyright (C) 2025-2026, Advanced Micro Devices, Inc. All rights reserved.
 * See LICENSE for license information.
 */
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// WorkloadExternalExecutionApplyConfiguration represents a declarative configuration of the WorkloadExternalExecution type for use
// with apply.
//
// WorkloadExternalExecution records what a workload needs to resume its own demand and
// claim after a restart or a lost reply.
//
// Every identifier here is written before the request it belongs to is sent. A request
// whose response never arrived can only be reconciled by replaying the same id with the
// same body: allocating a fresh one would ask the provider for a second reservation while
// the first may already exist, and nothing afterwards would notice the surplus.
type WorkloadExternalExecutionApplyConfiguration struct {
	// PlacementMode selects capacity acquisition. Empty or "claim" is the legacy HTTP path;
	// "kube-scheduler" uses Pod/PodTemplate/ProvisioningRequest and keeps claim fields empty.
	PlacementMode *string `json:"placementMode,omitempty"`
	// ProvisioningRequest is the name of the autoscaling ProvisioningRequest for a gang on
	// the kube-scheduler path. Empty for single-pod workloads.
	ProvisioningRequest *string `json:"provisioningRequest,omitempty"`
	// ProvisioningAttempt counts BookingExpired/CapacityRevoked rebuilds within one
	// dispatch generation so PR/PodTemplate names stay unique without bumping dispatch-count.
	ProvisioningAttempt *int32 `json:"provisioningAttempt,omitempty"`
	// ProvisioningCondition is the last observed PR condition type/reason/message for UI.
	ProvisioningCondition *string `json:"provisioningCondition,omitempty"`
	// ResolvedImages are Spec.Images pinned to digest before Pod/PodTemplate create on the
	// kube-scheduler path. Empty on the claim path (provider freezes digest at claim time).
	ResolvedImages []string `json:"resolvedImages,omitempty"`
	// The dispatch generation these identifiers belong to
	DispatchGeneration *int32 `json:"dispatchGeneration,omitempty"`
	// Demand identity and the revision last published
	DemandId        *string `json:"demandId,omitempty"`
	DemandRevision  *int32  `json:"demandRevision,omitempty"`
	DemandRequestId *string `json:"demandRequestId,omitempty"`
	// Observation and expiry of the current demand revision. They are stored rather than
	// recomputed because the contract refuses a revision whose body changed, and both
	// timestamps are part of that body: taking the clock again on every pass would turn an
	// intended replay into a conflict.
	DemandObservedAt *metav1.Time `json:"demandObservedAt,omitempty"`
	DemandExpiresAt  *metav1.Time `json:"demandExpiresAt,omitempty"`
	// Queue and capacity snapshot revisions sent with the current demand revision. They
	// are part of the body and fixed with the revision for the same reason.
	DemandQueueSnapshot    *string `json:"demandQueueSnapshot,omitempty"`
	DemandCapacitySnapshot *string `json:"demandCapacitySnapshot,omitempty"`
	// Set once the demand has been withdrawn, so the withdrawal is published exactly once.
	// Repeating it would reuse a revision number under a changed body, which the contract
	// refuses, and would eventually collide with a revision issued for the opposite meaning.
	DemandWithdrawn *bool `json:"demandWithdrawn,omitempty"`
	// Claim identity, the request id that created it and the phase last observed
	ClaimId        *string `json:"claimId,omitempty"`
	ClaimRequestId *string `json:"claimRequestId,omitempty"`
	ClaimRevision  *int32  `json:"claimRevision,omitempty"`
	ClaimPhase     *string `json:"claimPhase,omitempty"`
	// ReleaseRequestId is persisted before ReleaseClaim so a lost reply is retried with
	// the same idempotency key rather than a new one.
	ReleaseRequestId *string `json:"releaseRequestId,omitempty"`
	// Expected revision and reason sent with ReleaseRequestId. They are fixed with the id
	// because the provider binds a request id to the body it first carried.
	ReleaseExpectedRevision *int32  `json:"releaseExpectedRevision,omitempty"`
	ReleaseReason           *string `json:"releaseReason,omitempty"`
	// Placements approved by the provider, kept so the dispatcher builds the pod from the
	// reservation that was granted rather than asking for a new plan
	Placements []WorkloadExternalPlacementApplyConfiguration `json:"placements,omitempty"`
	// Set once the workload is finished but the provider has not confirmed release. The
	// resources stay charged to the workspace while it is true.
	Reclaiming *bool `json:"reclaiming,omitempty"`
}

// WorkloadExternalExecutionApplyConfiguration constructs a declarative configuration of the WorkloadExternalExecution type for use with
// apply.
func WorkloadExternalExecution() *WorkloadExternalExecutionApplyConfiguration {
	return &WorkloadExternalExecutionApplyConfiguration{}
}

// WithPlacementMode sets the PlacementMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PlacementMode field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithPlacementMode(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.PlacementMode = &value
	return b
}

// WithProvisioningRequest sets the ProvisioningRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProvisioningRequest field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithProvisioningRequest(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.ProvisioningRequest = &value
	return b
}

// WithProvisioningAttempt sets the ProvisioningAttempt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProvisioningAttempt field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithProvisioningAttempt(value int32) *WorkloadExternalExecutionApplyConfiguration {
	b.ProvisioningAttempt = &value
	return b
}

// WithProvisioningCondition sets the ProvisioningCondition field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProvisioningCondition field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithProvisioningCondition(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.ProvisioningCondition = &value
	return b
}

// WithResolvedImages adds the given value to the ResolvedImages field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ResolvedImages field.
func (b *WorkloadExternalExecutionApplyConfiguration) WithResolvedImages(values ...string) *WorkloadExternalExecutionApplyConfiguration {
	for i := range values {
		b.ResolvedImages = append(b.ResolvedImages, values[i])
	}
	return b
}

// WithDispatchGeneration sets the DispatchGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DispatchGeneration field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDispatchGeneration(value int32) *WorkloadExternalExecutionApplyConfiguration {
	b.DispatchGeneration = &value
	return b
}

// WithDemandId sets the DemandId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemandId field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDemandId(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.DemandId = &value
	return b
}

// WithDemandRevision sets the DemandRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemandRevision field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDemandRevision(value int32) *WorkloadExternalExecutionApplyConfiguration {
	b.DemandRevision = &value
	return b
}

// WithDemandRequestId sets the DemandRequestId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemandRequestId field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDemandRequestId(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.DemandRequestId = &value
	return b
}

// WithDemandObservedAt sets the DemandObservedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemandObservedAt field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDemandObservedAt(value metav1.Time) *WorkloadExternalExecutionApplyConfiguration {
	b.DemandObservedAt = &value
	return b
}

// WithDemandExpiresAt sets the DemandExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemandExpiresAt field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDemandExpiresAt(value metav1.Time) *WorkloadExternalExecutionApplyConfiguration {
	b.DemandExpiresAt = &value
	return b
}

// WithDemandQueueSnapshot sets the DemandQueueSnapshot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemandQueueSnapshot field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDemandQueueSnapshot(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.DemandQueueSnapshot = &value
	return b
}

// WithDemandCapacitySnapshot sets the DemandCapacitySnapshot field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemandCapacitySnapshot field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDemandCapacitySnapshot(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.DemandCapacitySnapshot = &value
	return b
}

// WithDemandWithdrawn sets the DemandWithdrawn field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DemandWithdrawn field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithDemandWithdrawn(value bool) *WorkloadExternalExecutionApplyConfiguration {
	b.DemandWithdrawn = &value
	return b
}

// WithClaimId sets the ClaimId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClaimId field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithClaimId(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.ClaimId = &value
	return b
}

// WithClaimRequestId sets the ClaimRequestId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClaimRequestId field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithClaimRequestId(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.ClaimRequestId = &value
	return b
}

// WithClaimRevision sets the ClaimRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClaimRevision field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithClaimRevision(value int32) *WorkloadExternalExecutionApplyConfiguration {
	b.ClaimRevision = &value
	return b
}

// WithClaimPhase sets the ClaimPhase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClaimPhase field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithClaimPhase(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.ClaimPhase = &value
	return b
}

// WithReleaseRequestId sets the ReleaseRequestId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseRequestId field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithReleaseRequestId(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.ReleaseRequestId = &value
	return b
}

// WithReleaseExpectedRevision sets the ReleaseExpectedRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseExpectedRevision field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithReleaseExpectedRevision(value int32) *WorkloadExternalExecutionApplyConfiguration {
	b.ReleaseExpectedRevision = &value
	return b
}

// WithReleaseReason sets the ReleaseReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReleaseReason field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithReleaseReason(value string) *WorkloadExternalExecutionApplyConfiguration {
	b.ReleaseReason = &value
	return b
}

// WithPlacements adds the given value to the Placements field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Placements field.
func (b *WorkloadExternalExecutionApplyConfiguration) WithPlacements(values ...*WorkloadExternalPlacementApplyConfiguration) *WorkloadExternalExecutionApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPlacements")
		}
		b.Placements = append(b.Placements, *values[i])
	}
	return b
}

// WithReclaiming sets the Reclaiming field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reclaiming field is set to the value of the last call.
func (b *WorkloadExternalExecutionApplyConfiguration) WithReclaiming(value bool) *WorkloadExternalExecutionApplyConfiguration {
	b.Reclaiming = &value
	return b
}
