{{- if and .Values.a2a_gateway .Values.a2a_gateway.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-a2a-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: a2a-gateway
spec:
  selector:
    matchLabels:
      app: a2a-gateway
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
{{- end }}
