{{- if and .Values.claw .Values.claw.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.claw.service_account_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: robust-claw-unified
    app.kubernetes.io/managed-by: Helm
{{- end }}
